### ISSUE TITLE
iOS 13 BackgroundTasks API

### ISSUE THREAD

**Issue by Kymer** [fluttercommunity/flutter_workmanager#109]
With the new iOS 13 [BackgroundTasks](https://developer.apple.com/documentation/backgroundtasks) API we can now more closely match the existing Android workmanager implementation. The goals is to adapt the new API on iOS 13 and up but still keep our existing app background refresh implementation on older versions.

We decided to abstract away the iOS 13 API into its own dedicated framework: see [ios-workmanager](https://github.com/vrtdev/ios-workmanager). As soon as development is done (see [issue #1](https://github.com/vrtdev/ios-workmanager/issues/1)), we can add that module as a CocoaPod dependency.

In this issue we'll map the incoming flutter arguments to the needed iOS specific constraints and properties.

**Comment by sdebruyn** [comment]
Would be super helpful!

**Comment by tony123S** [comment]
Does it support One off task now?

**Comment by bretie** [comment]
@Kymer This is irrelevant to your implementation...

I implemented my own plugin using Android's WorkManager. Works great in the background and runs all my task perfectly.

Now for the iOS implementation I was looking for something like Android's WorkManager... although the only one I've found was this documentation:

#1: https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh

#2
https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask

Is this the same API you plan on using?

**Comment by lymanlai** [comment]
> @Kymer This is irrelevant to your implementation...
> 
> I implemented my own plugin using Android's WorkManager. Works great in the background and runs all my task perfectly.
> 
> Now for the iOS implementation I was looking for something like Android's WorkManager... although the only one I've found was this documentation:
> 
> #1: https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh
> 
> #2
> https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask
> 
> Is this the same API you plan on using?

I think so ;)

**Comment by ovaldi** [comment]
Thank you, I'm looking forward this feature, 👍

**Comment by otopba** [comment]
@Kymer Hi!
Any updates? =)

**Comment by TommasoAzz** [comment]
Now that the package is being maintained again, is it going to be updated with this new API?

**Comment by ened** [comment]
@TommasoAzz Yes, planning to take care of that. Rough action plan:

1. factory pattern (#240)
2. CI system running (GH actions etc)
3. 0.3.0
4. null-safety
5. 0.4.0
6. bugfixes when necessary (will need some help to sort & prioritise)
7. 0.4.1
8. Start looking at new features like BG processing.

It would be nice to cooperate with @Kymer and possibly merge the projects?

**Comment by lpsBetty** [comment]
@ened that would be so great, do you have any plan when this action plan will be executed? 😅

**Comment by nathanogunleye** [comment]
Can anyone share the progress on this work? Is this being looked into in the dev builds?

**Comment by Jonas-Sander** [comment]
Would love to have this!

**Comment by ened** [comment]
Please have a test w/ 0.5.0-dev.8.
