### ISSUE TITLE
iOS Build error

### ISSUE THREAD

**Issue by dmasotti** [fluttercommunity/flutter_workmanager#153]
I've tried to build for ios 

but it is stopping with this error:

> - `workmanager` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

i have tried this :
https://github.com/vrtdev/flutter_workmanager/issues/57
with no success so I added the line 

s.swift_version = '4.2' to the file  flutter_workmanager/ios/workmanager.podspec
and now it stops with this error:

fatal error: module map file '/Users/macbookpro/Coding/flutter/rhd/build/ios/Debug-iphonesimulator/workmanager/workmanager.modulemap' not found

this is flutter doctor output:

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale it)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.0)
[✓] Connected device (1 available)

**Comment by AamirSk** [comment]
Any updates on this? I am also facing issue for iOS.
