### ISSUE TITLE
Allow `null` as inputData parameter

### ISSUE THREAD

**Issue by nioncode** [fluttercommunity/flutter_workmanager#158]
It would be great if `null` values would be supported as fields of `inputData`.
Currently, this fails, because `flutter_workmanager` explicitly checks for compatible types: https://github.com/vrtdev/flutter_workmanager/blob/e237220996c3238fa2e47da0994cb6832e557a0b/lib/src/workmanager.dart#L210-L220

Thus, calling the following method will throw an Exception:
```dart
Workmanager.registerOneOffTask('taskId', 'taskName', inputData: {'optional': null});
```

To make this work, I now have to manually do a `null` check on each of my input parameters that might be optional instead of relying on `jsonEncode` and `jsonDecode` to do the right thing.
It would be great if `Workmanager` would allow `null` values instead.

**Comment by tony123S** [comment]
What if I want to pass a object as parameter?

**Comment by petermnt** [comment]
This is not possible as it's a limitation of workmanager, only int, bool, double and String's are supported.

**Comment by tony123S** [comment]
Thanks .

**Comment by tony123S** [comment]
List can't pass a well?

**Comment by KarnerTh** [comment]
@tony123S you can pass an object by encoding it via `jsonEncode()` to a String and parse it back with `jsonDecode()` to a Map where you need it

**Comment by nioncode** [comment]
@ened why did you close this? Was this implemented?

**Comment by ened** [comment]
> @ened why did you close this? Was this implemented? 

See peters reply 2years ago:

> This is not possible as it's a limitation of workmanager, only int, bool, double and String's are supported.


Therefore closed as "not supported".

**Comment by neeluagrawal04** [comment]
ios does not support the inputData so how to add a check of different task run in ios via work manager?
