### ISSUE TITLE
🐞Workmanager.cancelByUniqueName not working

### ISSUE THREAD

**Issue by bujanovschilarisa** [fluttercommunity/flutter_workmanager#164]
I'm using this version of workmanager: ^0.2.0.
I'm trying to use cancelByUniqueName  method from Workmanager but it's not working.
I received this error message: No implementation found for method cancelTaskByUniqueName on channel be.tramckrijte.workmanager/foreground_channel_work_manager.

Can you help me with this issue?

**Comment by ened** [comment]
Please try in latest beta `0.5.0-dev.8`.

**Comment by EA-YOUHOU** [comment]
Hi,

It didn't work for iOS on 0.5.0-dev.8 :/
