### ISSUE TITLE
Built failed likely due to AndroidX incompatibilities in a plugin

### ISSUE THREAD

**Issue by Chethansmash7** [fluttercommunity/flutter_workmanager#166]
I tried to run the example code as in https://pub.dev/packages/workmanager#-example-tab-
But I am getting this error:

![image](https://user-images.githubusercontent.com/14990970/80225785-2d6c9400-8669-11ea-9975-29f3c8e00ec4.png)

Can anyone give a link of a simpler example for the same?I really cant understand whats happening.Please help

**Comment by Dhua-v** [comment]
This same problem, comes when building the example. How come the example itself is problematic

**Comment by Dhua-v** [comment]
This problem only persisted for android studio, running in vscode, worked like a charm. I am getting that scheduled execution even when the app is terminated.

**Comment by Chethansmash7** [comment]
> vscode

Thanks for the response.But why is that in android studio,it is not running??Is there a possible solution in it?

**Comment by Chethansmash7** [comment]
> This problem only persisted for android studio, running in vscode, worked like a charm. I am getting that scheduled execution even when the app is terminated.

I got the same error while running in vscode also.Like what is the meaning of this error:
![image](https://user-images.githubusercontent.com/14990970/80364857-3bf2bf80-88a4-11ea-91fe-c484fe6b123d.png)

**Comment by AxesandGrinds** [comment]
For me, it's working on android studio but the debug notifcation keeps saying failed...

**Comment by AshrafLP** [comment]
same problem here

**Comment by emouawad** [comment]
same here

**Comment by surveshoeb** [comment]
Any update on this issue?

**Comment by ened** [comment]
Please open a new issue if this problem still exists in recent plugin versions (or the beta `0.5.0-dev.8`)
