### ISSUE TITLE
Minimum Interval not being met

### ISSUE THREAD

**Issue by cormalenv** [fluttercommunity/flutter_workmanager#177]
Period task duration set to 10 hours, but mostly running at 5 hours with some events up to 7 maximum, never reaches or exceeds 10.

Testing on Android physical device API 28
Workmanager version  0.2.2

Example:
```
await Workmanager.initialize(callbackDispatcher);
      Workmanager.registerPeriodicTask("1", "MyTask", 
           frequency: Duration(hours: 10),
          initialDelay: Duration(hours: 1),
          existingWorkPolicy: ExistingWorkPolicy.keep, 
          constraints: Constraints(
          networkType: NetworkType.connected));
    }
```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.476], locale en-AU)
    • Flutter version 1.17.1 at D:\...\flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at d:\...\android\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:/.../Android/sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_92\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

**Comment by cormalenv** [comment]
Same issue on iOS.

**Comment by ened** [comment]
Please see the discussion on other tickets and also refer to www.dontkillmyapp.com for Android limitations.
