### ISSUE TITLE
🐞[Android, Task was cancelled in periodic run]

### ISSUE THREAD

**Issue by trueromanus** [fluttercommunity/flutter_workmanager#179]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [ ] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |    0.2.2     |

**Describe the error**

I run the code on Android (periodic), but it works for the first time only, all further runs failed with an error:

My code:
```
void backgroundTrackerInitialize() {
  Workmanager.cancelAll();
  Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
  Workmanager.registerPeriodicTask(
    "1",
    "refreshLocationAndNetworkStatus",
    frequency: Duration(minutes: 15)
  );
}

void callbackDispatcher() {
  Workmanager.executeTask((task, parameters) async {
    print('task:getposition');

    print('task:finished');

    return Future.value(true);
  });
}
```

![image](https://user-images.githubusercontent.com/9040186/84490091-5691c400-acab-11ea-86be-bf61744bb379.png)

Error output:
```
I/WM-WorkerWrapper( 7011): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper( 7011): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper( 7011): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper( 7011): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper( 7011): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
I/WM-WorkerWrapper( 7011): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
I/WM-WorkerWrapper( 7011): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/WM-WorkerWrapper( 7011): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/WM-WorkerWrapper( 7011): 	at java.lang.Thread.run(Thread.java:923)
```

In example project all work fine, but if I copy/paste code from example project to my project I get same error.
Any ideas?

**Output of `flutter doctor -v`**

```

[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.3 at C:\ide\flutter
    • Framework revision b041144f83 (7 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\truer\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\truer\AppData\Local\Android\Sdk
    • Java binary at: C:\ide\androidstudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\ide\androidstudio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • sdk gphone x86 arm • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by gebsl** [comment]
Why do you return `Future.value(true)`? You already have the `async` keyword in your `executeTask` handler, so just returning `true` should be enough. Alternatively, just remove the `async` keyword. This could do the trick.

**Comment by trueromanus** [comment]
@gebsl I checked with **async** and without. The error is still there. I think something is wrong with the configuration of the Android project, but I don’t understand where exactly.

**Comment by gebsl** [comment]
Strange. 

Have you checked this [guide](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)?
`callbackDispatcher` is a top level function (i had problems while `callbackDispatcher` was a public static function)?
Does it print your debug messages in console?

**Comment by gebsl** [comment]
What I also noticed: The name of your periodic task is `refreshLocationAndNetworkStatus` but the screenshot you added states task name is `simplePeriodicTask`. Is there additional code registering this task?

**Comment by trueromanus** [comment]
> Have you checked this [guide](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)?
> Is `callbackDispatcher` a real top level function (i had problems while `callbackDispatcher` was a public static function within a class)?
> Does it print your debug messages in console?

I checked the guide and my project has tag **metadata** from it.
In console only error **Task was cancelled**.

> What I also noticed: The name of your periodic task is `refreshLocationAndNetworkStatus` but the screenshot you added states task name is `simplePeriodicTask`. Is there additional code registering this task?

I copy this [file](https://github.com/vrtdev/flutter_workmanager/blob/master/example/lib/main.dart) to my project for tests. The screenshot was taken already when I check the code from the example, but in my code  error was same but with name refreshLocationAndNetworkStatus.

**Comment by zhangxinagjunHJH** [comment]
I meet same error..

**Comment by yakupbaser** [comment]
i meet same error too. ):

**Comment by gebsl** [comment]
Have you checked the status of your workmanager tasks using `adb shell dumpsys jobscheduler`

I've found that it provides some useful information from time to time ;)

**Comment by xenophilya** [comment]
I am having similar issue too

**Comment by gebsl** [comment]
Have you checked the output of `adb shell dumpsys jobscheduler`?

**Comment by xenophilya** [comment]
> Have you checked the output of `adb shell dumpsys jobscheduler`?

yeah,

**Comment by trueromanus** [comment]
Hi Guys, what about the status of this issue?
What is the chance this issue will be fixed?

**Comment by gebsl** [comment]
I don't think this is a problem of flutter_workmanager. Example app works fine. I have never experienced this issue.

**Comment by MarcinKrz1** [comment]
Does anyone know how to resolve this problem? I notice that on one device app work properly but on another, I get this error :/

**Comment by MwangiMartin** [comment]
Getting same error. any fix??

**Comment by willroyMyles** [comment]
I had this problem on my sansung A21s, turns out when i have on power mode (optimize battery usage) it limits background activity. turning it off allowed my app to continue wokring in the background. 

is there any way around this?

**Comment by PaoloP98** [comment]
> I had this problem on my sansung A21s, turns out when i have on power mode (optimize battery usage) it limits background activity. turning it off allowed my app to continue wokring in the background.
> 
> is there any way around this?

Maybe you can try to request the permission to ignore battery optimization. 
I use permission_handler: `Permission.ignoreBatteryOptimizations.request()`

**Comment by ened** [comment]
Please open a new issue if you encounter the problem still.

**Comment by codemicah** [comment]
Please what is the solution to this?

**Comment by janhelwich** [comment]
For those having this error: for me it was the return type of the code in executeTask. If use async I need to return only true (not encapsulated in a Future).
