### ISSUE TITLE
Flutter workmanager not working after reboot

### ISSUE THREAD

**Issue by harpreetsingh3127** [fluttercommunity/flutter_workmanager#180]
My android version is 10, it works when I open app again: it will restart the workmanager fine in background even app is terminated.

**Comment by umuieme** [comment]
any update on this? I am facing samilar issues. it works fine until reboot.

**Comment by harpreetsingh3127** [comment]
not now

**Comment by Kymer** [comment]
Please don't write _your entire issue_ in the title field. Please.

Not expected behaviour lets say, but probably related to the underlying Android API and not the plugin's implementation. Going to keep it open for further investigation

**Comment by gebsl** [comment]
Can you maybe provide the output of `adb shell dumpsys jobscheduler` *before* and *after* restarting the phone?

Reference: https://developer.android.com/topic/libraries/architecture/workmanager/how-to/debugging#use_adb_shell_dumpsys_jobscheduler

**Comment by Blue2Blue** [comment]
Got the same error on Android:

I'm starting a periodic task which works fine but only the first time I open the app or start it in debug mode on Android Studio. 

After the first time the code never goes into the callbackDispatcher function and get this error message in the code debug console which might be related to the issue as I didn't see this message before start using WorkManager:

```
W/com.blue.bv4(14832): Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000131/GoogleCertificates.apk
W/com.blue.bv4(14832): NOTE: This wastes RAM and hurts startup performance.
W/com.blue.bv4(14832): Found duplicated class when checking oat files: 'Landroidx/annotation/Keep;' in /data/app/com.blue.bv4-SDNzhedui10FjoNFwg6Wug==/base.apk and 
```

I'm not using any method to cancel background task, could it be that WorkManager sets a "flag file" each time it runs a tasks and that flag isn't cleared between executions preventing a new background task to be instantiated at app reboot ?

**Comment by rishavk1102** [comment]
Any update on this issue? I am facing the same problem

**Comment by gebsl** [comment]
https://github.com/fluttercommunity/flutter_workmanager/issues/180#issuecomment-659043088

This might help investigating the problem.

**Comment by ModernChocolate** [comment]
I'm encountering this problem too, I've checked the [don't kill my app tricks] (https://dontkillmyapp.com/) (on a Huawei p30) but task is still not scheduled after a reboot. 
Any news ?

**Comment by ModernChocolate** [comment]
Well, my mistake, I just noticed that by enabling the manual launching in the app setting, the background task is effectively starting. 
But that's a problem, I don't want my user to be lost in settings in order to enable it, can I do something to automatically start it ?

**Comment by gebsl** [comment]
Folks please! I don't want to post it over and over again. 

PLEASE put in the output of `adb shell dumpsys jobscheduler`. I think otherwise it's just black magic reasoning about what prevents your task from being started after reboot.

**Comment by ModernChocolate** [comment]
Hey, I'm sorry I really wanted to do it but I have forgotten. 
My app name is `fr.ynotes `
Here is 3 files : one before rebooting, one after rebooting, and one after rebooting with manual launching. 
[after_reboot_manual_launching.txt](https://github.com/fluttercommunity/flutter_workmanager/files/5735607/after_reboot_manual_launching.txt)
[after_reboot.txt](https://github.com/fluttercommunity/flutter_workmanager/files/5735608/after_reboot.txt)
[before_reboot.txt](https://github.com/fluttercommunity/flutter_workmanager/files/5735609/before_reboot.txt)

**Comment by gebsl** [comment]
@ModernChocolate which package identifier do you use?
e.g. `com.example.test`

**Comment by ModernChocolate** [comment]
`fr.ynotes`

**Comment by gebsl** [comment]
Did a quick look and seems at least one other person also has the same issue -> https://github.com/googlecodelabs/android-workmanager/issues/157#issuecomment-543226751 \
Could be Battery Optimization leading to this behaviour on particular devices (like Huawei) -> https://github.com/googlecodelabs/android-workmanager/issues/22#issuecomment-643811014

Can you maybe test the behaviour on another device or on a emulator?

**Comment by ModernChocolate** [comment]
Yes I've finally spent my afternoon to develop a small platform interface in order to disable the Huawei automatical "App launch" 
So here is the workaround for Huawei (and other devices) users if it can help :

- Add a platform channel using [this tutorial](https://flutter.dev/docs/development/platform-integration/platform-channelsl)
- Redirect the user to the concerned settings. I've made this code, its messy and it surely can be enhanced :
```kotlin
fun openAutostartSettings() {
        try {
            val intent = Intent()
            val manufacturer = Build.MANUFACTURER
            Log.d("Manufacturer", manufacturer)
            if ("xiaomi".equals(manufacturer, ignoreCase = true)) {
                intent.component = ComponentName(
                    "com.miui.securitycenter",
                    "com.miui.permcenter.autostart.AutoStartManagementActivity"
                )
            } else if ("oppo".equals(manufacturer, ignoreCase = true)) {
                intent.component = ComponentName(
                    "com.coloros.safecenter",
                    "com.coloros.safecenter.permission.startup.StartupAppListActivity"
                ) //need "oppo.permission.OPPO_COMPONENT_SAFE" in the manifest
            } else if ("vivo".equals(manufacturer, ignoreCase = true)) {
                intent.component = ComponentName(
                    "com.vivo.permissionmanager",
                    "com.vivo.permissionmanager.activity.BgStartUpManagerActivity"
                )
            } else if ("Letv".equals(manufacturer, ignoreCase = true)) {
                intent.component = ComponentName(
                    "com.letv.android.letvsafe",
                    "com.letv.android.letvsafe.AutobootManageActivity"
                )
            } else if ("Honor".equals(manufacturer, ignoreCase = true)) {
                intent.component = ComponentName(
                    "com.huawei.systemmanager",
                    "com.huawei.systemmanager.optimize.process.ProtectActivity"
                )
            } 
            else if ("Huawei".equals(manufacturer, ignoreCase = true)) {
                //open huawei settings
                intent.component = ComponentName(
                    "com.huawei.systemmanager",
                    "com.huawei.systemmanager.startupmgr.ui.StartupNormalAppListActivity"
                )
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            } 
            else {
                //Timber.d("Auto-start permission not necessary")
            }
            val list = ContextWrapper(applicationContext).packageManager
                .queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY)
            if (list.size > 0) {
                ContextWrapper(applicationContext).startActivity(intent)
            }
        } catch (e: Exception) {
            Log.d("exception",e.toString())
        }
    }
```

**Comment by ModernChocolate** [comment]
I'm still investigating because some apps are automatically added to the Huawei's whitelist (as Snapchat or CovidApp) and I'd like to understand why. If anyone has any leads ...

**Comment by futurelucas4502** [comment]
I seem to have the same problem but on a Samsung A70 is there anything I should check or try in order to get the correct behaviour

Note: I'm using the git branch fix as my app also needs to run on iOS

**Comment by flutteresbolivia** [comment]
Does the library work when the application is closed?
is the periodic task still running?

**Comment by sanjib292-cmd** [comment]
> Does the library work when the application is closed?
> is the periodic task still running?

yes

**Comment by ened** [comment]
Please check the links above and also www.dontkillmyapp.com for BG limitations on Android.
