### ISSUE TITLE
[iOS] background fetch not running periodically 

### ISSUE THREAD

**Issue by MuhammedRefaat** [fluttercommunity/flutter_workmanager#196]
I've implemented all the process as mentioned in the documentation, then after running the app, I've tried to 'simulate background fetch' from XCode and it did work perfectly, but on the other hand, it never runs in the background, and to make sure about that, I did clone the example app and run it and got the same exact behavior, when trying to manually simulate background fetch it works perfectly but never runs in the background (every 15 min. as it suppose to do)

**Comment by gebsl** [comment]
I experienced this too. iOS is not very transparent about the schedule when an app is about to be run in the background. At least for me, it took more than 24 hours for the first background fetch to run (after app install). After that there were about 4 runs (all scheduled about 15 minutes apart), after which it just stopped running my app in the background for several hours.

So I think it's just Apple's way of handling background fetch. In my opinion, it's a pain for app developers.

**Comment by MuhammedRefaat** [comment]
> I experienced this too. iOS is not very transparent about the schedule when an app is about to be run in the background. At least for me, it took more than 24 hours for the first background fetch to run (after app install). After that there were about 4 runs (all scheduled about 15 minutes apart), after which it just stopped running my app in the background for several hours.
> 
> So I think it's just Apple's way of handling background fetch. In my opinion, it's a pain for app developers.

That's a big issue if so, we need a confirmation though as it's a big inconsistency matter.

**Comment by JonasJW** [comment]
> At least for me, it took more than 24 hours for the first background fetch to run (after app install). After that there were about 4 runs (all scheduled about 15 minutes apart), after which it just stopped running my app in the background for several hours.

I have the exact same behavior, did you find anything that helped?

**Comment by gebsl** [comment]
Not yet, unfortunately. I've never developed for iOS before, so I'm also stumbling from issue to issue it seems.
Also, my app currently stops working on my iOS device after 4-5 days after build and install. Don't know if this is due to a bug in my code or if it's intentional behaviour. It quits immediately, if I start the app. No message/error whatsoever. 
So far, I don't have any clue why this happens all the time.

I will let you know if I have any new information on these issues.

**Comment by vemarav** [comment]
@gebsl This works as expected, worth a try https://github.com/transistorsoft/flutter_background_fetch

**Comment by gebsl** [comment]
Thanks for sharing, will give it try if iOS's implementation remains unstable.

**Comment by JonasJW** [comment]
> @gebsl This works as expected, worth a try https://github.com/transistorsoft/flutter_background_fetch

I might be missing something here but it seems to me that it is using the same iOS API (performFetchWithCompletionHandler) so I don't see why it should work with this plugin because the issue is with iOS implementation and not this plugin.

**Comment by MiguelSOliveira** [comment]
@gebsl did you figure out the cause for startup crashes? Having the same problem now.

**Comment by gebsl** [comment]
Hi @MiguelSOliveira,
unfortunately not. Haven't been working on this specific project for a long time and will not continue in the near future, therefore I think I can't help you, sorry.

**Comment by ened** [comment]
Hi everyone, have you seen the IOS Setup documentation here, esp. the note on reliability: https://github.com/fluttercommunity/flutter_workmanager/blob/master/IOS_SETUP.md#testing-background-fetch

Also, you may need to turn the "background app refresh" setting on in your Settings app on the iOS device.
