### ISSUE TITLE
Workmanager does not execute future in callback

### ISSUE THREAD

**Issue by wolfc01** [fluttercommunity/flutter_workmanager#197]
In the example I made the change:

```
      case simplePeriodicTask:
        print("$simplePeriodicTask was executed");
        Future.delayed(const Duration(milliseconds: 5500), () {
          print('Hello, world');
        });
        break;
```
But the "hello world" was not printed. Is this intended? If so, please explain the mechanism behind prohibiting the completion of the future.

Br
Carl.

**Comment by gebsl** [comment]
Could it be same problem/solution as here -> https://github.com/fluttercommunity/flutter_workmanager/issues/171#issuecomment-640855666?

You are not awaiting the delayed future. This might lead to the task already being finished before the future is resolved.

**Comment by Tienisto** [comment]
await / async is working on my side. Probably `await` is missing in this code.

**Comment by SSVernekar** [comment]
@gebsl  please help me with it

**Comment by ened** [comment]
Refer to the example for a dispatcher with await/async usage. https://github.com/fluttercommunity/flutter_workmanager/blob/main/example/lib/main.dart#L19
