### ISSUE TITLE
Possible to access static references if app running?

### ISSUE THREAD

**Issue by BestAndroidTeam** [fluttercommunity/flutter_workmanager#198]
I created a work that fetch data from internet, then updates a moor database.
Meanwhile, my app listen to this database's changes (with streams) to update the ui.
However I cannot access the Database client instance, which is a Singleton, from the WorkManager (it is null), so I have to create a new client instance.
So when I update the Database via this new client instance, my UI is not notified of the changes, as it listens to an other instance.

Ex:

```dart
class Database {
  static Database _instance;
  static Database get instance => _instance ??= Database();

  Database() {
    print('Database instance is null, creating new');
  }
}

class App {
  static void start() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Initialize workmanager
    Workmanager.initialize(
      WorkManager.callbackDispatcher,
      isInDebugMode: AppConstants.MODE_DEBUG,
    );
    
    Database.instance; // prints 'Database instance is null, creating new'
    Database.instance; // prints Nothing as the Database client has already been created

    await Workmanager.registerOneOffTask(
      'myUniqueName',
      'myTaskName',
      inputData: {},
    );

    // Start app
    final app = App();
    runApp(Container());
  }
}

void callbackDispatcher() {
  Workmanager.executeTask((taskName, inputData) async {
    Database.instance; // prints 'Database instance is null, creating new'
  }
}
```

With Android's WorkManager, I could access static instances and it worked fine. Would it be possible to do the same with flutter_workmanager?

**Comment by gebsl** [comment]
Possibly the same as #184 ?

The callback that's triggered by Android's WorkManager mechanism is running in its own flutter isolate. Therefore, variables from another isolate are not accessible.

This comment might help you -> https://github.com/fluttercommunity/flutter_workmanager/issues/151#issuecomment-612777877
It states how to share data among isolates.

**Comment by BestAndroidTeam** [comment]
Thanks! I saw https://github.com/fluttercommunity/flutter_workmanager/issues/151#issuecomment-612777877
I was wondering if there was an easier way, but I guess not haha

**Comment by limcheekin** [comment]
Hi @BestAndroidTeam,

I have the exactly the same issue and did gone thru the #151, but still don't have any clue on how to make it works on the example above as Isolates is new to me.

Appreciate if you share the code here for the solution.

Thanks in advanced.

**Comment by 2math** [comment]
In your main.dart class
```
main(){
 _listenForUpdatesFromWorkManager()
 runApp(...)
}

void _listenForUpdatesFromWorkManager() {
    var port = ReceivePort();
    IsolateNameServer.registerPortWithName(port.sendPort, "my_port_name_must_be_constant");
    port.listen((dynamic data) async {      
      Log.w('got $data on UI');
    });
  }
```

At the end of your callbackBackgroundDispatcher or maybe somewhere in btw:
```
void callbackBackgroundDispatcher() {
  Workmanager.executeTask((task, inputData) async {
.....
    final sendPort = IsolateNameServer.lookupPortByName("my_port_name_must_be_constant");
    if (sendPort != null) {
      Log.d("send to port $isTaskDoneSuccessful", tag);
      // The port might be null if the main isolate is not running.
      sendPort.send(isTaskDoneSuccessful);
    }else{
      Log.d("no port", tag);
    }

    return Future.value(true);
  });
```

**Comment by limcheekin** [comment]
Hi @2math,

Thanks for sharing the code of sending the updated data from `callbackBackgroundDispatcher` to the `main.dart`.

However, it still doesn't solved the issue I reported at https://github.com/fluttercommunity/get_it/issues/103, which I believe it is a common issue.

Please click the link above for more information and github repo.

**Comment by ened** [comment]
The issue was answered correctly - the dispatcher registered in `initialize` runs in its own Isolate and therefore has no access to anything in the main isolate.
In order for get_it to work in that isolate, you need to register all the services again once it's called. 

You may be able to open a communication channel to the main App and get work processed there or have access to an already open database object. The `moor_isolate` package may help moor users with that.
