### ISSUE TITLE
🐞 I try To send Data in Background but dosn't working

### ISSUE THREAD

**Issue by HamzaAyada** [fluttercommunity/flutter_workmanager#199]
I use a pedometer to count daily step in my app, it's work fine; then i try to send data every x hours, so i try to use workmanager plugin; first time i thing it's working fine, but i check my database to see if i have the new value but i don't have any data send when i close the app and i have notification with success of task without new data.

that's hy have in the console:

`E/flutter (30778): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:workmanager/src/workmanager.dart': Failed assertion: line 97 pos 12: 'callback != null': The callbackDispatcher needs to be either a static function or a top level function to be accessible as a Flutter entry point.
E/flutter (30778): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (30778): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (30778): #2      Workmanager.initialize (package:workmanager/src/workmanager.dart:97:12)
E/flutter (30778): #3      _HomePageState.initState (package:walk_win/ui/home.dart:88:17)
E/flutter (30778): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
E/flutter (30778): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30778): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30778): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30778): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30778): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30778): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30778): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30778): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30778): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30778): #24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (30778): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30778): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30778): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter (30778): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30778): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30778): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30778): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30778): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30778): #38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (30778): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30778): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30778): #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter (30778): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30778): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30778): #44     Element.updat`

Flutter Doctor -verbose 👍 

`[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [version 10.0.19041.388], locale fr-FR)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\HAMZA TEK'NOLOGY IT\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\HAMZA TEK'NOLOGY IT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[√] Connected device (1 available)
    • JAT L29 (mobile) • 9EHNW20303000604 • android-arm • Android 9 (API 28)

• No issues found!
`

[code ww.txt](https://github.com/fluttercommunity/flutter_workmanager/files/5087050/code.ww.txt)

**Comment by gebsl** [comment]
Have you tried building and running the example app? (https://github.com/fluttercommunity/flutter_workmanager/tree/master/example)

**Comment by HamzaAyada** [comment]
I don't need to run this exemple because it's not the same to my project.
@gebsl

**Comment by gebsl** [comment]
Yeah, but it's good to verify correct execution of the example app, before posting github issues, as sometimes things clarify while debugging the example app.

In the code provided, I can only see one thing that could be a problem.

```dart
 @override
  void initState() {
    const  myTask= "Walk & Win";
    Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
    Workmanager.registerPeriodicTask("1", "Walk & Win Runner", frequency: Duration(minutes: 15));
    Workmanager.registerPeriodicTask("2", myTask, frequency: Duration(minutes: 15));
    super.initState();
    _loadObjectifSaved();
    _loadUserMobile();
    startListening();
  }
```

You try to initialize WorkManager and immediatley after you try to execute a task.
However, `initialize` returns a Future, therefore you should wait for it to be resolved, before registering any tasks.

Try this:

```dart

  @override
  void initState() {
    super.initState();
    const myTask = "Walk & Win";

    initStateAsync();

    _loadObjectifSaved();
    _loadUserMobile();
    startListening();
  }

  void initStateAsync() async {
    await Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
    Workmanager.registerPeriodicTask("1", "Walk & Win Runner", frequency: Duration(minutes: 15));
    Workmanager.registerPeriodicTask("2", myTask, frequency: Duration(minutes: 15));
  }
```

Please note the keyword `await`, which makes your the runtime wait for `initialize` to complete, before registering your tasks.

**Comment by HamzaAyada** [comment]
I need to use this plugin only in main dart???

**Comment by gebsl** [comment]
Sorry, but I don't know what you mean. Have you tried implementing it the way I suggested?

**Comment by roflan94** [comment]
> I need to use this plugin only in main dart???

sahaa bro , belehi malkitlhesh hal lahkeya ?

**Comment by SebastienSCochet** [comment]
The error is clear here : The callbackDispatcher needs to be either a static function or a top level function to be accessible as a Flutter entry point.

**Comment by ened** [comment]
As mentioned, please try running the example project and verify the callbackDispatcher implementation. Thank you.
