### ISSUE TITLE
Get status of the scheduled job whether it is currently active 

### ISSUE THREAD

**Issue by bnayagrawal** [fluttercommunity/flutter_workmanager#200]
I have a sync periodic service scheduled. And in the application, there is a button to sync manually. 

I want to block the user from manually syncing if the background sync service is currently syncing and also when the user is manually syncing I don't want the background service to sync. 

How can I setup this communication from Application to the service and vice-versa?

**Comment by ened** [comment]
@bnayagrawal Thank you for documenting your progress, I'm sure it would help others. Do you mind starting a Wiki page on this project? Doze, power saving modes etc can always cause issues for background features activated using workmanager.

**Comment by nukeolay** [comment]
> @gebsl after making those changes it still was not syncing. After installing the app and launching it for the first time it syncs and then after a few minutes (before 20 minutes gap) if I launch the app again it doesn't sync which is fine (it is not supposed to sync as the interval is 20 minutes) but after more than 30 minutes has elapsed and I open the app then it starts syncing. That means it only syncs when the app is running. But it also synced once in the background but then never synced. 
> 
> It is mostly because the OS is trying to save the battery. I researched a bit and learned about the Doze mode. So what I did was, I turned off battery optimization for my app and viola the sync happened twice with the given interval.
> 
> Now I have set the interval to two hours. Let's see how it works.
> 
> Update: The sync is working perfectly. 

Hello! Can you share example of code, with turned off battery optimization and which "works perfectly" now.
Im experiencing same problem, but cant get my app sync in the background for a long period.

**Comment by bnayagrawal** [comment]
Just ask the user to disable battery optimizations by taking the user to the battery optimizations page. Once battery optimizations is turned off, the sync or whatever task will be executed in given intervals. Note that battery optimization API is available on Android 6+. For android versions below 6, the sync works in the given interval.

https://developer.android.com/training/monitoring-device-state/doze-standby
