### ISSUE TITLE
Calling native Android method channels from WorkManager, unfortunately it does now trigger the native Android method

### ISSUE THREAD

**Issue by petodavid** [fluttercommunity/flutter_workmanager#202]
**• Calling native Android method channels from WorkManager, unfortunately it does now trigger the native method from the Work Manager**

**Here is the Flutter Dart side code example i use:**

```
void callbackDispatcher() {
 Workmanager.executeTask((task, inputData) async {
   switch (task) {
     case activateProfile:
       try {
        await const MethodChannel('io.test.mdm/native_channel').invokeMethod('request_device_admin');
       } catch (e) {}
       break;
     case disableRestrictions:
       break;
   }
   return Future.value(true);
 });
}
```
**And here is my Android Side, i would like to trigger the REQUEST_DEVICE_ADMIN. This code example comes from the FlutterActivity Class.**

```
public class MainActivity extends FlutterActivity {
protected void onCreate(@Nullable Bundle savedInstanceState) {}
public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);

        new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
                .setMethodCallHandler((call, result) -> {
                            switch (call.method) {
                                case IS_DEVICE_OWNER:
                                    result.success(mIsDeviceOwner);
                                    break;
                                case IS_DEVICE_ADMIN:
                                    result.success(mIsAdminActive);
                                    break;

                                case REQUEST_DEVICE_ADMIN:
                                    Intent intent = new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN);
                                    intent.putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN, mDeviceAdminSample);
                                    intent.putExtra(DevicePolicyManager.EXTRA_ADD_EXPLANATION, getString(R.string.add_admin_extra_app_text));
                                    startActivityForResult(intent, REQUEST_CODE_ENABLE_ADMIN);
                                    result.success(true);
                                    break;

                                default:
                                    result.notImplemented();
                                    break;
                            }

                        }
                );
    }
}
```

**Comment by petodavid** [comment]
???

**Comment by wonpyohong** [comment]
same issue. 

Workmanager package make new flutter engine for new task. (In BackgroundWorker.kt)
This new flutter engine don't know your method channel because your channel is not registered

i think that you can fix with adding below code to your new flutterEngine object on BackgroundWorker.kt
```
flutterEngine.getPlugins().add(yourPluginObject)
```

1. you should modify code in workmanager package.
2. you should make Class extending FlutterPlugin, MethodCallHandler. 

I wonder that there is another simpler solution

**Comment by ened** [comment]
The simplest solution here may be to write a small helper plugin and depend on it from your App. 

In the native side, you could have a singleton object (defined in the plugin) which you can access from both MainActivity and the plugin itself. IF you need it. :)

**Comment by petodavid** [comment]
> The simplest solution here may be to write a small helper plugin and depend on it from your App.
> 
> In the native side, you could have a singleton object (defined in the plugin) which you can access from both MainActivity and the plugin itself. IF you need it. :)

Code example?
