### ISSUE TITLE
Background service every seconds

### ISSUE THREAD

**Issue by dimple3695** [fluttercommunity/flutter_workmanager#203]
Is this possible background service triggered every seconds?

If it is possible Can you please tell me functions/demo link?

**Comment by gebsl** [comment]
Please don't use github issues to ask question about best practices. Especially when labelling them as bug. This is confusing and not common practice.

I think you are looking for Android's services. Here is a comprehensive article from the official Flutter team -> https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

On iOS, I doubt something similar is possible.

**Comment by ened** [comment]
@dimple3695 this is probably out of scope for this library. As @gebsl has mentioned, you may need a different package. I'd recommend looking at [`flutter_background`](https://pub.dev/packages/flutter_background).

On iOS, you need a different mechanism to keep the App running, for example a active bluetooth connection or location tracking. Thus closing this ticket.
