### ISSUE TITLE
Not able to add frequency lower than 15 min in registerPeriodicTask

### ISSUE THREAD

**Issue by chirag-chopra** [fluttercommunity/flutter_workmanager#204]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |  ^0.2.3    |
| Xcode version        |  -  |
| Swift version        |   -   |
| iOS deployment target|   -    |

I am a windows user. So, can't try on iOS. I tried only in Android SDK 29.

**ISSUE**

I am developing an app in which I want to location updates in every 2-3 min in background. For that I tried this plugin but there is a limitation that we can't reduce background task frequency to lower than 15 min.

**Output of `flutter doctor -v`**
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by gebsl** [comment]
Issue has already been answered here -> https://stackoverflow.com/a/51203829/2700754

flutter_workmanager uses Android's WorkManager as an underlying implementation and therefore only supports a minimum interval of 15 minutes, when used for periodic work. You should give Android services a try. They should fit your requirements.

**Comment by ened** [comment]
Thank you @gebsl for the pointer. 15 minute is a WorkManager limitation.

**Comment by alpitilanam** [comment]
Hello @chirag-chopra 
I'm doing the same functionality. I want to update location in every 2-3 minute in background, So how can you fix this solution, Can you please help me for this or give me the suggestion for update location in background functionality.
Thanks in Advance.

**Comment by gebsl** [comment]
@alpitilanam If you are purely relying on background geolocation, try this plugin: https://pub.dev/packages/flutter_background_geolocation
Transistorsoft is quite experienced in background geolocation, their plugins work quite well.

flutter_workmanager is most probably not what you're looking for.

**Comment by alpitilanam** [comment]
> @alpitilanam If you are purely relying on background geolocation, try this plugin: https://pub.dev/packages/flutter_background_geolocation Transistorsoft is quite experienced in background geolocation, their plugins work quite well.
> 
> flutter_workmanager is most probably not what you're looking for.

Thank you @gebsl for the fast reply.
I have already check this plugin and this is a paid plugin, So please can you suggest other thing to update the location in background.

**Comment by gebsl** [comment]
@alpitilanam Maybe check out this one: https://pub.dev/packages/background_location
However, don't know how well it works, have never tried in on my own.

On pub.dev, there seems to be plenty of plugins available: https://pub.dev/packages?q=background+location

**Comment by alpitilanam** [comment]
> @alpitilanam Maybe check out this one: https://pub.dev/packages/background_location However, don't know how well it works, have never tried in on my own.
> 
> On pub.dev, there seems to be plenty of plugins available: https://pub.dev/packages?q=background+location

Thank you for the [suggestion](https://pub.dev/packages/background_location) i have also find one more [plugin](https://pub.dev/packages/flutter_background_service).

**Comment by gebsl** [comment]
@alpitilanam be careful. The implementation of the plugin you linked relies on iOS' `background_fetch` API. With this you can not achieve location updates every 2-3 minutes. `background_fetch` is quite restricted on iOS. I think this plugin will not fit your needs.

Reference: [Apple](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app)

**Comment by phantomate** [comment]
I found a hacky way to get around the 15 minutes.
You can register an one off task with an internal delay of 1 or 2 minutes and use the append work policy.
So after you updated your location or did a fetch you just register the same one off task again and its gonna repeat itself.

**Comment by hey-om7** [comment]
> 

Hey @phantomate I'm stuck and not able to acheieve this since long time.. pls elaborate how did you achieve that? Tnx a lot!!

**Comment by phantomate** [comment]
@hey-om7 First you need to initialize the package, like in the documentation. After that you can register an one off task like that:

`Workmanager().registerOneOffTask(
  "1",
  "simpleTask",
  initialDelay: Duration(minutes: 2),
  existingWorkPolicy: ExistingWorkPolicy.append
);`

When handling the task (I don't know what you want to achieve but maybe a fetch) you register the same one off task again and then its gonna repeat itself.

**Comment by abdulsamadshah** [comment]
Workmanager().registerPeriodicTask("get_location", "get_location",
      frequency: Duration(seconds: 15),existingWorkPolicy: ExistingWorkPolicy.append);

**Comment by abdulsamadshah** [comment]
Workmanager().registerPeriodicTask("get_location", "get_location",
      frequency: Duration(seconds: 15),existingWorkPolicy: ExistingWorkPolicy.append);
i have registerPeriodicTask in 15 seconds but it is not working because WorkManager  has set 15 minutes default
