### ISSUE TITLE
Periodically in iOS

### ISSUE THREAD

**Issue by rrifafauzikomara** [fluttercommunity/flutter_workmanager#206]
So, for periodically on iOS is not working?

**Comment by gebsl** [comment]
Depends on what you want to do. If it's small batches of work that can be deferred and is not time critical, this plugin might help you. However, for time critical work or bigger workloads you won't be happy with this implementation, as iOS is very strict when it comes to resources while the app is not running in foreground.

**Comment by rrifafauzikomara** [comment]
Hi @gebsl 

I see on the example can run the background service periodically with the title is "(Android only)", but when I run on the Android device the button can clicked but when I run on the simulator the button can't clicked. This is the example of the function.

```
PlatformEnabledButton(
                  platform: _Platform.android,
                  child: Text("Register 1 hour Periodic Task"),
                  onPressed: () {
                    Workmanager.registerPeriodicTask(
                      "5",
                      simplePeriodic1HourTask,
                      frequency: Duration(hours: 1),
                    );
                  }),
```

So, for the above function, it's only can run on the Android device? And how to run the background service periodically on iOS? Can you give me the function of this plugin to run the background service periodically and support on Android and iOS?

**Comment by gebsl** [comment]
Already answered in #207. Please don't open multiple issues, this is confusing.

I'm not an iOS developer so I don't know about iOS APIs

**Comment by rrifafauzikomara** [comment]
@gebsl Sorry for created multiple issues.
