### ISSUE TITLE
MissingPluginException Exception in iOS - No implementation found for method registerPeriodicTask on channel be.tramckrijte.workmanager/foreground_channel_work_manager

### ISSUE THREAD

**Issue by SijuKJ** [fluttercommunity/flutter_workmanager#209]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     0.2.0          |
| Xcode version        |      11.3.1         |
| Swift version        |       5        |
| iOS deployment target|    12.2 or 13.0            |

**Describe the error**

I am trying to use workmanager: ^0.2.0 plugin for the background process inside the flutter project. While running the application in iOS, it throws an error as below, But in Android plugin is working seamlessly

MissingPluginException(No implementation found for method registerPeriodicTask on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Workmanager.registerPeriodicTask (package:workmanager/src/workmanager.dart:158:32)
#2      main (package:worksample/main.dart:34:15)

I manually registered the Workmanager plugin inside the AppDelegate.swift code. still, it doesn’t autogenerating plugin registration code inside GeneratedPluginRegistrant.m class for this plugin. 

My code snippet 

`import UIKit`
`import Flutter`
`import workmanager`

`@UIApplicationMain`
`@objc class AppDelegate: FlutterAppDelegate {`
  `override func application(`
    `_ application: UIApplication,`
    `didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?`
 `) -> Bool {`
    `GeneratedPluginRegistrant.register(with: self)`
    `UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))`
    `UNUserNotificationCenter.current().delegate = self`
    `WorkmanagerPlugin.setPluginRegistrantCallback { registry in
        AppDelegate.registerPlugins(with: registry)
    }`
    `return super.application(application, didFinishLaunchingWithOptions: launchOptions)`
     `static func registerPlugins(with registry: FlutterPluginRegistry) {
               GeneratedPluginRegistrant.register(with: registry)
          }`
`override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification,` `withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {`
         `completionHandler(.alert)` 
     `}`
    
`}`

How can I resolve this issue?

**Comment by gebsl** [comment]
There is no periodic task on iOS (read https://github.com/fluttercommunity/flutter_workmanager#customisation-android-only)

Consider calling `registerPeriodicTask` only if you are on Android, like this:

```dart
if (Platform.isAndroid) {
  Workmanager.registerPeriodicTask(<WorkManagerOptions>);
}
```

**Comment by SijuKJ** [comment]
Thank you so much for your quick response, but the error is coming even for Method initialize,
 
MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Workmanager.initialize


Dart code

void main() {
  WidgetsFlutterBinding.ensureInitialized();
 
  Workmanager.initialize(
      callbackDispatcher, 
      isInDebugMode:
          true 
      );
  Workmanager.registerPeriodicTask(
    "1",
    "iAirport",
    frequency: Duration(minutes: 15),
  );

  runApp(new AtmosphereMessage());
}

> There is no periodic task on iOS (read https://github.com/fluttercommunity/flutter_workmanager#customisation-android-only)
> 
> Consider calling `registerPeriodicTask` only if you are on Android, like this:
> 
> ```dart
> if (Platform.isAndroid) {
>   Workmanager.registerPeriodicTask(<WorkManagerOptions>);
> }
> ```

**Comment by gebsl** [comment]
Already had a look at this issue? -> https://github.com/vrtdev/flutter_workmanager/issues/189#issuecomment-663868680

Which version of Flutter do you use? If you are on 1.20, also [this thread about plugin problems on Flutter 1.20](https://github.com/fluttercommunity/flutter_workmanager/issues/188) could be helpful.
