### ISSUE TITLE
How to setup a background timer / countdown .

### ISSUE THREAD

**Issue by zommerberg** [fluttercommunity/flutter_workmanager#210]
Hello, I am trying to setup a timer / countdown that continues to works in the background when the phone is locked or the app is in the background.
Is there an example that I could use that does that?
What is the strategy behind doing that?

**Comment by gebsl** [comment]
I think the following issue will answer your questions -> https://github.com/fluttercommunity/flutter_workmanager/issues/173

**Comment by zommerberg** [comment]
I don't understand the explanation in #173 , in my case lets say I have a 50 seconds countdown. 
How would I configure it so it is continues running after I lock the phone?
So after 40 seconds if I open the app it would show the remaining 10 seconds.

**Comment by gebsl** [comment]
What you want to achieve is not possible with Workmanager. Workmanager is not designed to run background services. It's designed to run one time (or recurring) tasks. Use Android services instead. My knowledge on iOS is too weak to suggest any solution how to implement this on iOS.

Citing [Android's guide for Workmanager](https://developer.android.com/topic/libraries/architecture/workmanager):

> WorkManager is intended for work that is deferrable—that is, not required to run immediately—and required to run reliably even if the app exits or the device restarts. For example:
> * Sending logs or analytics to backend services
> * Periodically syncing application data with a server

> WorkManager is not intended for in-process background work that can safely be terminated if the app process goes away or for work that requires immediate execution. Please review the background processing guide to see which solution meets your needs.

**Comment by zommerberg** [comment]
I understand, thank you.
Looks like it is time to learn Java

**Comment by gebsl** [comment]
Maybe this post can help you implementing the service: https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

**Comment by zommerberg** [comment]
I also found a super good article that implements exactly what I wanted 
https://dev.to/protium/flutter-background-services-19a4
