### ISSUE TITLE
Tasks with initialDelay do not trigger.

### ISSUE THREAD

**Issue by zommerberg** [fluttercommunity/flutter_workmanager#212]
Hello, in your provided example a task with initialDelay will not trigger 

To reproduce the bug where it never triggers:
1) Open the example 
2) Click "Start the Flutter background service"
3) Click "Register Delayed OneOff task" , it will not trigger again .
(Currently the only way I could trigger it again is by triggering a normal OneOff Task ,after that the delayed task was automatically executed)

Expected behavior is that it should trigger automatically after X time after the task was initialized.

**Comment by zommerberg** [comment]
It actually runs but about a minute later (my delay was set to 2 seconds)

**Comment by gebsl** [comment]
Android's WorkManager implementation will NEVER guarantee that a task will run at a specific date and time. It's just not designed for this purpose. It guarantees that a task WILL run, but it does not guarantee when.

Have a look at Android's AlarmManager, if you want to run tasks at specific dates and times.

**Comment by zommerberg** [comment]
I understand what you mean, thank you. 
I managed to implement it via alarm manager
