### ISSUE TITLE
Tried running Workmanager with Sms plugin. Got the following error.

### ISSUE THREAD

**Issue by apurvabanka** [fluttercommunity/flutter_workmanager#213]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |               |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel plugins.babariviere.com/recvSMS:
PlatformException(error, Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference, null)

When the exception was thrown, this was the stack: 
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:151:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:542:29)

Optionally provide the least amount of code that shows this behavior. Ideally in the `sample` app.

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) {
    print("Native called background task"); //simpleTask will be emitted here.
    SmsReceiver receiver = new SmsReceiver();
    receiver.onSmsReceived.listen((SmsMessage msg) {
      //Do something
    });
    return Future.value(true);
  });
}
void main(){
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.initialize(
      callbackDispatcher, // The top level function, aka callbackDispatcher
      isInDebugMode: true,
      // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );
  Workmanager.registerOneOffTask("1", "simpleTask",backoffPolicy: BackoffPolicy.exponential, backoffPolicyDelay: Duration(seconds: 10));
  runApp(MyApp());
}

The dependencies used are-
sms: ^0.2.4
workmanager: ^0.2.0

I am new to Flutter. Please help.

**Output of `flutter doctor -v`**

**Comment by dinahapuque** [comment]
I'm getting the same error. 
It seems its a problem with sms package that doesn't allow being used in a top level method on flutter.
So its a deadlock ):
I don't know what to do.

**Comment by ened** [comment]
Please try to run 

```
  WidgetsFlutterBinding.ensureInitialized();
```

In the first line of the callback handler, this should resolve problems when using platform plugins.
