### ISSUE TITLE
D8: Program type already present: com.google.common.util.concurrent.ListenableFuture

### ISSUE THREAD

**Issue by 2math** [fluttercommunity/flutter_workmanager#215]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**
  workmanager: ^0.2.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0

**Describe the error**

I have a Firebase project and when I add the WorkManager package can not build the app and this error appears:
```
D8: Program type already present: com.google.common.util.concurrent.ListenableFuture

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Program type already present: com.google.common.util.concurrent.ListenableFuture

```

I have tried so many things but nothing works. It looks like Workmanager uses com.google.guava.listenablefuture which is different then the one in Firebase and I can not find a way to exclude it.
Adding this to my dependencies doesn't work :
```
        implementation ("androidx.work:work-runtime:2.3.4") {
            exclude group: "com.google.guava", module: "listenablefuture"
        }
```
If anyone know a workaround I'm buying the beer!

**Output of `flutter doctor -v`**
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.508], locale bg-BG)
    • Flutter version 1.20.2 at C:\code\soft\flutter_sdk\flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\x\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\code\soft\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\code\soft\studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Pixel 3a XL (mobile) • 94DAX0DRW1 • android-arm64 • Android 10 (API 29)

**Comment by paolominel** [comment]
Hi, try to add this line to your app's build.gradle (into dependecies section):
**implementation 'com.google.guava:guava:28.2-android'**
This solved for me

**Comment by 2math** [comment]
> Hi, try to add this line to your app's build.gradle (into dependecies section):
> **implementation 'com.google.guava:guava:28.2-android'**
> This solved for me

Great, thanks!
