### ISSUE TITLE
NO Such Module workmanager on IOS side

### ISSUE THREAD

**Issue by congfandi** [fluttercommunity/flutter_workmanager#217]
- [x]  I have read the README
- [x]  I have done the setup for Android
- [x]  I have done the setup for iOS

0.2.0

please help guyss...

i have been follow all way on ios side and i have been read for all documentation but still got error 

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.20.4 at /Users/congfandi/development/flutter
    • Framework revision fba99f6cf9 (7 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/congfandi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API
      30) (emulator)
```

<img width="741" alt="Screen Shot 2020-09-22 at 05 12 31" src="https://user-images.githubusercontent.com/10652810/93826808-3e5e1780-fc92-11ea-9266-ab2195756737.png">

**Comment by ened** [comment]
Have this issue as well and will check today how to resolve. May be related to the iOS module definition, introduced in #181.

**Comment by congfandi** [comment]
Thanks dude,,,i wait for this PR

**Comment by ened** [comment]
@congfandi you can add this to your pubspec.yaml file:

``` yaml
dependency_overrides:
  workmanager:
    git:
      url: https://github.com/ened/flutter_workmanager.git
      ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d # flutter 1.20 compatibility
```

**Comment by congfandi** [comment]
okai i will do that

**Comment by congfandi** [comment]
is this OK ?

![image](https://user-images.githubusercontent.com/10652810/93876605-502ad380-fd01-11ea-9982-ea4dac90fa12.png)
 @ened

**Comment by ened** [comment]
Yup, looks good. Do `flutter clean` & rebuild afterwards to check everything.

**Comment by congfandi** [comment]
@ened  i got stauck with XCODE 12.0 after i add , they say


![image](https://user-images.githubusercontent.com/10652810/94084007-b3665400-fe2e-11ea-86c0-91d6fffd8313.png)


> @congfandi you can add this to your pubspec.yaml file:
> 
> ```yaml
> dependency_overrides:
>   workmanager:
>     git:
>       url: https://github.com/ened/flutter_workmanager.git
>       ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d # flutter 1.20 compatibility
> ```

**Comment by ened** [comment]
You need to refresh the local pods. Try `cd ios && pod install`.

**Comment by congfandi** [comment]
> You need to refresh the local pods. Try `cd ios && pod install`.

done, thanks.... i will close this issue

**Comment by smolugu** [comment]
Hi @ened,

I see you have created a PR but its pending. in the mean time can we do what you suggested here?

Regards,
Shyam

**Comment by ened** [comment]
@smolugu yes, that seems to work well. :)

**Comment by smolugu** [comment]
@ened thank you but i am getting the below error. do you know what I could be doing wrong?

`/Users/shyam/Documents/flutter/nearfiv12/ios/Runner/AppDelegate.swift:25:5: error: use of
    unresolved identifier 'WorkmanagerPlugin'
        WorkmanagerPlugin.setPluginRegistrantCallback { registry in  `

AppDelegate file:

`import UIKit
import Flutter
import GoogleMaps


@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

  // Registers all pubspec-referenced Flutter plugins in the given registry.  
  static func registerPlugins(with registry: FlutterPluginRegistry) {
    GeneratedPluginRegistrant.register(with: registry)
  }

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))

    AppDelegate.registerPlugins(with: self) // Register the app's plugins in the context of a normal run
        
    WorkmanagerPlugin.setPluginRegistrantCallback { registry in  
      // The following code will be called upon WorkmanagerPlugin's registration.
      // Note : all of the app's plugins may not be required in this context ;
      // instead of using GeneratedPluginRegistrant.register(with: registry),
      // you may want to register only specific plugins.
      AppDelegate.registerPlugins(with: registry)
    }
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}`

**Comment by ened** [comment]
You need to import workmanager in that file.
Try `import workmanager` on the top.

**Comment by smolugu** [comment]
Hi.. I am getting this error now. Not sure if this related to my project settings or WorkManager

`  /Users/shyam/Documents/flutter/nearfiv12/ios/Runner/AppDelegate.swift:4:8: error: compiling
    for iOS 8.0, but module 'workmanager' has a minimum deployment target of iOS 10.0:`

**Comment by smolugu** [comment]
Hi @ened, i changed the platform:ios to 10. and did a pop install in iOS folder.
I still get the same error after running the project

**Comment by smolugu** [comment]
Hi @ened, 

Can you please see if you can help me with this? [https://github.com/fluttercommunity/flutter_workmanager/issues/223](url)

Regards,
Shyam

**Comment by SSVernekar** [comment]
https://github.com/fluttercommunity/flutter_workmanager/issues/242#issue-800338060
@ened  please help me with the above issue

**Comment by dainora** [comment]
I tried many things on Xcode, like remove all temporary files, rebuild, install pod etc. but only one thing solved me an issue:

Go to Product in Xcode > Schemes > New Scheme...
Select the name of your Cocoapod(in your case workmanager) then click OK.
After you do this, build the project (click cmd + B)

**Comment by ghost** [comment]
For anyone having this issue, try changing the import from `workmanager` to `workmanager_apple` in AppDelagete file.
