### ISSUE TITLE
My code just stop execution with PhotoManager plugin

### ISSUE THREAD

**Issue by alejandrogiubel** [fluttercommunity/flutter_workmanager#219]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       0.2.3        |
| Android Studio        |       4        |
|Flutter version        |         1.17.5      |
| Android device version   |     10    |

**Describe the error**
I use PhotoManager plugin to access to all devices's media. This plugin works ok in my app, but when I use this plugin in the callbackDispatcher the code just stop running in the line where I invoke PhotoManager plugin. How can I fix this?

**Output of `flutter doctor -v`**
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [VersiÃ³n 10.0.18363.418], locale es-ES)
    • Flutter version 1.17.5 at D:\flutter
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\AndroidSDK
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Azules\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

**Comment by gebsl** [comment]
Android? iOS?
Version?

Please fill out the standard form for posting new issues.

**Comment by alejandrogiubel** [comment]
Any idea?

**Comment by gebsl** [comment]
Seriously? Why wouldn't you provide more information? It's pretty hard to guess, what's wrong in your code...

**Comment by alejandrogiubel** [comment]
Sorry, no error is showed. Just the code stop.
This is a part of my code. I execute this code when I send the app to background. The workermanager start working but never execute the PhotoManager plugin method (`PhotoManager.getAssetPathList(onlyAll: true, type: RequestType.image)`). I use others plugin like Tflite and workermanager plugin works fine whit it.
The only difference that I see is that I use Tflite plugin only with workermanager and PhotoManager I use it in all my app.

```
Future<void> deleteUnusedImageFromDataBase() async {  
//The code stop here***********. No more execution.  
  List<AssetPathEntity> albums = await PhotoManager.getAssetPathList(onlyAll: true, type: RequestType.image);
  List<AssetEntity> media = await albums[0].assetList;
  var box = Hive.box(imagesBox);
  box.toMap().forEach((key, value) {
    ProcessedImage pi = value as ProcessedImage;
    bool exist = false;
    for (int i = 0; i < media.length; i++) {
      if (pi.id == media[i].id) {
        exist = true;
        break;
      }
    }
    if (!exist) {
      pi.delete();
    }
  });
}
```

**Comment by gebsl** [comment]
Okay. Is there any output on the debug panel when WorkManager is running in the background?

Can you maybe prepend the faulty line with a `print('something')` statement so you can verify, the code is actually run?

**Comment by alejandrogiubel** [comment]
This is the output when workermanager start. Looks like a permission problem.
```
I/flutter (12208): Start deleteUnusedImageFromDataBase
E/MethodChannel#top.kikt/photo_manager(12208): Failed to handle method call
E/MethodChannel#top.kikt/photo_manager(12208): java.lang.NullPointerException: 获取权限的Activity不存在
E/MethodChannel#top.kikt/photo_manager(12208): 	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:110)
E/MethodChannel#top.kikt/photo_manager(12208): 	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:95)
E/MethodChannel#top.kikt/photo_manager(12208): 	at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:157)
E/MethodChannel#top.kikt/photo_manager(12208): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#top.kikt/photo_manager(12208): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#top.kikt/photo_manager(12208): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#top.kikt/photo_manager(12208): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#top.kikt/photo_manager(12208): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#top.kikt/photo_manager(12208): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#top.kikt/photo_manager(12208): 	at android.app.ActivityThread.main(ActivityThread.java:7811)
E/MethodChannel#top.kikt/photo_manager(12208): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#top.kikt/photo_manager(12208): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#top.kikt/photo_manager(12208): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
I/WM-WorkerWrapper(12208): Worker result FAILURE for Work [ id=e7f765fd-3b82-4d8f-ac2f-1503cb4a63a3, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
```
And this is my code.
```
Future<void> deleteUnusedImageFromDataBase() async {
  print('Start deleteUnusedImageFromDataBase');
  bool permission = await PhotoManager.requestPermission();
  print('permission $permission');
  if (permission) {
    List<AssetPathEntity> albums = await PhotoManager.getAssetPathList(onlyAll: true, type: RequestType.image);
    List<AssetEntity> media = await albums[0].assetList;
    print('works');
    var box = Hive.box(imagesBox);
    box.toMap().forEach((key, value) {
      ProcessedImage pi = value as ProcessedImage;
      bool exist = false;
      for (int i = 0; i < media.length; i++) {
        if (pi.id == media[i].id) {
          exist = true;
          break;
        }
      }
      if (!exist) {
        pi.delete();
      }
    });
    print('Finish deleteUnusedImageFromDataBase');
  } else {
    print('permission $permission');
  }
```
This is the output of workermanager notification.
![Screenshot_20200930-112108_One UI Home2](https://user-images.githubusercontent.com/36578847/94706086-c0dc7c00-030f-11eb-9960-841ab52f9605.jpg)

**Comment by gebsl** [comment]
I think the problem is this line:

```dart
bool permission = await PhotoManager.requestPermission();
```

You can not ask the user for permission to his/her photos, as WorkManager does not run in foreground. And as I understood those permission requests, they can only be done, when the app is running in the foreground.

Can you move this line to the foreground application, to ask the user when the app is still running in foreground?
When running in background (WorkManager), only check, if permission was granted. If yes, just proceed. If no, terminate the task because there is no way of getting the permission in the background.

**Comment by alejandrogiubel** [comment]
The first I do when star the app is request permission grant to user. I use PhotoManager in others part of the app.
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.cancelAll();

  bool result = await PhotoManager.requestPermission();
  if (result) {
    final appDocumentDir = await getApplicationDocumentsDirectory();
    Hive.init(appDocumentDir.path);
    Hive.registerAdapter(ProcessedImageAdapter());
    await Hive.openBox(imagesBox);
    await Hive.openBox(imagesThumbsBox);
    runApp(MyApp());
  } else {
    PhotoManager.openSetting();
  }
}
```
Them when the user send the app to background I invoke workermanager to do `deleteUnusedImageFromDataBase()`.  
If workermanager use isolates to work in background and I request permission grant in the main isolates,  PhotoManager can access to media's device from workermanager?  
Now I changed the code like you say and I still have the same error in console.
```
Future<void> deleteUnusedImageFromDataBase() async {
  print('Start deleteUnusedImageFromDataBase');
  List<AssetPathEntity> albums = await PhotoManager.getAssetPathList(onlyAll: true, type: RequestType.image);
  List<AssetEntity> media = await albums[0].assetList;
  print('works');
  var box = Hive.box(imagesBox);
  box.toMap().forEach((key, value) {
    ProcessedImage pi = value as ProcessedImage;
    bool exist = false;
    for (int i = 0; i < media.length; i++) {
      if (pi.id == media[i].id) {
        exist = true;
        break;
      }
    }
    if (!exist) {
      pi.delete();
    }
  });
  print('Finish deleteUnusedImageFromDataBase');
}
```
And `works` never print.

**Comment by alejandrogiubel** [comment]
The problem was in PhotoManager and its permission request. I solved the issue using `PhotoManager.setIgnorePermissionCheck(true);`.  
Thank for your time. Excellent plugin, very useful. You can close this issue.

**Comment by ened** [comment]
@alejandrogiubel thank you for confirming everything works.
Just a reminder - at the time your code runs in the background, the user may have removed the photo permission already. I recommend to double check the permission before doing anything sensitive.
