### ISSUE TITLE
SharedPrefenceValue not being updated in simple Workmanager example

### ISSUE THREAD

**Issue by TKalo** [fluttercommunity/flutter_workmanager#220]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [ ] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [ ] I have run the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       0.2.3  |
| Xcode version        |        N/A       |
| Swift version        |         N/A      |
| iOS deployment target|      N/A         |

**Describe the error**
REAL GOAL:
a feature which periodically fetches an online file, decodes it and store it in a moor database.

PROBLEM:
i have tried scraping the feature to a bare minimum to find the root of the problem.
1. set a SharedPreferenceValue to false - async method "checkSubscription"
2. i call a simple backgroundtask to set the SharedPreferenceValue to true - callbackDispatcher
3. i wait 6 seconds and then display the value of the SharedPreferenceValue - async method "checkSubscription"

i get a notification saying the task was executed, and can also observe the delay i have put in.
the task is clearly executed, but the SharedPreferenceValue remains false.
i'm currently only trying to get it to work in android

````dart
void callbackDispatcherTemp() {
  print("callbackDispatcher4");
  Workmanager.executeTask((task, inputData) async {
    final prefs = await SharedPreferences.getInstance();
    prefs.setBool("BGEXECUTED", true);
    await new Future.delayed(const Duration(seconds : 3));
    return true;
  });
}

void checkSubscription(context)async{
  SharedPreferences prefs = await SharedPreferences.getInstance();
  prefs.setBool("BGEXECUTED", false);

  await Workmanager.initialize(callbackDispatcherTemp, isInDebugMode: true);
  Workmanager.registerOneOffTask("2", myTaskTemp);
  Timer(Duration(seconds: 6),() {print("BGEXECUTED: " + prefs.getBool("BGEXECUTED").toString());});

}
````

**Output of `flutter doctor -v`**
[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale da-DK)
    • Flutter version 1.22.0 at C:\Users\Troels\flutter
    • Framework revision d408d302e2 (11 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Troels\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.4
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by brunodmn** [comment]
Same issue here. When I set and get preference within callbackDispatcher() it works fine. When I try to retrieve the preference set there on my code it shows null. Bellow part of my code:

```
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
        SharedPreferences prefs = await SharedPreferences.getInstance();
	  
	  		  //populate list with API response
              var list = await ApiProvider().getSummary('userID');
			
              if (list.isNotEmpty) {
				
				 //insert api response item into var
                int nrBoletosAbertosApi = list[0]['nrBoletosAbertos'] ?? 0;
                
				//insert prefs response into var
                int nrBoletosAbertosPref =
                    prefs.getInt('nrBoletosAbertos') ?? nrBoletosAbertosApi;
                
                //init flutter_local_notifications
                NotificationManager manager = NotificationManager();
                await manager.initNotificationManager();
                NotificationChannel channel = manager.scheduledNotificationChannels.first;
				
				//conditional show notification
                if (nrBoletosAbertosPref < nrBoletosAbertosApi) {
                  custom.Notification notification = custom.Notification(
                      channel: channel,
                      notificationTitle: "Boletos disponíveis",
                      notificationID: 0,
                      notificationBody:
                          "Você tem novos boletos disponíveis para pagamento no seu app.");
                  manager.showNotificationMine(notification);
                }
                //set pref
                await prefs.setInt('nrBoletosAbertos', nrBoletosAbertosApi);               
                print('bol venc prefs:' + prefs.getInt('nrBoletosAbertos').toString());//worker runs and show correct value on this line
              }
        
  

    return Future.value(true);
  });
}
```

On my homepage widget I have a button with bellow code:
'(...)
onPressed: () async {
                SharedPreferences prefs = await SharedPreferences.getInstance();
                var teste = prefs.getInt("nrBoletosAbertos").toString();
                print(teste.toString());

                //print(_clientBoletosAbertos[1].getFormattedValorPago());
                //_showNotification();
              }
(...)'
this returns null, even with previous returned value. Also, my notifications are not being show, as its always null when it starts and not null when if finishes.

**Comment by TKalo** [comment]
I got my code working some hours ago. I wasn't able to pinpoint what finally made it work, the issue just kind of stopped.

One patch I used, however, was to make sure that I called SharedPreferences.getInstance() in my UI thread AFTER the background task had finished updating the SharedPreferences. It seems you are already doing this, but it was the only real "data" I got from my extensive troubleshooting.

Have you tried running a simple background task, which only updates a SharedPreference and then display it on the UI thread afterward? 

Also think I read you should just return true, not Future.value(true).

**Comment by brunodmn** [comment]
Thank you for your quick reply!

 Yes, I am running get instance button AFTER background task.

 I have already tried to run the callbackDispatcher() with just a simple set pref code and it did not work as well, like this:
```
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {

        SharedPreferences prefs = await SharedPreferences.getInstance();
	  	await prefs.setInt('nrBoletosAbertos', nrBoletosAbertosApi);               
	  		 
  

    return Future.value(true);
  });
}

```

 I also tried to prefs.setInt('nrBoletosAbertos', 0) before initialize the dispatcher, but it wont update the value. But it does enter on my condition and trigger my notifications, which means job is working successfully, just not permanently updating prefs value (only update temporally inside the dispatcher).

 Yesterday I had this same code working fine, it is very strange.

 I'll try to set return as 'true' as you said, I do not know what else to try.. Thank you!

**Comment by krzysztofgarnys** [comment]
I have the same, SharedPreferences  does not update when working in background.

**Comment by brunodmn** [comment]
Dear, 
 After a lot of digging into my code, I identified what was going wrong, maybe it works for you.
 In my case, I had the SharedPreferences.getInstance() as Workmanager.initialize, so, when foreground got the instance, it hadn't been set by background (Workmanager) yet.
 My workaround was to put some delay before instantiate SharedPreferences on foreground.
 I was able to reproduce the issue with bellow code on main.dart:
```
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:workmanager/workmanager.dart';

const onOffTask = "onOffTask";
const periodicTask = "periodicTask";
const keyOne = 'keyOne';
const keyTwo = 'keyTwo';

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();

    switch (task) {
      case onOffTask:
        print("$onOffTask was executed");
        await prefs.setInt(keyOne, 2);
        print('bg task $keyOne: ' + prefs.getInt(keyOne).toString());
        break;

      case periodicTask:
        print("$periodicTask was executed");
        int i = prefs.getInt(keyTwo) ?? 0;       
        print('bg task $keyTwo: ' + prefs.getInt(keyTwo).toString());
        i++;
        await prefs.setInt(keyTwo, i);
        break;
    }
    return true;
  });
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.initialize(
    callbackDispatcher,
    isInDebugMode: true,
  );
  Workmanager.registerOneOffTask(onOffTask, onOffTask);
  Workmanager.registerPeriodicTask(periodicTask, periodicTask);

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _HomePageState();
  }
}

class _HomePageState extends State<HomePage> {
  String _valueOne, _valueTwo;

  _getPrefs() async {
    //TODO uncomment bellow delay and Workmanager wont set prefs
    //Future<void>.delayed(new Duration(seconds: 1), () async {
      //waits for workmanager
      SharedPreferences prefs = await SharedPreferences.getInstance();
      setState(() {
        _valueOne = prefs.getInt(keyOne).toString() ?? '';
        _valueTwo = prefs.getInt(keyTwo).toString() ?? '';
      });
    //});
  }

  _clearPrefs() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.clear();
  }

  @override
  void initState() {
    super.initState();
    _getPrefs();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Home Page',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Home Page'),
        ),
        body: Center(
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
              Text("valueOne: $_valueOne\nvalueTwo: $_valueTwo"),
              OutlineButton(
                child: Text('Reset'),
                onPressed: () async {
                  await Workmanager.cancelAll();
                  await _clearPrefs();
                  print("All workmanager jobs cancelled");
                  print("All sharedprefs values cleared");
                  await _getPrefs();
                },
              ),
              OutlineButton(
                child: Text('update values'),
                onPressed: () async {
                  await _getPrefs();
                },
              )
            ])),
             ),
    );
  }
}
```
 Just uncomment the 'Future<void>.delayed' and it may work. Note, if you run many 'sets' on background, try to put more seconds on the delayed, in my app I using 3 seconds.
I suppose it happens because background job runs on another isolate and either you instantiate a new SharedPreference on foreground or future is not being returned by memory after setpref. 
 I don't know if it could be fixed, but it is really uncool.

**Comment by TKalo** [comment]
hi, @brunodmn not sure if I completely understood what your problem was, but if you deem it to be a bug, I think you should open a new issue describing the bug, and what behaviour you would like to see from the package. I'm glad, however, that you got it working. @krzysztofgarnys , please write back if this fixed your problem, as I will then close this issue.

**Comment by sumitbhanushali** [comment]
there is `reload()` function provided in SharedPreferences Package which fetches updated values

**Comment by brunodmn** [comment]
> there is `reload()` function provided in SharedPreferences Package which fetches updated values

 I tested and it did not work in this case.

**Comment by krzysztofgarnys** [comment]
The issue is not happen when app is minimized, but when app is close.




*Pozdrawiam serdecznie,*
*Krzysztof Garnys*
*509 948 430*

**Comment by hamzaEssaadi** [comment]
hi, if i understand your problem i would say that i have the same problem,
my solution is to call "reload" method provided by sharedPreferences instance ,like this :
` SharedPreferences sharedPreferences =
                    await SharedPreferences.getInstance();
                await sharedPreferences.reload();`

**Comment by krzysztofgarnys** [comment]
Hello
I don't know excatly what happend. RIghnt now I am okay.
Workmanager and application is using  SharedPreferences and seems it is
working fine.
I am not able to indicate what happened that I got such an issue earlier.

**Comment by gmkado** [comment]
Maybe related?
https://github.com/flutter/flutter/issues/61529
https://github.com/flutter/flutter/issues/13937

I'm having the same issue and the timing is proving very finicky

**Comment by PascalMalz** [comment]
You have to reload:
```
      SharedPreferences prefs = await SharedPreferences.getInstance();
      await prefs.reload();
      final String currentRefreshToken = prefs.getString('refreshToken') ?? '';
```
Don't forget await! That was my issue.
