### ISSUE TITLE
error: no such module 'workmanager'

### ISSUE THREAD

**Issue by smolugu** [fluttercommunity/flutter_workmanager#221]
Hi,

I am getting an error "error: no such module 'workmanager'" after updating AppDelegate file and running the app.

my AppDelegate file is as below. Please let me know if I am missing anything. have updated pod file with "platform :ios, '10.0'"
 and I am using Flutter 1.22.2

`import UIKit
import Flutter
import GoogleMaps
import workmanager

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

   static func registerPlugins(with registry: FlutterPluginRegistry) {
    GeneratedPluginRegistrant.register(with: registry)
   }

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))

    AppDelegate.registerPlugins(with: self)
        
    WorkmanagerPlugin.setPluginRegistrantCallback { registry in  
       AppDelegate.registerPlugins(with: registry)
    }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
`

Regards,
Shyam.

**Comment by juanagu** [comment]
Hello @smolugu I'm having the same error, what was your solution?
