### ISSUE TITLE
Not able to reduce frequency  duration less than 15mins. Its default taken as 15mins. Any possible solution for this

### ISSUE THREAD

**Issue by DeepaPradeepa** [fluttercommunity/flutter_workmanager#224]
Not able to reduce frequency  duration less than 15mins. Its default taken as 15mins. Any possible solution for this

**Comment by DeepaPradeepa** [comment]
I am waiting for this solution

**Comment by TommasoAzz** [comment]
The package and its creators clearly state they cannot let the activation time be smaller than 15 minutes because of the underlying implementation by the operating systems.

**Comment by DeepaPradeepa** [comment]
> The package and its creators clearly state they cannot let the activation time be smaller than 15 minutes because of the underlying implementation by the operating systems.

Thanks for your quick reply. I need to achieve in flutter code . Kindly suggest me any other libraries or methods

**Comment by ened** [comment]
@DeepaPradeepa I suggest you look at [`flutter_background`](https://pub.dev/packages/flutter_background); which may help you to run in a longer term, it may only work on Android.
