### ISSUE TITLE
Work Manager doesn't work some packages.

### ISSUE THREAD

**Issue by AhmetMelihSerter** [fluttercommunity/flutter_workmanager#226]
Work Manager not working with **gallery_saver: ^2.0.1**

Doesn't work with other libraries like this either.

We are waiting for a solution.

**Comment by syawqi** [comment]
up

doesn't work with asyncstorage too

**Comment by Tienisto** [comment]
Most packages are working on my side.

Are you using Android or iOS? If you are using iOS, don't forget to add:
```
File: ios/Runner/AppDelegate.swift

[...]

// workmanager
UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))
WorkmanagerPlugin.setPluginRegistrantCallback { registry in
  GeneratedPluginRegistrant.register(with: registry)
}

[...]

return super.application(application, didFinishLaunchingWithOptions: launchOptions)
```

**Comment by AhmetMelihSerter** [comment]
> Most packages are working on my side.
> 
> Are you using Android or iOS? If you are using iOS, don't forget to add:
> 
> ```
> File: ios/Runner/AppDelegate.swift
> 
> [...]
> 
> // workmanager
> UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))
> WorkmanagerPlugin.setPluginRegistrantCallback { registry in
>   GeneratedPluginRegistrant.register(with: registry)
> }
> 
> [...]
> 
> return super.application(application, didFinishLaunchingWithOptions: launchOptions)
> ```

I am using Android. This error occurs when i add pubspec.yaml to **gallery_saver: ^2.0.1.**

Error:
**Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@7eaf22b) but could not find and invoke the GeneratedPluginRegistrant.**

**Comment by 2math** [comment]
I have answered to you here https://github.com/CarnegieTechnologies/gallery_saver/issues/72#issuecomment-785129780
It worked in 2.0.1 before and I have fixed it that way, 2 days ago I have updated the plugin to 2.0.3 but forget to update the lib code locally and was searching for solution 2 days until I remembered the f*cking problem. But can confirm it works with 2.0.3 too. Be careful this will work on your local machine only and will be overridden if you update the plugin :)

**Comment by AhmetMelihSerter** [comment]
> I have answered to you here [CarnegieTechnologies/gallery_saver#72 (comment)](https://github.com/CarnegieTechnologies/gallery_saver/issues/72#issuecomment-785129780)
> It worked in 2.0.1 before and I have fixed it that way, 2 days ago I have updated the plugin to 2.0.3 but forget to update the lib code locally and was searching for solution 2 days until I remembered the f*cking problem. But can confirm it works with 2.0.3 too. Be careful this will work on your local machine only and will be overridden if you update the plugin :)

I disabled the package until the problem solved. I updated all packages two week ago. The problem was solved. I forgot to update here. 😂

**Comment by 2math** [comment]
Weird because I have updated to 2.0.3 and the workmanager wasn't able to register plugins, when I checked the GalerySaver code the problem wasn't fixed. I guess you have made other workaround :)

**Comment by AhmetMelihSerter** [comment]
I don't use workmanager. I use [background_fetch.](https://pub.dev/packages/background_fetch)

**Comment by AhmetMelihSerter** [comment]
> I have answered to you here [CarnegieTechnologies/gallery_saver#72 (comment)](https://github.com/CarnegieTechnologies/gallery_saver/issues/72#issuecomment-785129780)
> It worked in 2.0.1 before and I have fixed it that way, 2 days ago I have updated the plugin to 2.0.3 but forget to update the lib code locally and was searching for solution 2 days until I remembered the f*cking problem. But can confirm it works with 2.0.3 too. Be careful this will work on your local machine only and will be overridden if you update the plugin :)

I was tired. I didn't understand when you first wrote. I understood later. 😄

**Comment by ened** [comment]
It seems you have solved the problem already. Please add all details including sample code & stack trace.
