### ISSUE TITLE
Do we have to initialize firebase app in the callback function?

### ISSUE THREAD

**Issue by smolugu** [fluttercommunity/flutter_workmanager#227]

**Comment by smolugu** [comment]
I have to make a call to firestore and update database periodically.

The firestorm query is being updated successfully.

I have initialized firebase back inside the call back function. Just wondering if this is the right place.
Also will a separate isolate be created each time the callback function is called?

Regards,
Shyam

**Comment by ened** [comment]
It probably is a good place as the callback may be called when the rest of the App is not yet running or never running. 

It should use a new engine on every callback function run.
