### ISSUE TITLE
I am getting failure Result status when I am using Workmanager. Is there any solution for that

### ISSUE THREAD

**Issue by DeepaPradeepa** [fluttercommunity/flutter_workmanager#228]
I am waiting for your response.

FYR,
Result: Failure
dartTask: BackgroundLocationFetch
inputData: not Found
Ellapsed time: 1sec

**Comment by sumitbhanushali** [comment]
@DeepaPradeepa please provide sample code

**Comment by DeepaPradeepa** [comment]
@sumitbhanushali  Please get it
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case fetchBackground:
       getcurrentlocation();
        break;
      case Workmanager.iOSBackgroundTask:
        print("backgroundfetchcalled in ios");
        getcurrentlocation();
        break;
    }
    return Future.value(true);
  });
}
void getcurrentlocation() async {
  AppPreferences _appPreferences;
  _appPreferences = App().getAppPreferences();
  String tokenVal;
  Position userLocation = await Geolocator().getCurrentPosition(desiredAccuracy:LocationAccuracy.high);
  print("userLocationlat: ${userLocation.latitude.toString()}");
  _appPreferences.getAuthToken().then((value) {
    tokenVal = value;
    print("authtokenval: $tokenVal");
  }).then((value) => updateCurrentLoc(userLocation,tokenVal));


}
Future<String> updateCurrentLoc(Position position,String token) async {
  GraphQLClient graphQLClientWithHeader;
  HttpLink httpLink =
  HttpLink(uri:"http://134.209.47.247:4000/graphql",
    headers: <String, String>{
      'auth':globals.authToken,
      //"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE5MDJjY2MwLTc1ODMtMTFlYS05MmE1LWQ5NmY3M2Q5ZDUwYyIsImVtYWlsIjoiY2hnZ0BmaHZiLnZqbiIsInBob25lTnVtYmVyIjoiNzAxMDUyOTg5MyIsImlhdCI6MTYwMzcxMjA4NiwiZXhwIjoxNjE5MjY0MDg2fQ.uOF_gAVNBMUlehA7sub9OqyLwedfkYvea-L6YF-FIJk",
      //globals.authToken != ""  ? globals.authToken :,
    },);
  graphQLClientWithHeader = GraphQLClient(
    cache: new InMemoryCache(),
    link: httpLink ,
  );
//print("authtoken: ${globals.authToken}");

  var variables = <String, dynamic>{
    "lat": position.latitude,
    "lng": position.longitude
  };
@override
  void initState() {
    graphQlObject.getGraphQlClientWithHeader();
    getcurrentlocation();
    Workmanager.initialize(
        callbackDispatcher,
        isInDebugMode:true
    );

    Workmanager.registerPeriodicTask(
      "1",
      fetchBackground,
      frequency: Duration(seconds:1),
    );
}

**Comment by jibinjayachandran** [comment]
got any solution for this  ? I'm also facing same issue.Please help.

**Comment by rmaatouk** [comment]
@DeepaPradeepa have u got any solution ? Im facing same problem

**Comment by ened** [comment]
Unfortunately I can not see the actual error or warning message you are getting. Please ensure you have the correct set of permissions before running locations sensitive code in the background. Please open a new ticket if needed.
