### ISSUE TITLE
is there a way to only run workmanager task when app is closed?

### ISSUE THREAD

**Issue by sumitbhanushali** [fluttercommunity/flutter_workmanager#230]

**Comment by AhmetMelihSerter** [comment]
Just add this code to your application main method.
`void main() {
  WidgetsFlutterBinding.ensureInitialized();
}`

**Comment by AhmetMelihSerter** [comment]
[Review This Article](https://medium.com/vrt-digital-studio/flutter-workmanager-81e0cfbd6f6e)
