### ISSUE TITLE
Any way's to run a background service more frequently.

### ISSUE THREAD

**Issue by WizKi9d** [fluttercommunity/flutter_workmanager#232]
Are there any ways to run a background service more frequently. I was looking at running it every minute to check if a process needs to be carried out. 

It would also need to be when the app is killed. Maybe sticky services could be a solution? Although I'm not sure about frequency.

**Comment by TheLastGimbus** [comment]
Foreground service is what you are looking for. Without it, Android just won't let you do anything <15minutes, and labeling this as a bug is incorrect...

**Comment by ened** [comment]
@WizKi9d You probably need to look into another solution. Perhaps look at [`flutter_background`](https://pub.dev/packages/flutter_background).

This may only work on Android, though.
