### ISSUE TITLE
Getting error when working with firebase_messaging

### ISSUE THREAD

**Issue by 91priyansh** [fluttercommunity/flutter_workmanager#233]
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/firebase_messaging_background. Response ID: 2

**Comment by smolugu** [comment]
@91priyansh i get this message each time after workmanager callback function is called.
Have noticed a pause in delivery of FCM notifications but the notifications are displayed after some time.
let me know if you know why this is happening.
Thank you!

**Comment by wrteam-priyansh** [comment]
@smolugu in my case i am not getting any notification after this error.Do you know any other package that work with firebase_messaging in background

**Comment by ened** [comment]
hi @91priyansh - thank you for the report. Could you re-test using the latest `workmanager` version `0.4.0` and also the latest [firebase_messaging](https://pub.dev/packages/firebase_messaging) version?

**Comment by 91priyansh** [comment]
@ened sure will re-test it

**Comment by ened** [comment]
Thank you @91priyansh. If you see another issue, please open a new issue with **detailed stack trace**, **logs** and ideally a **sample project** - so that we can quickly verify the problem.
