### ISSUE TITLE
 In the following code if i remove for loop showNotification works otherwise not workmanager fails please help me anyone.

### ISSUE THREAD

**Issue by SSVernekar** [fluttercommunity/flutter_workmanager#235]
void callbackDispatcher() async{

Workmanager.executeTask((task, inputData) async {

print("responce : ${inputData['plants'].toList()}");
List notifications = [NotificationData("1","a"),NotificationData("2","a")];

for (var notificationData in inputData['plants'].toList()){

  notifications.add(NotificationData(
  notificationData["meterId"]!="null"?notificationData["meterId"]:0, notificationData["lastDayEnergy"]!="null"? 
  notificationData["lastDayEnergy"]:0));
}

showNotification(notifications);
return true;
});

**Comment by gebsl** [comment]
Can you post any debug logs?
I suspect `showNotification` is an async function and you are not `await`ing it.

And please don't include the whole question in the title and format your code. At the moment it's hard to get the issue.

**Comment by SSVernekar** [comment]
@gebsl thanks for your reply 
i found the solution actully i was awaiting correctly but i was hot reloading so changes are not reflecting.
now it is working.
