### ISSUE TITLE
How to provide dependencies to workmanager?

### ISSUE THREAD

**Issue by Ascenio** [fluttercommunity/flutter_workmanager#237]
Imagine you have something like this:
```dart
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) {
    if (task == 'sendNotifications') {
        // How to get the service there??
        notificationService.sendNotification('Hello World');
        return true;
    }
    return false;
  });
}


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.initialize(
    callbackDispatcher,
    isInDebugMode: true
  );
  Workmanager.registerOneOffTask("1", "sendNotifications");
  runApp(
    Provider(
      create: (_) => NotificationsService(),
      child: MaterialApp(),
    ),
  );
}
```
How would you inject the NotificationsService into the static method so that the scheduled task can send notifications?
Generally, to get access to it, the package should be inside the widget tree, but its not. Also it's a static method called _magically_.
Is there any solution to this? Currently I'm creating instances manually and duplicating logic in the static method.

**Comment by whoch-g2e** [comment]
In my case, the functional methods of Provider objects were used the same in the background (create and use).
```
void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) {
    if (task == 'sendNotifications') {
        NotificationsService notificationService = NotificationsService();
        notificationService.sendNotification('Hello World');
        return true;
    }
    return false;
  });
}

```
If you want background and foreground apps to communicate, you can use `IsolateNameServer`

 This comment might help you #151  #184

**Comment by Ascenio** [comment]
See, it's not that I need my app to communicate with the UI, it's just that if that's the case I have to instantiate all of the dependencies manually and also duplicate some logic. I don't like that, but what can I do ¯\_(ツ)_/¯

Also thanks for the references, they look very interesting.
