### ISSUE TITLE
How to cancel background task in iOS

### ISSUE THREAD

**Issue by whoch-g2e** [fluttercommunity/flutter_workmanager#238]
Hi. Thanks for supporting a good package😇

I'm using this package to develop log sync in the background.
My functions are optional, so I need to cancel on iOS.

I'm cancel using `cancelByUniqueName` on Android, what should I do with iOS?

**Comment by Ascenio** [comment]
I think both [cancelByTag and cancelByUniqueName](https://pub.dev/packages/workmanager#by-tag) should work, whatever might be the OS.

**Comment by whoch-g2e** [comment]
@Ascenio I think the same thing. But In my knowledge It's only for Android😢

**Comment by Ascenio** [comment]
Both of them?

**Comment by whoch-g2e** [comment]
Yes. registerPeriodicTask, Tagging and Cancellation(cancelByTag, ...) all belong to [Customisation (Android only!) ](https://pub.dev/packages/workmanager#customisation-android-only)

**Comment by Ascenio** [comment]
Weird. I thought the 'Android only' thing were about periodic tasks only. If so, it makes the plugin not very helpful for iOS.

**Comment by sooxt98** [comment]
I don't think its possible with this lib, background_fetch should work out of the box
https://pub.dev/documentation/background_fetch/latest/background_fetch/BackgroundFetch/stop.html

**Comment by ened** [comment]
Please try using cancellation with the latest version `0.5.0-dev.8` which utilizes the background task APIs.

**Comment by smile-yoshryo** [comment]
```0.5.0-dev.8``` installed. but, It seems that only oneOffTask is supported for unique key registration in ios.
Is it possible to register repeated tasks on ios?
