### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by helloalbin** [fluttercommunity/flutter_workmanager#239]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [ ] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [ ] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     0.2.3          |

**Describe the error**
WorkManager scheduler is not scheduling any tasks. I have periodic tasks, one-off task scheduled after 5 minutes and one off task scheduled immediately. Only the task scheduled immediately works. 

**Output of `flutter doctor -v`**
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.22.3 at C:\Apps\flutter
    • Framework revision 8874f21e79 (3 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Apps\Android\SDK
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Apps\Android\SDK
    • Java binary at: C:\Apps\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Apps\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • YU5530 (mobile) • VY0025160460702260 • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 2 categories.

**Comment by helloalbin** [comment]
Attaching the code [https://github.com/helloalbin/flutter_app](https://github.com/helloalbin/flutter_app)

**Comment by hassanrehman01398** [comment]
Same issue.Any solution?

**Comment by Sidharathjain0439** [comment]
Same issue . I scheduled a periodic task with frequency 20 minutes but I am not getting any debug notification that task is executed or not.

**Comment by ened** [comment]
0. Check with the latest version
1. `await` all the calls
2. use different tags
