### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by MooNag** [fluttercommunity/flutter_workmanager#241]
Hi,

I am planning on using this package in a null safe project and I was wondering if there was plans for implementing null safety or an existing attempt I can contribute to?

Thanks!

**Comment by parthdave93** [comment]
Created PR let's see when it's going to merge: [here is the link](https://github.com/fluttercommunity/flutter_workmanager/pull/244)

**Comment by ened** [comment]
This has been addressed by #244 & is published in version **0.4.0**. Thank you all for you your patience.
