### ISSUE TITLE
Package doesn't exist (the pubspec for workmanager 0.2.4 from git has version 0.2.3).                              

### ISSUE THREAD

**Issue by SSVernekar** [fluttercommunity/flutter_workmanager#242]
Not able to  run pub get when  the following code aded to pubspec
@ened please help me.

dependency_overrides:
  workmanager:
    git:
      url: https://github.com/ened/flutter_workmanager.git
      ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d

**Comment by SSVernekar** [comment]
it was  related  to my mac

**Comment by Harrys76** [comment]
> it was related to my mac

how you resolved this?
