### ISSUE TITLE
Replace iOS's deprecated performFetchWithCompletionHandler with BGTaskScheduler 

### ISSUE THREAD

**Issue by regmoraes** [fluttercommunity/flutter_workmanager#243]
The current version of the library uses the [deprecated `performFetchWithCompletionHandler`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623125-application) so I propose the replacement of it with the [recomended `BGTaskScheduler` ](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask).

**Comment by 2math** [comment]
Hi @regmoraes , what is the advantage of the new approach?

I'm testing with another library and also reading the documentation and can say that I'm disappointed.
While was expecting similar behavior as with the android's WorkManager, here iOS again decides when to run your task, no matter that all constraints are met. 

With current approach(performFetchWithCompletionHandler) I just check if there is an internet connection available in the beginning of the task.
I think current approach also is called when there is internet connection only too.

I expect when run a task with a constrain internet connection and currently has connection, the task to be started as in android immediately or if I enable any connection to be started right a way. I don't see this happening on iOS and unless they are going to deprecate current sync approach I'm not sure is worth it.

**Comment by ened** [comment]
https://uynguyen.github.io/2020/09/26/Best-practice-iOS-background-processing-Background-App-Refresh-Task/ has a bit more details. I'm currently implementing this for `flutter_uploader`, will migrate for this plugin as well. There are _some_ benefits, e.g. the constraints to _start_ the task would obsolete any constraint checks within the task. We can also assign a task result (true / false), although I'm not clear how to handle retries yet.

**Comment by ened** [comment]
Hi everyone, I'd appreciate feedback on the PR #279. There are also a few documentation updates. The BGTaskScheduler work will find it's way into a pub prerelease (0.5.0-dev.2) soon.
