### ISSUE TITLE
[QUESTION] Is this package still maintained?

### ISSUE THREAD

**Issue by futurelucas4502** [fluttercommunity/flutter_workmanager#246]
Hi so after trying to use this with iOS I got the same errors as many other people and have had to use the git branch found [here](https://github.com/fluttercommunity/flutter_workmanager/issues/189#issuecomment-749037991)

My question is, is this package still being maintained as there are no branches other than main and the last commit was all the way back in July of 2020 which is quite a while ago now

**Comment by neoacevedo** [comment]
What I can see, this package seems to be abandoned, because no one answer in any latest issues comes from the owners.

**Comment by ened** [comment]
hi everyone, the project is maintained again - I have just started working my way through the open PRs and will work through the open issues as time allows. Thank you for your patience.
