### ISSUE TITLE
workmanager does not work without auto-start permission

### ISSUE THREAD

**Issue by thekavak** [fluttercommunity/flutter_workmanager#250]
Hi,
A few days ago I opened a thread like this in stackoverflow. 
https://stackoverflow.com/questions/66771130/android-allow-app-to-start-automatically-permission-code/66771652#66771652 
I use xiaomi mi 10 and the workmanager doesn't work by itself as I installed it. I need to allow manual auto start from settings. How can I overcome this situation?

**Comment by PaoloP98** [comment]
I have also encountered this problem
So, I wrote an android plugin to launch the intent. I'll put it on a public repository and share you the link

**Comment by thekavak** [comment]
@PaoloP98 Thank you I really needed this. I am waiting for link from you.

**Comment by PaoloP98** [comment]
@thekavak 
here we go. I have written a short readme to explain how to use it.
Let me know if you solve your problem
https://github.com/PaoloP98/FlutterAutostartIntent

**Comment by thekavak** [comment]
@PaoloP98  I will include it in my project as soon as possible. Thank you so much.

**Comment by ened** [comment]
Thank you @PaoloP98 that is a great find and superb to see the plugin at https://github.com/PaoloP98/FlutterAutostartIntent.

What are your plans for this plugin? Are you planning to publish it? It would be great to link it in the [Wiki](https://github.com/fluttercommunity/flutter_workmanager/wiki).

Will close the ticket as it seems to have been resolved by your research & the plugin.

**Comment by PaoloP98** [comment]
Hi @ened, a few days ago I saw that there is already a plugin for this purpose: https://pub.dev/packages/android_autostart
I read the intents used and they seem to be the same. Perhaps he got them from the same source as me (https://stackoverflow.com/a/48945679/15328543)

So maybe it doesn't make sense to publish my plugin

**Comment by ened** [comment]
Oh very nice. We should document this, great knowledge!
