### ISSUE TITLE
🐞[ POST - form-data is not working in callback dispatcher however the same code works fine when making the post call from Flutter user interface trigger

### ISSUE THREAD

**Issue by mg7237** [fluttercommunity/flutter_workmanager#251]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md): Yes
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md): Yes
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md): NA
- [x] I have ran the sample app and it does work there:  Sample app works.
**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |         ^0.2.0      |
| Xcode version        |       NA        |
| Swift version        |         NA      |
| iOS deployment target|         NA      |
Tried Dio : ^4.0.0 and HTTP: ^0.12.2 . Same behaviors in both cases.

**Describe the error**
When a user submits the post request using Flutter UI, the POST call is successful however when the same call is made from the callbackDispatcher, the POST call is not working. It even doesn't throw any errors. Reference code is below:

**callbackDispatcher code:**

``` dart
            String text1 = row['FIRST_DATA'];
              String text2 = row['SECOND_DATA'];
              int id = row['ID'];
              if (await apiHelper.postData(text1, text2)) {
                dbHelper.delete(id);
           }
```

**apiHelper.PostData**

``` dart 
   var options = BaseOptions(
      baseUrl: 'http://zapp.fxsonic.com/api',
      connectTimeout: 5000,
      receiveTimeout: 3000,
    );
    Dio dio = Dio(options);
    var url = Uri.parse('http://zapp.fxsonic.com/api/register_pestcontrol');
    var _url = 'http://zapp.fxsonic.com/api/register_pestcontrol';
    Map<String, String> body = {
      'first_data': firstData,
      'second_data': secondData,
      'user_token': 'pest'
    };
    var formData = FormData.fromMap(body);
    try {
      response = await dio.post('/register_pestcontrol', data: formData);
      if (response != null && response.statusCode == 200) {
        print(response.data);
        return true;
      } else {
        return false;
      }
    } catch (e) {
      print(e);
      return false;
    }
```

****
**Output of `flutter doctor -v`**
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.1 at /Users/manishgupta/StudioProjects/flutter
    • Framework revision c5a4b4029c (5 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/manishgupta/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Dev Tools/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Dev Tools/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

**Comment by ened** [comment]
@mg7237 please ensure all futures are awaited, then try again. Please kindly also check with the latest WorkManager version , 0.4.1.
