### ISSUE TITLE
🐞[MissingPluginException] 

### ISSUE THREAD

**Issue by UnluckyY1** [fluttercommunity/flutter_workmanager#255]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      last     |
| Platform       |        android       |
| flutter version       |        1.22.6      |

**Describe the error**
i am not able to run workmanager with flutter_Local_Notfication after more than 5 hours of reasrch i found solution [link](https://www.coder.work/article/7310010)
i made a custom application class and registered other plug-ins

```
public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        WorkmanagerPlugin.setPluginRegistrantCallback(this);

    }

    @Override
    public void registerWith(PluginRegistry registry) {
        // GeneratedPluginRegistrant.registerWith(registry);


        FlutterLocalNotificationsPlugin.registerWith(registry.registrarFor("com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin"));

        //com.example.bluetooth_print.BluetoothPrintPlugin.registerWith(shimPluginRegistry.registrarFor("com.example.bluetooth_print.BluetoothPrintPlugin"));

        WorkmanagerPlugin.registerWith(registry.registrarFor("be.tramckrijte.workmanager.WorkmanagerPlugin"));
    }
}
```
but without success 
```
W/FlutterEnginePluginRegistry(19323): Attempted to register plugin (io.flutter.embedding.engine.g.g.a$b@161cc0a) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.a@d945475).E/MethodChannel#(19323): Parameter messenger must not be null.
E/WM-WorkerWrapper(19323): Work [ id=f6ba8d9c-bba1-4923-b026-96dc061c47f8, tags={ be.tramckrijte.workmanager.BackgroundWorker } ] failed because it threw an exception/error
E/WM-WorkerWrapper(19323): java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke interface method 'void e.a.d.a.b.a(java.lang.String, e.a.d.a.b$a)' on a null object reference
E/WM-WorkerWrapper(19323):      at androidx.work.impl.utils.m.a.c(:516)
E/WM-WorkerWrapper(19323):      at androidx.work.impl.utils.m.a.get(:475)
E/WM-WorkerWrapper(19323):      at androidx.work.impl.k$b.run(:298)
E/WM-WorkerWrapper(19323):      at androidx.work.impl.utils.f$a.run(:91)
E/WM-WorkerWrapper(19323):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(19323):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(19323):      at java.lang.Thread.run(Thread.java:764)
E/WM-WorkerWrapper(19323): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void e.a.d.a.b.a(java.lang.String, e.a.d.a.b$a)' on a null object reference
E/WM-WorkerWrapper(19323):      at e.a.d.a.j.a(:119)
E/WM-WorkerWrapper(19323):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onAttachedToEngine(:900)
E/WM-WorkerWrapper(19323):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.registerWith(:137)
E/WM-WorkerWrapper(19323):      at com.siyoumarkettn.siyou.Application.a(:28)
E/WM-WorkerWrapper(19323):      at be.tramckrijte.workmanager.BackgroundWorker.j(:80)
E/WM-WorkerWrapper(19323):      at androidx.work.impl.k$a.run(:281)
E/WM-WorkerWrapper(19323):      at android.os.Handler.handleCallback(Handler.java:873)
E/WM-WorkerWrapper(19323):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/WM-WorkerWrapper(19323):      at android.os.Looper.loop(Looper.java:193)
E/WM-WorkerWrapper(19323):      at android.app.ActivityThread.main(ActivityThread.java:6758)
E/WM-WorkerWrapper(19323):      at java.lang.reflect.Method.invoke(Native Method)
E/WM-WorkerWrapper(19323):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/WM-WorkerWrapper(19323):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
I/WM-WorkerWrapper(19323): Worker result FAILURE for Work [ id=f6ba8d9c-bba1-4923-b026-96dc061c47f8, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
```
than i figure out that this error is caused by this line
`WorkmanagerPlugin.setPluginRegistrantCallback(this);`

i've been searching for solution for 2 days now without any result and i am near to giveup and try  background_fetch

```
**Output of `flutter doctor -v`**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.928], locale en-150)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.55.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by ened** [comment]
hi @UnluckyY1 can you please confirm your use case ? You are scheduling a background task using `workmanager` & plan to show an notification when background work is done, using the `flutter_local_notifications` plugin. Correct?

**Comment by UnluckyY1** [comment]
@ened yes its correct

**Comment by UnluckyY1** [comment]
@ened yes its correct after 2 days i found out that one my dependencies is causing the ` bluetooth_print 2.0.0` removing this dependencie my yaml will make it work perfectly but its not a solution for me because one of the main futures in my app using this plugin after a more thorough investigation i found out that this plugin is getting generated by ShimPluginRegistry inside my GeneratedPluginRegistrant.java which is A PluginRegistry that is shimmed to let old plugins use the new Android embedding and plugin API behind the scenes by flutter team documetion i know that this issue is not anymore a workmanager issue but  am not an expert on java , going in cercels without a real solution

**Comment by ened** [comment]
@UnluckyY1 Your best bet is probably to chat with the `bluetooth_print` maintainer and submit a small reproducible example on GitHub. Feel free to link it here as well.

Plugins don't always play well with multiple instances of the Flutter Engine (& thus themselves). It is relatively easy to fix once the maintainer can repro the problem.
