### ISSUE TITLE
[Android] background working screen off only if device is powered by cable..

### ISSUE THREAD

**Issue by nitneuq33** [fluttercommunity/flutter_workmanager#259]
I don't know if it's normal and if something is possible to do, but I use workmanager to run accelerometer in background to monitor physic activities. It's work great when the screen is off but only if the device is powered by his usb cable ( no need to be connected to a laptop, just usb 5V and it works). Problem: I need to run my app in pocket and so to be autonomous. it's a normal limitation from Android, packages, or bad use of the package ? thank you

**Comment by ened** [comment]
@nitneuq33 it probably is a limitation in Android - running code long-time in the background needs a background service (foreground service nowadays) to hold onto. I suggest the [flutter_background](https://pub.dev/packages/flutter_background) package which does exactly that.
