### ISSUE TITLE
Possible to access local storage with background tasks?

### ISSUE THREAD

**Issue by Wizzel1** [fluttercommunity/flutter_workmanager#261]
Is it possible to access local storage with workmanager if app is not running? I need to run a task every 24 hours that loads some data from disk and schedules local notifications based on the result.

**Comment by ened** [comment]
Yes should be no problem.
Mind you though if the user has removed the permission (or the permission expired, thx Android 11), then you need to handle permissions first.

You can use plugins to check, like "permission_handler".
