### ISSUE TITLE
How to Register A specfic plugin on IOS

### ISSUE THREAD

**Issue by heshaShawky** [fluttercommunity/flutter_workmanager#266]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Describe the error**
I'm using the Shared preference plugin and I need to register it only as when I have used the code on the readme throw an error with InAppBrowser plugin.

I'm not an expert with swift/iOS development and I can't find a way to register only the shared preference plugin instead of all of them.

**Comment by SayedShalan** [comment]
Did you find a solution ?

**Comment by ened** [comment]
Please refer to the example project how to register plugins for WorkManager. https://github.com/fluttercommunity/flutter_workmanager/blob/master/example/ios/Runner/AppDelegate.swift#L14

You can adjust the swift code if you need to only load specific plugins.
