### ISSUE TITLE
🐞[Android and Ios] registerOneOffTask

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [fluttercommunity/flutter_workmanager#267]
- [v] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [v] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [v] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [v] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       4.0        |
| Xcode version        |       12.4        |
| Swift version        |               |
| iOS deployment target|       10.0        |

I ran code with version 0.4.0 have this error . 

Unhandled Exception: PlatformException(unhandledMethod("registerOneOffTask") error, Unhandled method registerOneOffTask, null, null)

I do same as your example

**Comment by ened** [comment]
Please clean the project (`flutter clean`) and try again. Also, please use the latest WorkManager version 0.4.1.

**Comment by CaoGiaHieu-dev** [comment]
Still not working

**Comment by ened** [comment]
I see now. You are running on iOS, right? 
The `register*` methods are not supported on iOS.

Instead, iOS will currently run whenever the system is idle (or a fetch request occurred). 

You can refer to the example project how to handle a background task on iOS: https://github.com/fluttercommunity/flutter_workmanager/blob/master/example/lib/main.dart#L51
