### ISSUE TITLE
🐞Shared Preference inside execute task, Missing plugin

### ISSUE THREAD

**Issue by SayedShalan** [fluttercommunity/flutter_workmanager#268]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.4.0         |

**Describe the error**
execute task failed in await SharedPreferences.getInstance() , Note Iam using also facebook plugin .

**Comment by ened** [comment]
Please submit further details, stack trace and any error logs in the console / adb logcat. Did you follow the instructions in https://github.com/fluttercommunity/flutter_workmanager/blob/master/ANDROID_SETUP.md or https://github.com/fluttercommunity/flutter_workmanager/blob/master/IOS_SETUP.md ?
