### ISSUE TITLE
execute sequential task ?

### ISSUE THREAD

**Issue by LabN36** [fluttercommunity/flutter_workmanager#269]
Hi, 
can you please let me know on how can i run tasks based on sequence, is there a way to achieve this ?

Please provide me some hints so that i can customize it accordingly.

**Comment by madd-project** [comment]
Yes, is synchronous code not working? hmm

**Comment by LabN36** [comment]
hey, i'm talking about sequential

**Comment by ened** [comment]
@LabN36 you refer to WorkManagers sequential processing? One task depending the other?
