### ISSUE TITLE
Periodic task not performing every X minutes (power saving feature?)

### ISSUE THREAD

**Issue by contenta-rok** [fluttercommunity/flutter_workmanager#271]
Hello.

I have set frequency for periodic task to 15 minutes and set isInDebugMode to true to check when task if fired. 

When I'm active on phone, next few tasks are performed around 15 minutes. When phone is not touched for few hours, frequency starts to increase to half a hour or even a hour. Through night frequency was increased to few hours.

Currently I'm only testing on Android. Does this happens because of some power saving feature?
Is there any way to perform task every 15 minutes?

Greetings.

**Comment by ened** [comment]
@contenta-rok Unfortunately that is expected behavior when using work manager. If you plan on running periodic tasks with increased certainty, try out plugins like [`flutter_background`](https://pub.dev/packages/flutter_background).

**Comment by ened** [comment]
@contenta-rok something to look at https://dontkillmyapp.com - please try it out and play around with the settings applicable to your phone model & OS version.
