### ISSUE TITLE
FlutterJNI was detached from native C++

### ISSUE THREAD

**Issue by pjdupreez** [fluttercommunity/flutter_workmanager#278]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it DOES  work

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.2.2         |

**Describe the error**

Followed everything in the readme file, and everything works as expected until the background job executes. I am trying to simply call a REST service endpoint. Don't care about the response. Simple job just to trigger an event on the server after a time period as expired.

The sample app works fine, no issues there.

Tried some of the tips on 'Don't kill my app!' but doesnt work.

Here is the relevant console out:

> D/FlutterSecureStoragePl(17038): Initializing StorageCipher
> I/WM-WorkerWrapper(17038): Worker result SUCCESS for Work [ id=2692e675-e58c-42e7-8799-798869169a7e, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
> D/FlutterSecureStoragePl(17038): StorageCipher initialization complete
> W/FlutterJNI(17038): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 2

Here is my job and related code:
```
const String myJobKey = "job.key";

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case myJobKey:
        logger.i("$myJobKey was triggered");
        _doTheWork(inputData);
        break;

      case Workmanager.iOSBackgroundTask:
        logger.i("iOS background fetch was triggered!");
        _doTheWork(inputData);
        break;
    }

    return Future.value(true);
  });
}

void _doTheWork(inputData) {
  logger.i("make the server call")

  // everything works up to this point.
  // code below is either not reached or does not run.

  MyRepository repository = MyRepository();
  repository.makeTheCall(inputData["myId"]);
}

import 'package:http/http.dart';
import 'package:http_interceptor/http_client_with_interceptor.dart';

class MyRepository {
  final Logger logger = Logger();
  Client client = HttpClientWithInterceptor.build(
      retryPolicy: ExpiredTokenRetryPolicy(),
      interceptors: [
        ApiInterceptor(),
      ]);

  Future makeTheCall(String id) async {
    try {
      final url =
          "${AppCore.baseUrl}/api/services/app/think/foo?Id=$id";

      final response = await client.get(Uri.parse(url));

      if (response.statusCode == 200) {
        //dont care about a respons
      } else {
        throw Exception("something went wrong");
      }
    } catch (e) {
      logger.e(e);
    }
  }
```

**Output of `flutter doctor -v`**

[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_ZA.UTF-8)
    • Flutter version 2.0.5 at /home/user/snap/flutter/common/flutter
    • Framework revision adc687823a (8 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • SM A510F (mobile) • 00000000000000 • android-arm     • Android 7.0 (API 24)
    • SM A205F (mobile) • 00000000000000 • android-arm64 • Android 10  (API 29)

! Doctor found issues in 1 category.

I tried running on both of my connected devices, both are giving the issue.

Could it be the http package? 

>  http: ^0.13.3
>  http_interceptor: ^0.4.1

**Comment by ened** [comment]
It may be a issue in flutter_secure_storage. Do you need to dispose/close or otherwise deinitialize the plugin when you are done using it?

**Comment by pjdupreez** [comment]
Thanks. I just tried with `secure_storage` to see if it would make a difference from using the `http` package, which I thought might be the issue.

The `MyRepository` actually resides in another dart file. Should the code that must be run in the background also be in main.dart file?

**Comment by ened** [comment]
The location of the source code does not matter. 

Just make sure that asynchronous functions are awaited and native plugins are deinitialized. If you have streamsubscriptions, make sure to cancel them, too.

**Comment by pjdupreez** [comment]
Ok, so I double checked everything again. Made sure I am using the latest version of `workermanager` (0.4.1). I am awaiting all async methods (eg `makeTheCall' from the `MyRepository` Class).

When I run the app in debug, just before the console prints out `Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 2` an exception is thrown in `errors_patch.dart` from this bit of code (line 212)
`
// The compiler emits a call to _throwNew when it cannot resolve a static
  // method at compile time. The receiver is actually the literal class of the
  // unresolved method.
  @pragma("vm:entry-point", "call")
  static void _throwNew(
      Object receiver,
      String memberName,
      int invocationType,
      int typeArgumentsLength,
      Object? typeArguments,
      List? arguments,
      List? argumentNames) {
    throw new NoSuchMethodError._withType(receiver, memberName, invocationType,
        typeArgumentsLength, typeArguments, arguments, argumentNames); // <-- exception thrown here
  }
`
Exception Message:

`NoSuchMethodError (NoSuchMethodError: No top-level getter '_registerPlugins' declared.
Receiver: top-level
Tried calling: _registerPlugins`

Could this have something to do with it? Should I have a `_registerPlugins` method somewhere in my project?

**Comment by ened** [comment]
@pjdupreez nice investigation. There should be no need for `_registerPlugins`, it's not related to WorkManager. There is `registerPlugins` on the native side for getting plugins to work but this is not related to your problem I think.

Can you modify this dart above and print the stack trace? `print StackTrace.current()`, so we can figure out who is trying to call this method.

**Comment by pjdupreez** [comment]
I added `StackTrace.current` just before I instantiate my repository. This is the output:

```
I/flutter (20085): [38;5;208m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (20085): [38;5;208m│ #0   _doTheWork
I/flutter (20085): [38;5;208m│ #1   callbackDispatcher.<anonymous closure>
I/flutter (20085): [38;5;208m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (20085): [38;5;208m│ ⚠️ #0      _doTheWork (package:myapp/main.dart:65:23)
I/flutter (20085): [38;5;208m│ ⚠️ #1      callbackDispatcher.<anonymous closure> (package:myapp/main.dart:48:9)
I/flutter (20085): [38;5;208m│ ⚠️ #2      callbackDispatcher.<anonymous closure> (package:myapp/main.dart:44:29)
I/flutter (20085): [38;5;208m│ ⚠️ #3      Workmanager.executeTask.<anonymous closure> (package:workmanager/src/workmanager.dart:93:28)
I/flutter (20085): [38;5;208m│ ⚠️ #4      Workmanager.executeTask.<anonymous closure> (package:workmanager/src/workmanager.dart:91:45)
I/flutter (20085): [38;5;208m│ ⚠️ #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:435:55)
I/flutter (20085): [38;5;208m│ ⚠️ #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:382:34)
I/flutter (20085): [38;5;208m│ ⚠️ #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
I/flutter (20085): [38;5;208m│ ⚠️ #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:221:15)
I/flutter (20085): [38;5;208m│ ⚠️ #9      _rootRun (dart:async/zone.dart:1354:13)
I/flutter (20085): [38;5;208m│ ⚠️ #10     _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (20085): [38;5;208m│ ⚠️ #11     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (20085): [38;5;208m│ ⚠️ #12     _invoke3 (dart:ui/hooks.dart:220:10)
I/flutter (20085): [38;5;208m│ ⚠️ #13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
I/flutter (20085): [38;5;208m│ ⚠️ #14     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
I/flutter (20085): [38;5;208m│ ⚠️ 
I/flutter (20085): [38;5;208m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterSecureStoragePl(20085): Initializing StorageCipher
I/WM-WorkerWrapper(20085): Worker result SUCCESS for Work [ id=93611f88-d324-43b4-8bd3-848581283e88, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
D/FlutterSecureStoragePl(20085): StorageCipher initialization complete
W/FlutterJNI(20085): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 2
```

Also, I have been Googling a bit and found similar reported issues on GitHub and StackOverflow, mainly about using firebase/firebase_messanger/location/geo_location packages. Might be related as I am using various firebase packages also

**Comment by pjdupreez** [comment]
@ened ... got it working!!!

and I feel stupid... I never changed my `_doTheWork` function to be of type Future! I only added `async` to the method signature...

Thanks for your assistance, though.
