### ISSUE TITLE
How to use Hive with workmanager?

### ISSUE THREAD

**Issue by madd-project** [fluttercommunity/flutter_workmanager#280]
**Version**
Technology            Android
Work manager 0.4.2

Well, the Work manager is beautifully working for me, It is doing its job great in the system it is giving expecting outputs beautifully.

**Question**
How to use HiveDb with the WorkManager?
I know that we have to Initialize Hive inside the callback dispatcher but I am not able to do it, Actually, It is not understandable to me, Many Experts say, that you have to Initialize Hive inside the WorkManager, But Practically, I can't Understand How to Do it..  

Can the Creators of the Beautiful Package, Provide me the Minimal Code, an example of how to do it?
I am really anxious about it.

**Comment by Donk3ys** [comment]
Try this for your callBackDispacher.

```
void _callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    print("Native called background task: $task");

    // Init Hive
    await Hive.initFlutter();
    final hiveBox = await Hive.openBox("hive");

    await hiveBox.put('name', 'David');
    final name = await hiveBox.get("name");
    print(name);

    return Future.value(true);
  });
}
```

**Comment by madd-project** [comment]
Thanks alot @Donk3ys

**Comment by ened** [comment]
It seems like the issue is resolved. Thank you everyone for the help.
