### ISSUE TITLE
How to call workmanager after login?

### ISSUE THREAD

**Issue by Shubham-Narkhede** [fluttercommunity/flutter_workmanager#281]
I'm using workmanager for calling an api in background it gives right response but on main method. I want the same method used in after login. Means when user successlly login and enter into application. Then call HTTP method in background. How it is possible?

**Comment by ened** [comment]
You can call any methods and app components in the callback dispatcher as shown in the [example](https://github.com/fluttercommunity/flutter_workmanager/tree/master/example). 

Just make sure to `await` the result.

**Comment by Shubham-Narkhede** [comment]
@ened I checked the example and used await for the result and it working fine but it called only once means I added initial delay for 5 min still it called only once not calling repetedaly

**Comment by ened** [comment]
@Shubham-Narkhede perhaps workmanager is not the best package for what you are trying to achieve. You would like to run HTTPs commands whenever the user has logged in? workmanager can not make guarantees for the timely execution. Consider it more like a package to collect background tasks and execute them reliably, but without a reliable schedule.
