### ISSUE TITLE
🐞```java.lang.ClassCastException``` when initializing the Workmanager

### ISSUE THREAD

**Issue by julianbraasch** [fluttercommunity/flutter_workmanager#282]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
~I have ran the sample app and it does not work there~ Not applicable

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |0.4.1               |
| Xcode version        | 12.5              |
| Swift version        | 5              |
| iOS deployment target|11.0               |

**Describe the error**
Disclaimer:
- I don't know if my issue is actually related to this plugin, but it was where I noticed it
- I don't know if the issue can even be fixed in this plugin or if it's caused by some code from the Android SDK

My app was initially created with Flutter version 1. Because of several large dependencies, I had to enable [MultiDex](https://developer.android.com/studio/build/multidex) to get over the 64K limit. Everything worked up until here.

When I decided to migrate the app to Flutter 2, I also bumped the minSdkVersion from 18 to 21 .This allowed me to get rid of MultiDex since SDK >= 21 uses the newer "Android Runtime" (ART) which automatically handles splitting classes into multiple .dex files.
This change led to some more dependency changes under the hood: I upgrade to Gradle 4.2.1 and workmanager 0.4.1.
When I ran the app, I was presented with the following error:
```
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): Failed to handle method call
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at be.tramckrijte.workmanager.Extractor.extractWorkManagerCallFromRawMethodName(Extractor.kt:157)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at be.tramckrijte.workmanager.WorkmanagerCallHandler.onMethodCall(WorkmanagerCallHandler.kt:21)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#be.tramckrijte.workmanager/foreground_channel_work_manager( 9025): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Somehow, the plugin failed to cast the handle identifier for the callback from an Integer to a Long.

Long story short: I fixed the issue by renaming the callback function. My guess is that the callback function name is cached somewhere and the change from manual to automatic MultiDex messed something up. That is why I am not sure if this is even fixable.

**Output of `flutter doctor -v`**
```bash
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    de-DE)
    • Flutter version 2.2.1 at /Users/dev/development/devTools/flutter-sdk
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5556 • android-x86 • Android 11 (API
      30) (emulator)

• No issues found!
```

**Comment by ened** [comment]
@julianbraasch workmanager should, however, accept Integer or Long and cast to Long internally. Will consider as a bug. Thank you!

**Comment by pvsvamsi** [comment]
@ened Facing the same issue. Is this fix released?

**Comment by ened** [comment]
> @ened Facing the same issue. Is this fix released?

Yes please try `0.5.0-dev.8`
