### ISSUE TITLE
🐞[Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @fb04536]

### ISSUE THREAD

**Issue by gangzhaorige** [fluttercommunity/flutter_workmanager#287]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  | 0.5.0-dev.4  |
| Xcode version        |      12.5         |
| Swift version        |       5      |
| iOS deployment target|       12      |

**Describe the error**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @fb04536

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en)
    • Flutter version 2.0.6 at /Users/ganaa/flutter
    • Framework revision 1d9032c7e1 (8 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ganaa/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 16.0.1+9-24)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.106
```

**Comment by ened** [comment]
@gangzhaorige You are using Java 16, which is not yet supported anywhere. Please use Java 11 as it's the currently supported Java version on Android.

**Comment by mjoji** [comment]
Hi

How do I "Use Java 11" in my flutter app? do you know where and how do I change this?
Thank you!

**Comment by chirag-eka** [comment]
> @gangzhaorige You are using Java 16, which is not yet supported anywhere. Please use Java 11 as it's the currently supported Java version on Android.

hey i tried this but i'm still getting the same error

**Comment by AjayShanker-geek** [comment]
I don't know how to change but you could remove Java 16 `(rm -rf /Library/Java/JavaVirtualMachines/jdk-16.jdk).`

Follow: [JDK Uninstallation Guide](https://docs.oracle.com/en/java/javase/16/install/installation-jdk-macos.html#GUID-F9183C70-2E96-40F4-9104-F3814A5A331F)

Check your version again after removing it by using `java -version` in terminal. Hope it helps :)

**Comment by mjoji** [comment]
Hi There. Yes. Removing Java version 16 worked. I also had to change my "JAVA_HOME" environment variable to point to the lower version of Java (in my case, version 8). Thank you so much for your help! Much appreciated

**Comment by saeidparvizi** [comment]
Using `flutter upgrade` in terminal.

**Comment by marchellodev** [comment]
Also, changing gradle version in gradle-wrapper properties to 7.1.1 (6.x does not support java 16), and adding the following line in gradle.properties (https://stackoverflow.com/questions/42667837/running-application-with-java-9-module-java-base-does-not-opens-java-io)
```
org.gradle.jvmargs=-Xmx1536M --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED

```
seems to solve the issue

**Comment by archi7** [comment]
@marchellodev solution worked for me.

**Comment by SeptiyanAndika** [comment]
@marchellodev thanks, solution worked for me.

**Comment by StephanCassel** [comment]
@marchellodev are my man  (only three hours in the bin)

**Comment by joanbric** [comment]
Thanks @marchellodev
You are the best. 👏

**Comment by veda2wratha** [comment]
@saeidparvizi  solution worked for me. Thank you

**Comment by stakkdev** [comment]
Solved same issue with following commands

cd /Applications/Android\ Studio.app/Contents/jre

ln -s ../jre jdk

ln -s "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" jdk

Clean and run it will work.

**Comment by jeanantoine** [comment]
The above solutions do not work for me.
I uninstalled Android Studio and Android SDK and reinstalled everything, without success.
Then I created a new Flutter project and copied the sources from the old one, and this time it worked.

**Comment by Sunshine2Smile** [comment]
i met the problem

**Comment by Sh-Labs-IsuruG** [comment]
@marchellodev Worked for me as well...Thank you 👍

**Comment by IsuruIG** [comment]
@marchellodev Worked for me as well...Thank you 👍

**Comment by felipe-novaes** [comment]
Same goes for me, solutions above does not work. I'm totally lost 'cause it works fine on IOS and suddenly i can't run the app on Android. 
I've checked all over and my guesses are indicating that some packages are causing this issue (like permission_handler and url_launcher)

**Comment by Quentinb** [comment]
@marchellodev worked for me as well (Mac M1 and React-Native)

**Comment by mihalycsaba** [comment]
only copying the sources to a new project works... there should be a tool that deletes all the unnecessary stuff and keeps the sources, because that resolved a lot of gradle issues for me.

**Comment by IonOlaru89** [comment]
For me upgrading to 

classpath 'com.android.tools.build:gradle:7.2.1'
from 
classpath 'com.android.tools.build:gradle:4.2.2'
WORKED

**Comment by Ritsz123** [comment]
> only copying the sources to a new project works... there should be a tool that deletes all the unnecessary stuff and keeps the sources, because that resolved a lot of gradle issues for me.

which files did you copy?

**Comment by Ritsz123** [comment]
> The above solutions do not work for me. I uninstalled Android Studio and Android SDK and reinstalled everything and upgraded Flutter, without success. Then I created a new Flutter project and copied the sources from the old one, and this time it worked.

can you name the files that you copied from new project?

**Comment by Ritsz123** [comment]
> The above solutions do not work for me. I uninstalled Android Studio and Android SDK and reinstalled everything and upgraded Flutter, without success. Then I created a new Flutter project and copied the sources from the old one, and this time it worked.

can you name the files that you copied from new project?

**Comment by namangupta01** [comment]
Changing the java version to 11 worked for me. Thanks @ened
