### ISSUE TITLE
🐞[Ios wont register one off task]

### ISSUE THREAD

**Issue by gangzhaorige** [fluttercommunity/flutter_workmanager#289]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.5.0-dev.4         |
| Xcode version        |      12.5      |
| Swift version        |       5      |
| iOS deployment target|       12        |

**Describe the error**
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(unhandledMethod("registerOneOffTask") error, Unhandled method registerOneOffTask, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      Workmanager.registerOneOffTask (package:workmanager/src/workmanager.dart:139:7)
<asynchronous suspension>
```

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en)
    • Flutter version 2.0.6 at /Users/ganaa/flutter
    • Framework revision 1d9032c7e1 (8 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ganaa/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 77E60B82-3C68-42BC-81AA-576152D41970 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114
```

**Comment by choepro577** [comment]
same problem with me. Hope to get it resolved

**Comment by Reymai** [comment]
I had the same issue, but I resole it.
```
/// top-level
/// Make sure it's return [Future<void>], is async and You [await] Workmanager()
Future<void> _registerNewIOSTask() async {
  await Workmanager().registerOneOffTask(
      Workmanager().hashCode.toString(), 'Background_auto_backup',
      tag: 'autobackup',
      initialDelay: EnvConfig.AUTO_BACKUP_DURATION,
      constraints: Constraints(
          networkType: NetworkType.connected, requiresStorageNotLow: true));
}

// class method
Future<void> start() async {
    await Workmanager().initialize(callbackDispatcher, isInDebugMode: true);
    if (Platform.isAndroid) {
      await Workmanager().registerPeriodicTask(
          '1', '123',
          tag: 'tag',
    } else {
      await _registerNewIOSTask();
    }
  }
  ```
  Hope it's can help

**Comment by Reymai** [comment]
I had the same issue, but I resole it.
```
/// Make sure it's return [Future<void>], is async and You await Workmanager()
Future<void> _registerNewIOSTask() async {
  await Workmanager().registerOneOffTask(
      '2', '234',
      tag: 'tag',
}

// class method
Future<void> start() async {
    await Workmanager().initialize(callbackDispatcher, isInDebugMode: true);
    if (Platform.isAndroid) {
      await Workmanager().registerPeriodicTask(
          '1', '123',
          tag: 'tag',
    } else {
      await _registerNewIOSTask();
    }
  }
```
Hope it can help

**Comment by sejun2** [comment]
Is this still not solved? If then I can't use this library for both platform right?

**Comment by cybex-dev** [comment]
I have the same problem specifically with iOS. 

**Summary:**
Call `initialize()` followed by `registerOneOffTask()` from [Flutter WorkManager Example App](https://github.com/fluttercommunity/flutter_workmanager/tree/main/example) project - no background activity takes place (while app in foreground or background).

**Tested on:**
 - iPhone 6s (physical device)
`no visible log output of any errors.`

 - iPhone 12 Pro Max (simulator) - see logs below:

After launching & clicking initialise, the following log output is vislble:
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running Xcode build...
Xcode build done.                                           11,4s
Debug service listening on ws://127.0.0.1:52593/VlfeQg6cInY=/ws
Syncing files to device iPhone 12 Pro Max...
```

After clicking `Perform a BG Task`, the following log output shows (error):

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.

This may be due to too many tasks being scheduled but not run.

See the error for details: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      Workmanager.registerOneOffTask (package:workmanager/src/workmanager.dart:185:7)
<asynchronous suspension>
```

**Only project changes:**
 1. project Team ID changed.
 2. `minimum OS deployment version` set to `10`.

**Environment Setup:**

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] Connected device (5 available)

• No issues found!
```

**Comment by AdamBridges** [comment]
> I have the same problem specifically with iOS.
> 
> **Summary:** Call `initialize()` followed by `registerOneOffTask()` from [Flutter WorkManager Example App](https://github.com/fluttercommunity/flutter_workmanager/tree/main/example) project - no background activity takes place (while app in foreground or background).
> 
> **Tested on:**
> 
> * iPhone 6s (physical device)
>   `no visible log output of any errors.`
> * iPhone 12 Pro Max (simulator) - see logs below:
> 
> After launching & clicking initialise, the following log output is vislble:
> 
> ```
> Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
> Warning: Missing build name (CFBundleShortVersionString).
> Warning: Missing build number (CFBundleVersion).
> Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
> Running Xcode build...
> Xcode build done.                                           11,4s
> Debug service listening on ws://127.0.0.1:52593/VlfeQg6cInY=/ws
> Syncing files to device iPhone 12 Pro Max...
> ```
> 
> After clicking `Perform a BG Task`, the following log output shows (error):
> 
> ```
> [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.
> 
> This may be due to too many tasks being scheduled but not run.
> 
> See the error for details: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"., null, null)
> #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
> #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
> <asynchronous suspension>
> #2      Workmanager.registerOneOffTask (package:workmanager/src/workmanager.dart:185:7)
> <asynchronous suspension>
> ```
> 
> **Only project changes:**
> 
> 1. project Team ID changed.
> 2. `minimum OS deployment version` set to `10`.
> 
> **Environment Setup:**
> 
> ```
> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-ZA)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.1)
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
> [✓] Connected device (5 available)
> 
> • No issues found!
> ```

I am also experiencing the same error on iOS with version `0.5.0-dev.7`. Were you able to correct the issue or is it still being investigated?

**Comment by ened** [comment]
The issue now contains 2 problems. Please re-open new tickets if you still encounter problems. 

Also, please use the latest prerelease `0.5.0-dev.8`.

**Comment by Binozo** [comment]
Problem still exists

**Comment by EA-YOUHOU** [comment]
Same issue : https://github.com/fluttercommunity/flutter_workmanager/issues/396

**Comment by luvishq** [comment]
Facing the same issue on iOS any updates on this @Binozo @ened @EArminjon2 ?

**Comment by Binozo** [comment]
> Facing the same issue on iOS any updates on this @Binozo @ened @EArminjon2 ?

Still same issue

**Comment by EArminjon** [comment]
> Facing the same issue on iOS any updates on this @Binozo @ened @EArminjon2 ?

Sée answer here : https://github.com/fluttercommunity/flutter_workmanager/issues/289#issuecomment-1143250887
