### ISSUE TITLE
On Callback Function I am getting this error

### ISSUE THREAD

**Issue by amaajid001** [fluttercommunity/flutter_workmanager#290]
I have written a http request in workmanager callback. Whenever this code run It give me this error on http request calling.
I want to save one entry periodically.
Could you please guide me how to solve this issue?

**HandshakeException (HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354)))**

**Comment by ened** [comment]
Please submit a sample project.
