### ISSUE TITLE
Workmanager not saving data to sqflite

### ISSUE THREAD

**Issue by amaajid001** [fluttercommunity/flutter_workmanager#294]
I am working on app in which i need to save data to sqlite periodically e.g after 30 minutes. When app is running then this plugin working fine data is saving in sqlite but when app is closed then workmanager not saving data to sqlite. I am stuck from many days. Please Help me to solve this issue if anybody knows about this. 

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |  ^0.3.0           |

flutter doctor -
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H512 darwin-x64, locale en-PK)
    • Flutter version 1.22.5 at /Users/student/Developer/flutter
    • Framework revision 7891006299 (7 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/student/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

**Comment by sukhcha-in** [comment]
Inside `callbackDispatcher` you have to initialize the plugin before executing any task inside `Workmanager().executeTask`.

**Comment by amaajid001** [comment]
> Inside `callbackDispatcher` you have to initialize the plugin before executing any task inside `Workmanager().executeTask`.


..
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({key}) : super(key: key);

  @override
  _MyApp createState() => _MyApp();
}

class _MyApp extends State<MyApp> {
  static final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  @override
  initState() {
    super.initState();
    // initialize background process
    Workmanager().initialize(
      callbackDispatcher,
      isInDebugMode: false,
    );

I wrote this on main file to initialize workmanager. Do i need to changes something?

**Comment by codermonk1** [comment]
f

> I am working on app in which i need to save data to sqlite periodically e.g after 30 minutes. When app is running then this plugin working fine data is saving in sqlite but when app is closed then workmanager not saving data to sqlite. I am stuck from many days. Please Help me to solve this issue if anybody knows about this.
> 
> **Version**
> 
> Technology	Version
> Workmanager version	^0.3.0
> flutter doctor - [✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H512 darwin-x64, locale en-PK) • Flutter version 1.22.5 at /Users/student/Developer/flutter • Framework revision 7891006299 (7 months ago), 2020-12-10 11:54:40 -0800 • Engine revision ae90085a84 • Dart version 2.10.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3) • Android SDK at /Users/student/Library/Android/sdk • Platform android-30, build-tools 30.0.3 • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495) • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5) • Xcode at /Applications/Xcode.app/Contents/Developer • Xcode 11.5, Build version 11E608c • CocoaPods version 1.10.1
> 
> [!] Android Studio (version 4.1) • Android Studio at /Applications/Android Studio.app/Contents ✗ Flutter plugin not installed; this adds Flutter specific functionality. ✗ Dart plugin not installed; this adds Dart specific functionality. • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.57.1) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.24.0
> 
> [✓] Connected device (1 available) • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
> 
> ! Doctor found issues in 1 category.

first of all you have to checked whether your app is running in background or not ,  if running then put break point on callbackdispatcher. and see the process

**Comment by ened** [comment]
More details are needed in order to provide support. Also, please ensure to follow the suggestions on this thread and provide success AND failure logs.
