### ISSUE TITLE
The binary version of its metadata is 1.5.1, expected version is 1.1.15.

### ISSUE THREAD

**Issue by amaajid001** [fluttercommunity/flutter_workmanager#300]
WorkmanagerPlugin.kt: (50, 31): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. **The binary version of its metadata is 1.5.1, expected version is 1.1.15.**

After updating flutter 2 i am getting this error while launching the app.

**Comment by duckprogrammerr** [comment]
android/build.gradle

write ext.kotlin_version = '1.4.32' ;
its worked with me

**Comment by amaajid001** [comment]
Thanks its working.

**Comment by sejun2** [comment]
Thank you! It works!
