### ISSUE TITLE
Working with flutter_reactive_ble

### ISSUE THREAD

**Issue by yo80106** [fluttercommunity/flutter_workmanager#301]
Recently, I am trying to connect my Flutter app with an Arduino device through BLE. Everything had been working perfectly in the foreground until I tried to make the connection in the background. I use the [flutter_reactive_ble plugin](https://pub.dev/packages/flutter_reactive_ble) to handle the BLE connection. I put the BLE scanning and connection in the callback dispatcher. After I initialized FlutterReactiveBle in the callback dispatcher, I can get the updated BLE status (first line of the code `print(_ble.status);`). The status is unknown. However, the rest of the BLE code seems not working because none of any print statements is executed within the block. It seems like the workmanager run through the codes without waiting for the functions to scan and connect.

```
print(_ble.status);
_subscription = _ble.scanForDevices(
    withServices: [serviceID],
    scanMode: ScanMode.lowLatency,
    requireLocationServicesEnabled: false).listen((device) {
      print(device.name);
  if (device.name == 'PersonDetection') {
    print('PersonDetection found!');
    _connection = _ble
        .connectToDevice(
      id: device.id,
      connectionTimeout: const Duration(seconds: 5),
    )
        .listen((connectionState) async {
      // Handle connection state updates
      print(device.name);
      print(device.id);
      print('connection state:');
      print(connectionState.connectionState);
      if (connectionState.connectionState ==
          DeviceConnectionState.connected) {
        final characteristic = QualifiedCharacteristic(
            serviceId: serviceID,
            characteristicId: characteristicsID,
            deviceId: device.id);
        final response = await _ble.readCharacteristic(characteristic);
        print(response);
        _disconnect();
        print('disconnected');
      }
    }, onError: (dynamic error) {
      // Handle a possible error
      print(error.toString());
    });
  }
}, onError: (error) {
  print('error!');
  print(error.toString());
});

```

**Comment by ened** [comment]
`flutter_workmanager` is not suited for background BLE work. This is something the BLE plugins should implemented themselves.

**Comment by heedongrichrich** [comment]
> `flutter_workmanager` is not suited for background BLE work. This is something the BLE plugins should implemented themselves.

Hi, I am currently implementing a bluetooth background using ios core-bluetooth. I am looking for a way to send data from native to flutter dart in background mode.
Is this package is suitable for this job? I don't know where to ask this question so I write here. 

If I am wrong, please let me know :)

**Comment by robertherber** [comment]
@ened I'm curious as to why this library wouldn't work with a general-purpose Bluetooth library?

> `flutter_workmanager` is not suited for background BLE work. This is something the BLE plugins should implemented themselves.

I'm curious as to why it's not suited for BLE work?

**Comment by ened** [comment]
Background tasks have a finite life span and are under OS management regarding their lifecycle. They may run at any time (or not at all), it depends on the OS. See https://www.dontkillmyapp.com for typical issues.

BLE connections are long-lived, and if not long lived then for sure are running for an infinite amount. Consider delays, retries etc. You want to keep your application running in the background while the connection is active. This is a different use case. It requires a background (foreground on new versions) service on Android and iOS can manage this for you using the CoreBluetooth framework.

**Comment by abdaltintop** [comment]
> > `flutter_workmanager` is not suited for background BLE work. This is something the BLE plugins should implemented themselves.
> 
> Hi, I am currently implementing a bluetooth background using ios core-bluetooth. I am looking for a way to send data from native to flutter dart in background mode. Is this package is suitable for this job? I don't know where to ask this question so I write here.
> 
> If I am wrong, please let me know :)

This is what i was looking for, have you found a solution for this? i have implemented a bluetooth background using ios core-bluetooth, and native side works correctly. But I have problems with sending data from native to flutter dart in background mode. i will appreciate if you have an answer to this.
