### ISSUE TITLE
Where is the command to execute the background task directly for emulator?

### ISSUE THREAD

**Issue by anass-naoushi** [fluttercommunity/flutter_workmanager#303]
There used to be a command in the readme doc about executing the periodic task rather than waiting for 15 minutes every time. Where do I find it?

**Comment by Maxmontgelas** [comment]
e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"workmanager.background.task"]

**Comment by EA-YOUHOU** [comment]
@Maxmontgelas  where run this command ? It didn't work inside terminal
