### ISSUE TITLE
is there any way to perform certain operations using flutter plugins  in work manager periodic task execution?

### ISSUE THREAD

**Issue by AkhilSajiCodzoc** [fluttercommunity/flutter_workmanager#304]
suppose i have to do a task to setwallpaper in periodically, Then can i use this plugin ?Means i have implemented periodic task in work manager ,but its only shows print statements in debug mode.Its doesnt executes my setwallpaper flutter code (i dont know much more about this plugin).My question is that can i use  plugins to do some  functions like wallpaper changer in work manager.[my purpose is change wallpaper in 24 hours]

**Comment by codermonk1** [comment]
yes

**Comment by ened** [comment]
Probably yes on android, most likely NO on iOS.

**Comment by darshanpopat80802** [comment]
@ened How can I perform certain operations in work manager periodic task ?

**Comment by codermonk1** [comment]
// void callbackDispatcher() {
//   Workmanager().executeTask((task, inputData) async {
DO YOUR TASK HERE
//     return Future.value(true);
//   });
// }

this should be add on main.dart file and then in call

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Workmanager().initialize(callbackDispatcher);
  // Workmanager().registerPeriodicTask(
  //   "1",
  //   "uniqueKey",
  //   frequency: Duration(minutes: 60),
  // );
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    home: splash_screen(),
  ));
}
