### ISSUE TITLE
Facing 'No Firebase App has been created' while uploading to Firebase Storage

### ISSUE THREAD

**Issue by kamalbanga** [fluttercommunity/flutter_workmanager#315]
I want to collect user browsing data for offline backend analysis for a Flutter app.
What I am planning to do is run a daily cron on the app that uploads it using the WorkManager package.

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  Workmanager().initialize(uploadUserData, isInDebugMode: true);
  Workmanager()
      .registerOneOffTask('1', 'task1', initialDelay: Duration(seconds: 10));
  runApp(MyApp());
}

void uploadUserData() {
  Workmanager().executeTask((task, inputData) {
    firebase_storage.FirebaseStorage.instance
        .ref('/uploads/test_workmanager.txt')
        .putString('workmanager test');
    return Future.value(true);
  });
}
```

I am facing the following issue while running the above code

> E/BackgroundWorker( 6733): errorCode: error, errorMessage: [core/no-app] *No Firebase App '[DEFAULT]' has been created* - call Firebase.initializeApp()
> I/WM-WorkerWrapper( 6733): Worker result FAILURE for Work [ id=81642715-826f-4d40-b8ec-9d86eab75136, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]

I have checked in multiple ways that firebase is initialized before calling the workmanager task (using firebase.apps.length & .whenComplete). Basically everything just works if I just call `firebase_storage....putString` in the `main()` instead of within `Workmanager().executeTask`.

---

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |   0.4.1         |
| Flutter        |        2.5.0       |

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-IN)
    • Flutter version 2.5.0 at /Users/.../Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
```

**Comment by ened** [comment]
You need to initialise the FB App in the workmanager dispatcher.

```
void uploadUserData() {
  Workmanager().executeTask((task, inputData) async {
    await Firebase.initializeApp();
    firebase_storage.FirebaseStorage.instance
        .ref('/uploads/test_workmanager.txt')
        .putString('workmanager test');
    return Future.value(true);
  });
}
```

**Comment by kamalbanga** [comment]
@ened I have tried that and it still doesn't work.

**Comment by kamalbanga** [comment]
@ened Hey could you please re-open the issue.

**Comment by ened** [comment]
From the code posted above, the `firebase_storage` variable May not be set correctly.

I can not help you unless you submit a detailed stack trace and sample project perhaps. Thank you, Seb

**Comment by VilleKylmamaa** [comment]
1. Call `await Firebase.initializeApp();` in `Workmanager().executeTask() async { }`.

2. I recommend awaiting all Firebase actions in the Workmanager task: `await firebase_storage.FirebaseStorage.instance.[...]`. This is because without `await`, the Workmanager might consider the task finished and kill the process before the Firebase action finishes.

Full Workmanager example task code with changes:

```
Workmanager().executeTask((task, inputData) async {
  await Firebase.initializeApp();
  await firebase_storage.FirebaseStorage.instance
      .ref('/uploads/test_workmanager.txt')
      .putString('workmanager test');
  return Future.value(true);
});
```

**Comment by gotnull** [comment]
Still occurring on my end as well...
