### ISSUE TITLE
periodic task stopes after hours

### ISSUE THREAD

**Issue by AkhilSajiCodzoc** [fluttercommunity/flutter_workmanager#319]
i just tried to do some task periodically using work manager.its working fine.but after few hours the task will not runs. i have already  turned ON auto start option and turned OFF battery optimisation . I just tried in stock android mobiles, we can get similar thing there too.this is usually happens when user doesn't take his phone too long.

**Comment by ened** [comment]
This probably needs a few more details, like the phone model and OS version.

I would suggest to check https://dontkillmyapp.com first and follow the instructions. If that fixes your problems, perhaps workmanager is not the right choice for your task.

**Comment by dfourcfive** [comment]
@ened  is there an alternative way to execute a background task periodically ?

**Comment by AkhilSajiCodzoc** [comment]
@dfourcfive  you can use Android Alarm Manager plus to do suck kind of task.But this will not work in Ios.

**Comment by dfourcfive** [comment]
@AkhilSajiCodzoc if it works without depending on the autostart   thing its would be fine as a start
