### ISSUE TITLE
🐞[Can't build iOS with workmanager Plugin]

### ISSUE THREAD

**Issue by nino-finch** [fluttercommunity/flutter_workmanager#323]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     0.4.1          |
| Xcode version        |     12.5.1          |
| Swift version        |       5.2        |
| iOS deployment target|      10.0         |

**Building works on Android but while building in iOS I got an error complaining that it couldn't find 'UNNotificationRequest'.**

Here's the full stacktrace:

/Users/thomasaquinasnugrahabudi/.pub-cache/hosted/pub.dartlang.org/workmanager-0.4.1/ios/Classes/DebugNotificationHelper.swift:56:169: error: 'UNNotificationRequest' is only available in iOS 10.0 or newer private static func createNotificationRequest(identifier: String, threadIdentifier: String, title: String, body: String, icon: ThumbnailGenerator.ThumbnailIcon) -> UNNotificationRequest { ^ /Users/thomasaquinasnugrahabudi/.pub-cache/hosted/pub.dartlang.org/workmanager-0.4.1/ios/Classes/DebugNotificationHelper.swift:56:25: note: add @available attribute to enclosing static method private static func createNotificationRequest(identifier: String, threadIdentifier: String, title: String, body: String, icon: ThumbnailGenerator.ThumbnailIcon) -> UNNotificationRequest { ^ /Users/thomasaquinasnugrahabudi/.pub-cache/hosted/pub.dartlang.org/workmanager-0.4.1/ios/Classes/DebugNotificationHelper.swift:11:8: note: add @available attribute to enclosing struct struct DebugNotificationHelper {

I have set my deployment target on my Podfile to iOS 10
platform :ios, '10.0'

Does anyone ever run into this issue before? Not sure what's going on but this issue preventing us from even building the iOS app right now.

**Output of `flutter doctor -v`**
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/thomasaquinasnugrahabudi/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/thomasaquinasnugrahabudi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPhone 8 Plus (mobile) • 4990E2C7-C747-41D1-A1A7-CC0E317DC573 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.82

**Comment by nino-finch** [comment]
NVM I found the reason of the issue. Flutter post-script build forced the build target back to 9.0. After I fixed that part the build works again

**Comment by xalikoutis** [comment]
@nino-finch I have the same problem, where can i find the Flutter post-script build
