### ISSUE TITLE
🐞BUILD FAILED in 1m 47s Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by codermonk1** [fluttercommunity/flutter_workmanager#328]
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.4.1\android\src\main\kotlin\be\tramckrijte\workmanager\WorkmanagerPlugin.kt: (47, 10): Class 'kotlin.ReplaceWith' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar!/kotlin/ReplaceWith.class
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.4.1\android\src\main\kotlin\be\tramckrijte\workmanager\WorkmanagerPlugin.kt: (47, 10): Class 'kotlin.DeprecationLevel' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

The class is loaded from ../.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar!/kotlin/DeprecationLevel.class
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.4.1\android\src\main\kotlin\be\tramckrijte\workmanager\WorkmanagerPlugin.kt: (48, 10): Class 'kotlin.jvm.JvmStatic' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from C:/Users/Brijbhan Singh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar!/kotlin/jvm/JvmStatic.class

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.4.1\android\src\main\kotlin\be\tramckrijte\workmanager\WorkmanagerPlugin.kt: (50, 31): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from C:/Users/Brijbhan Singh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':workmanager:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by Bes79** [comment]
> Update Kotlin version solved this issue. Flutter default Kotlin version is `1.3.50` right now (In flutter version 2.5.2). WorkManger uses Kotlin version `1.5.10` which makes it incompatible with your app. You need to update your app's Kotlin version. From android>build.gradle update line `ext.kotlin_version = '1.3.50'` to `ext.kotlin_version = '1.4.32'` which makes WorkManager work and doesn't breaks other things

this work for me, thanks

**Comment by codermonk1** [comment]
> This solution did not work for me :( Kindly help at #334

if this not work then rebuild your project 
go to your terminal 
flutter clean
after clean 
then flutter pub get

then build your project
if this not work then send error report

**Comment by kvernon93** [comment]
I tried that but didn't work, what resolved the issue for me was that I removed the package along with flutter_local_notifications, ran the project, put the package back and then it worked.
