### ISSUE TITLE
Migrate to Federated Design

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [fluttercommunity/flutter_workmanager#330]
We should eventually support other platforms and in the process migrate this repo to Federated Plugin design.

See here for more about federated design: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin

See here for an example of migrating an existing plugin using MethodChannel to Platform Interface: https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6

**Comment by ened** [comment]
@ChristianEdwardPadilla PRs welcome.

**Comment by ened** [comment]
Taking some notes for myself: 

```
flutter create -t plugin --platforms ios,android,macos  --org be.tramckrijte --project-name workmanager .
```

**Comment by alexbejann** [comment]
Hi @ened, is this task relevant? I can make a PR for it

**Comment by ChristianEdwardPadilla** [comment]
The plus_plugins of the fluttercommunity ended up reverting their federation, see: https://github.com/fluttercommunity/plus_plugins/issues/1226.

I do not understand their CI-related rationale or whether it would be relevant to the flutter_workmanager plugin, but it's possible that this issue is no longer useful.

**Comment by alexbejann** [comment]
Hey @ChristianEdwardPadilla, 
I looked briefly through the comments and their issue, but I am not 100% sure if this would be the case for flutter_workmanager. I have to dive a bit further, but this will be only during weekend. If this is not relevant anymore, I would suggest closing the issue and I will pick something else.
