### ISSUE TITLE
Periodic background tasks on IOS

### ISSUE THREAD

**Issue by Musie-ebuy** [fluttercommunity/flutter_workmanager#336]
Hi Flutter community, 
I have implemented a periodic background tasks(using the WorkManger plugin) which should run daily (or nearly daily) using flutter for an IOS device.
I have tested the background task in Android device and they work correctly. But in IOS they are not running even close to the frequency they are supposed to. In the flutter documentation I see that, in IOS, the WorkManger for background tasks still does not support implementation of periodic tasks. 
Do you know any alternative solution(or possible workaround) for this issue? or do you think Flutter will make this this feature available soon?

thank you,
Musie Ebuy

**Comment by aliaksei-pakaliuk** [comment]
@Musie-ebuy you can use https://pub.dev/packages/background_fetch plugin

**Comment by ened** [comment]
Periodic tasks are not supported in iOS. You can use the `Workmanager.iOSBackgroundTask` key to get a chance to execute once a day, but it depends on the OS configuration. You can also schedule work on a one-by-one basis (see the APIs in `0.5.0-dev.8`).

**Comment by jarodtang** [comment]
> Periodic tasks are not supported in iOS. You can use the `Workmanager.iOSBackgroundTask` key to get a chance to execute once a day, but it depends on the OS configuration. You can also schedule work on a one-by-one basis (see the APIs in `0.5.0-dev.8`).

How can I do a "You can also schedule work on a one-by-one basis"? I found it executed while in changing, but never called without charging
