### ISSUE TITLE
Not rescheduling after phone restart

### ISSUE THREAD

**Issue by pluzmedia** [fluttercommunity/flutter_workmanager#344]
Hi,

MY existing jobs are not rescheduling after phone restart. Below is my AndroidManifest.xml configuration
`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`

```
<service
            android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmService"
            android:enabled="true"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:process=":remote" />
```
        <receiver
            android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmBroadcastReceiver"
            android:exported="false" />
        <receiver
            android:name="dev.fluttercommunity.plus.androidalarmmanager.RebootBroadcastReceiver"
            android:enabled="false"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
`

**Comment by ened** [comment]
Looks like this is for another project, not for `flutter_workmanager`. Please read the docs for `WM` itself if you see jobs not restarting. https://developer.android.com/reference/androidx/work/WorkManager?hl=en
