### ISSUE TITLE
Not Working on iOS

### ISSUE THREAD

**Issue by umerbutt03** [fluttercommunity/flutter_workmanager#346]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     ^0.4.1          |
| Xcode version        |        13.1       |
| Swift version        |        5.5.1       |
| iOS deployment target|        10.0       |

**Describe the error**
It gives error, when I register the preodic task.

  Workmanager().registerPeriodicTask(
    "1",
    rescheduledTaskKey,
    inputData: <String, dynamic>{
      'key': Random().nextInt(64000),
    },
    frequency: const Duration(minutes: 15),
  );

ERROR: [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      Workmanager.registerPeriodicTask (package:workmanager/src/workmanager.dart:173:7)
<asynchronous suspension>

**Output of `flutter doctor -v`**

[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/umerbutt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/umerbutt/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Users/umerbutt/Desktop/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/umerbutt/Desktop/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/umerbutt/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • D1BE1A59-4692-4B84-96D8-6351C97E78B9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

**Comment by gwennguihal** [comment]
registerPeriodicTask only for Android only.

**Comment by umerbutt03** [comment]
> registerPeriodicTask only for Android.

How it will be workable on iOS?

**Comment by mehransahandi** [comment]
I also Have the same problem, when I send the background-fetch from Xcode it works but then it never fire by itself

**Comment by MrVipinVijayan** [comment]
Same here. Even sample app doesn't work.
iOS 15.2

**Comment by dvu714** [comment]
I'm having the same issue on IOS 15.2.  Sending background fetch from Xcode works, but my callback never gets called when running on the device.

**Comment by ened** [comment]
`registerPeriodicTask` is not supported on iOS. 

Please also attempt to use the latest pre-release version, `0.5.0-dev.8`.

**Comment by delizondo** [comment]
> I used the sample example code, I also Have the same problem, when I send the background-fetch from Xcode it works but then it never fire by itself how should we fix this ?any Idea ?

Same situation here. 
After some research found the following. 

Latest version of workmanager is `0.5.0-dev.8`, which uses [BGAppRefreshTask](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask) for iOS.

Now, during the installation instructions for workmanager in iOS we need to register the identifier in the `info.plist` file

```
<key>BGTaskSchedulerPermittedIdentifiers</key>
<array>
	<string>workmanager.background.task</string>
</array>
```

Now, in [this](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app) link, explains how to setup the `BGAppRefreshTask` in iOS, and what catch my attention is this part: 

``` 
In iOS 13 and later, adding a BGTaskSchedulerPermittedIdentifiers key to the Info.plist disables the
[application(_:performFetchWithCompletionHandler:)] and [setMinimumBackgroundFetchInterval(_:)] methods.
``` 

And that would explain why the background fetch works if launched manually in iOS never fires itself

**Comment by delizondo** [comment]
@ened  please reopen this bug, as there's some changes needs to be done in the iOS part

**Comment by ened** [comment]
> @ened  please reopen this bug, as there's some changes needs to be done in the iOS part
> 
> 

The issue is about periodic tasks, not the behavior of the new plug-in version. As such, we will keep it closed. 

Please open a new ticket as needed, it seems that is more appropriate. (The problem seems documentation related, too).
