### ISSUE TITLE
🐞Cannot run android native function in task

### ISSUE THREAD

**Issue by sri-vathsa** [fluttercommunity/flutter_workmanager#349]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have ran the sample app and it works there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |          0.4.1     |

**Describe the error**
Context: I have a use case where I have to execute some native android code as a task and I am working on android only application.

I created my app with the code from the example on this [repo](https://github.com/fluttercommunity/flutter_workmanager/blob/a65356d8bb3aa19b63c7ec800d94379f6df80492/example/lib/main.dart#L22). 

Then I added code to call native android functions using the java code [here](https://docs.flutter.dev/development/platform-integration/platform-channels?tab=android-channel-java-tab).

I have tested both of them(work manager tasks and android native) independently and both of them are working perfectly as expected.

So then I added ```await platform.invokeMethod('testMethod')``` to the tasks under `simpleTaskKey` (https://github.com/fluttercommunity/flutter_workmanager/blob/a65356d8bb3aa19b63c7ec800d94379f6df80492/example/lib/main.dart#L22) in work manager to call the native android method and it fails with the error.
```
MissingPluginException(No implementation found for method testMethods on channel samples.flutter.dev/battery)
``` 
To keep things simple I am simply returning a string without any other function calls on the `testMethod`.

Is work manager not compatible with invoking platform-specific code?
Can someone please help me out with this?

**Output of `flutter doctor -v`**
No errors shown on running `flutter doctor -v`

**Comment by marchellodev** [comment]
Facing the exact same problem

**Comment by marchellodev** [comment]
Seems to be related to #305 #255 #6

**Comment by ened** [comment]
@sri-vathsa please try calling to a standard plugin to verify the function. The message `MissingPluginException(No implementation found for method testMethods on channel ...`  in your case may point to incomplete implementation on native side.

**Comment by dollyvindane** [comment]
facing the same issue. is workmanager unable to invoke native apis?
