### ISSUE TITLE
[Question] Run task based on battery percentage?

### ISSUE THREAD

**Issue by BlackBearFTW** [fluttercommunity/flutter_workmanager#353]
Is it possible to run the background task based on the battery percentage of the phone?

Use Case:
We are building an app and we would like to send the user a notification when their battery has an x amount of percentage in it, the notification will warn them that their battery is almost empty and that they should go to one of our charging points nearby.

**Comment by ened** [comment]
https://developer.android.com/reference/androidx/work/Constraints?hl=en - no such API exists.
Workmanager (and iOS) equivalent code offer APIs to do work when battery is _not_ low.
