### ISSUE TITLE
🐞The callbackDispatcher needs to be either a static function or a top level function to be accessible as a Flutter entry point.

### ISSUE THREAD

**Issue by remymumoh** [fluttercommunity/flutter_workmanager#364]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      ^0.4.1         |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
Describe error
How can I use the work-manager in another class, apart from the main.dart class? I Have tried the implementation below I end up getting the error  

> Failed assertion: line 110 pos 12: 'callback != null': The callbackDispatcher needs to be either a static function or a top level function to be accessible as a Flutter entry point.

Any tips or tricks on how to call it from any State class 
Optionally provide the least amount of code that shows this behaviour. Ideally in the `sample` app.
```
class WAHomeScreen extends StatefulWidget {
  static String tag = '/WAHomeScreen';

  @override
  WAHomeScreenState createState() => WAHomeScreenState();
}

class WAHomeScreenState extends State<WAHomeScreen> {

@override
  void initState() {
    super.initState();
    init();
    initStateAsync();
    
  }

  void initStateAsync() async {
    await Workmanager().initialize(callbackDispatcher,
        isInDebugMode:
        true); //to true if still in testing lev turn it to false whenever you are launching the app
    await Workmanager().registerPeriodicTask("5", simplePeriodicTask,
        existingWorkPolicy: ExistingWorkPolicy.replace,
        frequency: const Duration(minutes: 15),
        //when should it check the link
        initialDelay: const Duration(seconds: 5),
        //duration before showing the notification
        constraints: Constraints(
          networkType: NetworkType.connected,
        ));
  }

  void callbackDispatcher() {
    Workmanager().executeTask((task, inputData) async {

}
}

```
**Output of `flutter doctor -v`**
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
    • Flutter version 2.10.2 at D:\FlutterSDk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (7 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.31829.152
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\rngei\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by banderberg** [comment]
I think your callback needs to be either top-level or static.

**Comment by ened** [comment]
Move the `callbackDispatcher` function out of the class, so that it becomes `a static function or a top level function to be accessible as a Flutter entry point`.
