### ISSUE TITLE
🐞Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by daviddagan** [fluttercommunity/flutter_workmanager#376]
version: ^0.4.1

on every android 31 SDK (android 12 )

app crashes like hell!!!

Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(15430): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime(15430): Process: com.example.fucking_fuck_fuck, PID: 15430
E/AndroidRuntime(15430): java.lang.IllegalArgumentException: com.example.fucking_fuck_fuck: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(15430): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(15430): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(15430): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime(15430): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
lib\main.dart:1
Warning: Mapping new ns [http://schemas.android.com/repository/android/common/02]() to old ns [http://schemas.android.com/repository/android/common/01]()
E/AndroidRuntime(15430): 	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
E/AndroidRuntime(15430): 	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
E/AndroidRuntime(15430): 	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
E/AndroidRuntime(15430): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
E/AndroidRuntime(15430): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(15430): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(15430): 	at java.lang.Thread.run(Thread.java:920)

**Comment by TheCarpetMerchant** [comment]
Bumping this ! This makes the app unusable on Android 12 !

**Comment by mafkaroo** [comment]
Also workaround is adding this to app/build.gradle dependencies

implementation 'androidx.work:work-runtime-ktx:2.7.1'

**Comment by ened** [comment]
Version 0.5.0 will be released today.

**Comment by desmeit** [comment]
I installed 0.4.1 as well because the new version 0.5.0 only runs with SDK

`>=2.11.0`

I had the same error as above and tried it with 
`implementation 'androidx.work:work-runtime-ktx:2.7.1'`

and it works, but I have a new error now:

`Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver de.appname.app.BootReceiver: java.lang.ClassNotFoundException: Didn't find class "de.appname.app.BootReceiver"`
