### ISSUE TITLE
🐞 [iOSBackgroundProcessingTask is not triggered.]

### ISSUE THREAD

**Issue by DanhDue** [fluttercommunity/flutter_workmanager#377]
I have done the setup for both Android & iOS. But when I run the snippet below on my iPhone(software version: 15.3.1) the Workmanager.iOSBackgroundProcessingTask is not triggered.

`
Workmanager().registerOneOffTask(
   "1",
   "simpleTaskKey",
   initialDelay: const Duration(seconds: 15),
   constraints: Constraints(networkType: NetworkType.connected)
);
`

I also have done the setup for the BGTaskScheduler and the Background Fetch and then I have tested 2 methods on XCode. They've worked.
1. Run app and execute this command: 
`e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"workmanager.background.task"]`
2. Debug → Simulate Background Fetch.

- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       ^0.5.0-dev.8        |
| Xcode version        |        13.3       |
| Swift version        |       5.6        |
| iOS deployment target|        10.0       |

**Describe the error**
Describe error
Optionally provide the least amount of code that shows this behaviour. Ideally in the `sample` app.

**Output of `flutter doctor -v`**

➜  solarcoin git:(workmanager) ✗ fvm flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale en-VN)
    • Flutter version 2.10.4 at /Users/danhdueexoictif/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/danhdueexoictif/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/danhdueexoictif/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by neeluagrawal04** [comment]
I am also getting the exception in ios:
Unhandled Exception: PlatformException(unhandledMethod("registerOneOffTask") error, Unhandled method registerOneOffTask, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      Workmanager.registerOneOffTask (package:workmanager/src/workmanager.dart:139:7)
<asynchronous suspension>

**Comment by chunlee-thong** [comment]
I also encounter this error. Nothing happen

**Comment by neeluagrawal04** [comment]
Also while fetching any data from getStorage inside worker getting this plugin exception and value always return as null.

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (18411): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:47:7)
E/flutter (18411): <asynchronous suspension>
E/flutter (18411): #1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:28:7)
E/flutter (18411): <asynchronous suspension>

**Comment by chunlee-thong** [comment]
@neeluagrawal04 Your issue might relate to #366. This issue is related to iOS only

**Comment by neeluagrawal04** [comment]
> I also encounter this error, Nothing happens. Working when debugging with Xcode.

yes working via same but how to distinguish for multiple worker task in ios as in Android we can add the differentiation via case and taskName. How we can differentiate and run that particular task on tigger of any button in ios?

**Comment by neeluagrawal04** [comment]
> @neeluagrawal04 Your issue might relate to #366. This issue is related to iOS only

it works and remove the exception but getting null value when getting the data from GetStorage inside worker task. Any solution for it?

**Comment by chunlee-thong** [comment]
After few research and clearly read to doc, iOSBackgroundProcessingTask can't be happen immediately. It has an interval of minimum of 15min

**Comment by ened** [comment]
I'm closing the issue for now - please @DanhDue could you retest with `0.5.0`.

**Comment by EA-YOUHOU** [comment]
@chunlee-thong you are confusing background fetch (BGTaskScheduler:  iOSBackgroundTask) and background processing (BGTaskScheduler: iOSBackgroundProcessingTask).

**Comment by brightchip** [comment]
How to running this as foreground service on iOS like this plugin: https://pub.dev/packages/flutter_foreground_task
The plugin works on Android but never ran on iOS
