### ISSUE TITLE
Getting Platform exception while implementing and running app in ios

### ISSUE THREAD

**Issue by neeluagrawal04** [fluttercommunity/flutter_workmanager#380]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     0.4.1          |
| Xcode version        |     13.2.1          |
| Swift version        |       swift 5        |
| iOS deployment target|     15          |

**Describe the error**
Describe error
On running the sample app on ios device getting the Platform exception

**Output of `flutter doctor -v`**

2022-05-06 13:11:16.244540+0530 Runner[3786:416002] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)

Please fix this issue for ios

**Comment by neeluagrawal04** [comment]
Any updates on this because this work manager is not working in ios device as well. But working fine on android.
So if the plugin does not support ios then why the support for both android/ios is mentioned in documentation?
Please revert asap i am stucked on it.

**Comment by EA-YOUHOU** [comment]
@neeluagrawal04  ?
