### ISSUE TITLE
  await Workmanager().registerPeriodicTask causes crash in Android 12

### ISSUE THREAD

**Issue by sudhi001** [fluttercommunity/flutter_workmanager#394]
E/AndroidRuntime(11132): kotlin.UninitializedPropertyAccessException: lateinit property sensorEventListener has not been initialized
E/AndroidRuntime(11132): 	at dev.fluttercommunity.plus.sensors.StreamHandlerImpl.onCancel(StreamHandlerImpl.kt:26)
E/AndroidRuntime(11132): 	at dev.fluttercommunity.plus.sensors.SensorsPlugin.teardownEventChannels(SensorsPlugin.kt:69)
E/AndroidRuntime(11132): 	at dev.fluttercommunity.plus.sensors.SensorsPlugin.onDetachedFromEngine(SensorsPlugin.kt:28)
E/AndroidRuntime(11132): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime(11132): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
E/AndroidRuntime(11132): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
E/AndroidRuntime(11132): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)

**Comment by ened** [comment]
Unrelated to this plugin.
