### ISSUE TITLE
ResolvableFuture can only be called from within the same library group prefix

### ISSUE THREAD

**Issue by Inferno-Team** [fluttercommunity/flutter_workmanager#399]
Execution failed for task ':workmanager:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:

  C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.5.0\android\src\main\kotlin\be\tramckrijte\workmanager\BackgroundWorker.kt:59: Error: ResolvableFuture can only be called from within the same library group prefix (referenced groupId=androidx.concurrent with prefix androidx from groupId=be.tramckrijte.workmanager) [RestrictedApi]
      private val resolvableFuture = ResolvableFuture.create<Result>()
                                     ~~~~~~~~~~~~~~~~
  C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.5.0\android\src\main\kotlin\be\tramckrijte\workmanager\BackgroundWorker.kt:132: Error: ResolvableFuture.set can only be called from within the same library group prefix (referenced groupId=androidx.concurrent with prefix androidx from groupId=be.tramckrijte.workmanager) [RestrictedApi]
              resolvableFuture.set(result)
                               ~~~



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10m 33s
1057 actionable tasks: 143 executed, 914 up-to-date

**Comment by Tahahalabi** [comment]
Is there any update?

**Comment by ened** [comment]
Hi @Tahahalabi & @Inferno-Team there's a PR addressing this. Are you interested in testing the change?

**Comment by patriciatrauman** [comment]
Hello,

I use workmanager: ^0.5.2
And I get the same err or I guess when I've thoses logs.
Below, you'll see all the dependancies I use, my gradle et flutter version .
Any suggestion on how fix or workaround this issue ?

> Task :workmanager:lintDebug FAILED
> Lint found 1 errors, 4 warnings. First failure:
> 
> .pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/DebugHelper.kt:17: Error: Success can only be accessed from within the same library group (referenced groupId=androidx.work from groupId=dev.fluttercommunity.workmanager) [RestrictedApi]
>             is ListenableWorker.Result.Success -> "\uD83C\uDF89"
>                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>    Explanation for issues of type "RestrictedApi":
>    This API has been flagged with a restriction that has not been met.
> 
>    Examples of API restrictions:
>    * Method can only be invoked by a subclass
>    * Method can only be accessed from within the same library (defined by the
>    Gradle library group id)
>    * Method can only be accessed from tests.
> 
>    You can add your own API restrictions with the @RestrictTo annotation.
> 
> 
> The full lint text report is located at:
>   ....build/workmanager/intermediates/lint_intermediate_text_report/debug/lintReportDebug/lint-results-debug.txt
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':workmanager:lintDebug'.
> > Lint found errors in the project; aborting build.
>   
>   Fix the issues identified by lint, or create a baseline to see only new errors.
>   To create a baseline, run `gradlew updateLintBaseline` after adding the following to the module's build.gradle file:
>   ```
>   android {
>       lint {
>           baseline = file("lint-baseline.xml")
>       }
>   }
>   ```
>   For more details, see https://developer.android.com/studio/write/lint#snapshot
>   
>   Lint found 1 errors, 4 warnings. First failure:
>   
> .../.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/DebugHelper.kt:17: Error: Success can only be accessed from within the same library group (referenced groupId=androidx.work from groupId=dev.fluttercommunity.workmanager) [RestrictedApi]
>               is ListenableWorker.Result.Success -> "\uD83C\uDF89"
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   
>      Explanation for issues of type "RestrictedApi":
>      This API has been flagged with a restriction that has not been met.
>   
>      Examples of API restrictions:
>      * Method can only be invoked by a subclass
>      * Method can only be accessed from within the same library (defined by the
>      Gradle library group id)
>      * Method can only be accessed from tests.
>   
>      You can add your own API restrictions with the @RestrictTo annotation.
>   
>   
>   The full lint text report is located at:
>     ...../build/workmanager/intermediates/lint_intermediate_text_report/debug/lintReportDebug/lint-results-debug.txt
> 
> * Try:
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':workmanager:lintDebug'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
>         at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:293)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
>         at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
>         at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
>         at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
>         at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
> Caused by: java.lang.RuntimeException: Lint found errors in the project; aborting build.
> 
> Fix the issues identified by lint, or create a baseline to see only new errors.
> To create a baseline, run `gradlew updateLintBaseline` after adding the following to the module's build.gradle file:
> ```
> android {
>     lint {
>         baseline = file("lint-baseline.xml")
>     }
> }
> ```
> For more details, see https://developer.android.com/studio/write/lint#snapshot
> 
> Lint found 1 errors, 4 warnings. First failure:
> 
> .../.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/DebugHelper.kt:17: Error: Success can only be accessed from within the same library group (referenced groupId=androidx.work from groupId=dev.fluttercommunity.workmanager) [RestrictedApi]
>             is ListenableWorker.Result.Success -> "\uD83C\uDF89"
> 
>    Explanation for issues of type "RestrictedApi":
>    This API has been flagged with a restriction that has not been met.
>    Examples of API restrictions:
>    * Method can only be invoked by a subclass
>    * Method can only be accessed from within the same library (defined by the
>    Gradle library group id)
>    * Method can only be accessed from tests.
> 
>    You can add your own API restrictions with the @RestrictTo annotation.
> 
> 
> The full lint text report is located at:
> ....  build/workmanager/intermediates/lint_intermediate_text_report/debug/lintReportDebug/lint-results-debug.txt
>         at com.android.build.gradle.internal.lint.AndroidLintWorkAction$Companion.maybeThrowException(AndroidLintWorkAction.kt:231)
>         at com.android.build.gradle.internal.lint.AndroidLintTextOutputTask.doTaskAction(AndroidLintTextOutputTask.kt:109)
>         at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:66)
>         at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
>         at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:97)
>         at jdk.internal.reflect.GeneratedMethodAccessor1309.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
>         at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
>         at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:229)
>         at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:212)
>         at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:195)
>         at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:162)
>         at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
>         at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
>         at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
>         at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
>         at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
>         at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
>         at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:42)
>         at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:75)
>         at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
>         at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
>         at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
>         at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
>         at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
>         at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
>         at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
>         at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:69)
>         at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:46)
>         at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
>         at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
>         at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
>         at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
>         at org.gradle.internal.Either$Right.fold(Either.java:175)
>         at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:62)
>         at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
>         at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
>         at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:46)
>         at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:35)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:75)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:53)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:53)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:35)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
>         at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:49)
>         at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:27)
>         at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:71)
>         at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:39)
>         at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
>         at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
>         at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:107)
>         at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:56)
>         at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
>         at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
>         at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
>         at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
>         at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
>         at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
>         at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
>         at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
>         at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
>         at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
>         at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
>         at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
>         at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
>         at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
>         at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
>         at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
>         at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
>         at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
>         at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
>         at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
>         at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
>         at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
>         at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
>         at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
>         at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
>         at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
>         at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
> BUILD FAILED in 25s
> 1678 actionable tasks: 104 executed, 1574 up-to-date


In my pubspec.yaml I've 
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  share_plus: ^10.1.1
  after_layout: ^1.2.0
  flip_card: ^0.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  language_code: ^0.5.5
  cloud_firestore: ^5.4.5
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  json_annotation: ^4.9.0
  gap: ^3.0.1
  firebase_crashlytics: ^4.1.4
  firebase_analytics: ^11.3.4
  flutter_launcher_icons: ^0.14.1
  go_router: ^14.6.0
  badges: ^3.1.2
  sign_in_with_apple: ^6.1.3
  url_launcher: ^6.3.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

```

```
------------------------------------------------------------
Gradle 8.10
------------------------------------------------------------
Build time:    2024-08-14 11:07:45 UTC
Revision:      fef2edbed8af1022cefaf44d4c0514c5f89d7b78
Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  17.0.12 (Oracle Corporation 17.0.12+8-LTS-286)
Daemon JVM:    '/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home' (from org.gradle.java.home)
OS:            Mac OS X 15.1.1 aarch64
```

```
Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (3 weeks ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3
```
