### ISSUE TITLE
Plugin doesn't work on iOS

### ISSUE THREAD

**Issue by t-kietzmann** [fluttercommunity/flutter_workmanager#403]
I'm trying to use the plugin on Android and iOS and followed both Platform instructions and I'm also run the example app.

On iOS I don't get any feedback, Android works as expected.

Flutter 3.0.2, Real Device iPhone SE iOS 15.1

**Comment by ncatallo** [comment]
I have the same issue.

I tried to print something on my callbackDispatcher. It's working on Android but the function is never called on iOS.

Flutter 3.0.5, Real Device iPhone 12 iOS 15.5

**Comment by AnasSafi** [comment]
Same issue, `Workmanager().executeTask((task, inputData) { // not reach here on IOS}`, i try with example app and my code, both not work on real device `IOS 16.0.2`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.4.0-34.0.pre, on macOS 12.6 21G115 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by ened** [comment]
iOS Background processing is slightly varied. Are you trying to submit a task using a specific ID and is the ID registered according to the instructions in the README? Remember you need to configure Info.plist with that ID as well.

Feel free to re-open with more details and perhaps a repro case.

**Comment by maxmitz** [comment]
I still have this issue. Does it work for the people that had this problem? What did you change?
