### ISSUE TITLE
WorkManager background service will stop running after a while

### ISSUE THREAD

**Issue by xiaoyaoking** [fluttercommunity/flutter_workmanager#415]
Background services stop at random times and can only run normally for three to five days.

The test results of multiple Android phones are basically the same. Android permissions enable background services, allow background processes, and turn off power saving mode.

**Comment by Nithinjovee** [comment]
is this issue fixed ?

**Comment by johnt1838** [comment]
Periodic Notifications stops after running once

**Comment by ened** [comment]
Please read https://dontkillmyapp.com

**Comment by xiaoyaoking** [comment]
> Please read https://dontkillmyapp.com
Saw it a long time ago. Power management and other restrictions have been manually adjusted, but still not enforced. I've switched to https://pub.dev/packages/background_fetch now. It's been running stable for a month now and everything works fine now.
