### ISSUE TITLE
No Such Module workmanager on Xcode

### ISSUE THREAD

**Issue by Kicky13** [fluttercommunity/flutter_workmanager#418]
✅ I have read the README
 ✅ I have done the setup for Android
 ✅ I have done the setup for iOS

0.4.0

Please help me solve this.
I already follow installation instruction for iOS and read entire documentation but still got an error

[✓] Flutter (Channel stable, 2.8.0, on macOS 12.5 21G72 darwin-arm, locale
    en-ID)
    • Flutter version 2.8.0 at /Users/crm-aksestoko/development/SDK/flutter28
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 months ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/crm-aksestoko/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • iPhone 13 Pro (mobile) • F9A4A20A-7A59-4C4B-88E3-FC6F8E7E97BF • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 104.0.5112.79
<img width="1440" alt="Screen Shot 2022-08-10 at 14 38 37" src="https://user-images.githubusercontent.com/32523482/183843329-bda3216b-194c-4f3d-b9ab-1801a81dce20.png">

**Comment by mmahgoub** [comment]
Have you tried to `flutter run` first?

**Comment by Kicky13** [comment]
> Have you tried to `flutter run` first?

Already did, but i've got this error
<img width="1440" alt="Screen Shot 2022-08-23 at 16 21 49" src="https://user-images.githubusercontent.com/32523482/186122367-4aa35d38-11c1-4533-acc0-602e4002bbc6.png">

**Comment by mmahgoub** [comment]
@Kicky13 I think it has something to do with WachOS enabled in the ios configuration, try to reset everything in your ios configuration, by deleting `ios` directory (you can move elsewhere as a backup) then run: `flutter create .' this will recreate the ios directory then `flutter run` again

**Comment by Kicky13** [comment]
> @Kicky13 I think it has something to do with WachOS enabled in the ios configuration, try to reset everything in your ios configuration, by deleting `ios` directory (you can move it elsewhere as a backup) then run: `flutter create .` this will recreate the ios directory then `flutter run` again and see if it works.

After recreating ios folder using  `flutter create .`, i've got this error when running `pod install` command.
![image](https://user-images.githubusercontent.com/32523482/186370017-006d895d-8db7-4400-b4fb-a32f23a22e51.png)

This error i've when try to running on device:
<img width="1440" alt="Screen Shot 2022-08-24 at 15 40 29" src="https://user-images.githubusercontent.com/32523482/186372457-e98b67b2-6e9e-4c32-836b-344dfe9d233b.png">

**Comment by mmahgoub** [comment]
@Kicky13 At the top of the Pod file in your ios directory you will find a similar line to this:
`# Uncomment this line to define a global platform for your project
platform :ios, '12.0'`
Set the platform to 12.0 and `flutter run` again

**Comment by Kicky13** [comment]
> @Kicky13 At the top of the Pod file in your ios directory you will find a similar line to this: `# Uncomment this line to define a global platform for your project` `platform :ios, '12.0'` Set the platform to 12.0 and `flutter run` again

I did it but this error show up:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32523482/186562372-1dcba4d7-3c5b-4b95-9087-05ca80624046.png">
Here's my pod file:
![image](https://user-images.githubusercontent.com/32523482/186562624-e7f6046a-8291-43d8-9e3f-4cf634152b3e.png)
And when i try to build via xcode here's error i've got:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32523482/186562910-3e5b49b3-e400-4928-a4a1-3167b812ea6f.png">

**Comment by mmahgoub** [comment]
now cd into ios dir and  `pod install` again :) then run

**Comment by Kicky13** [comment]
> @Kicky13 now cd into ios dir and `pod install` again :) then run

I did set deployment target to 12, then `pod install` and run on device, this error comes up:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32523482/187140140-6fe0be70-5837-4233-adc3-43b4bbfb8389.png">

**Comment by mmahgoub** [comment]
@Kicky13 😅  I would try to run it using Xcode I would imagine running it using AS is similar to `flutter run`

**Comment by Kicky13** [comment]
> @Kicky13 😅 I would try to run it using Xcode I would imagine running it using AS is similar to `flutter run`

I solve it, try `pod deintegrate` then `pod install`. But after that, some other library might had an error, just fix it by changing deployment target same value to `platform: 12.0` in my podfile then it work. Thank you for your help, i will close this issue.
