### ISSUE TITLE
🐞Error: No task request with identifier <decode: missing data> has been scheduled

### ISSUE THREAD

**Issue by mmahgoub** [fluttercommunity/flutter_workmanager#419]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |        0.5.0       |
| Xcode version        |        12.0       |
| Swift version        |       5.6.1        |
| iOS deployment target|         11.0      |

**Describe the error**
Describe error

Getting: `2022-08-12 14:55:40.460816+0200 Runner[5033:344896] Simulating launch for task with identifier workmanager.background.task
2022-08-12 14:55:43.708211+0200 Runner[5033:345195] No task request with identifier <decode: missing data> has been scheduled` when trying to simulate background task in physical device and simulator:
`e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"workmanager.background.task"]`

Output from the sample app:
```
e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"be.tramckrijte.workmanagerExample.simpleTask"]

2022-08-12 15:29:25.560905+0200 Runner[5336:366253] Simulating launch for task with identifier be.tramckrijte.workmanagerExample.simpleTask
2022-08-12 15:29:29.543499+0200 Runner[5336:366539] No task request with identifier <decode: missing data> has been scheduled
2022-08-12 15:29:29.543709+0200 Runner[5336:366549] [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```

**Output of `flutter doctor -v`**
`[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2 21D49 darwin-arm, locale en-SD)
    • Flutter version 3.0.5 at /Users/mmahgoub/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mmahgoub/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • R’s iPhone (mobile) • 00008030-001409563EC0402E • ios            • iOS 15.5 19F77
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by mmahgoub** [comment]
I would add that increasing the iOS deployment target to 12 or 13 hasn't solved the issue.

**Comment by mmahgoub** [comment]
As a workaround just use the default task for ios `Workmanager.iOSBackgroundTask`

**Comment by ened** [comment]
a) don't test this in simulator
b) have you adjusted your Info.plist?

please reopen as needed
