### ISSUE TITLE
Could not define Frequency as 3 minutes??

### ISSUE THREAD

**Issue by yeminsoe** [fluttercommunity/flutter_workmanager#420]
I would like to ask about frequency.
I found Frequency is 15 minutes. Is it for both iOS and Android?
Could I add 3 minutes in frequency for Android and iOS?
If not, how should I do to add frequency 3 minutes because I need to work once task every 3 minutes when app is in background.?

**Comment by minhtritc97** [comment]
u can try:
```
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) {
   // do something
  Workmanager().registerOneOffTask(
        'task-identifier',
        'simpleTask',
        initialDelay: const Duration(minutes: 3),
      );
return Future.value(true);
  });
}

void main() {
  Workmanager().initialize(
    callbackDispatcher, // The top level function, aka callbackDispatcher
    isInDebugMode: true // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );
  Workmanager().registerOneOffTask(
        'task-identifier',
        'simpleTask',
        initialDelay: const Duration(minutes: 3),
      );
  runApp(MyApp());
}
```
it 's just an idea, maybe it don't run

**Comment by ened** [comment]
15 minute minimum is enforced on Android - and not guaranteed either. If you need _realtime_ processing at such interval, consider running a long-lived background service.

**Comment by baranacikgoz** [comment]
@ened what do you mean by long-lived background service, I need it. Can you give example?
