### ISSUE TITLE
can workmanager handle background tasks in terminated state?

### ISSUE THREAD

**Issue by hasnainhayat** [fluttercommunity/flutter_workmanager#421]
Can you please guide about running tasks in terminated state.
Thanks

**Comment by ened** [comment]
The behaviour is different on each platform. If the App is user terminated on iOS, most likely not - ago least for the sole purpose of getting this plugin to act.

For Android, similar restrictions apply but you have a few more ways to get the App components activated. Try setting up a use case that applies to you.
