### ISSUE TITLE
🐞[NPE on StorageTask.isInProgress()]

### ISSUE THREAD

**Issue by luvishq** [fluttercommunity/flutter_workmanager#425]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version** : 0.5.0

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     0.5.0          |
| Xcode version        |        N/A       |
| Swift version        |     N/A          |
| iOS deployment target|     N/A          |

**Describe the error**
We are trying to perform the video upload task using the workmanager. This task is divided into two things:
1. Uploading the file to firebase storage
2. Saving the generated url to the firestore database.

It seems while performing the first task we are getting the below exception 

`E/AndroidRuntime(21314): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.storage.StorageTask.isInProgress()' on a null object reference
E/AndroidRuntime(21314): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.destroy(FlutterFirebaseStorageTask.java:144)
E/AndroidRuntime(21314): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.cancelInProgressTasks(FlutterFirebaseStorageTask.java:76)
E/AndroidRuntime(21314): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin.onDetachedFromEngine(FlutterFirebaseStoragePlugin.java:134)
E/AndroidRuntime(21314): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime(21314): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
E/AndroidRuntime(21314): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
E/AndroidRuntime(21314): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
E/AndroidRuntime(21314): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:427)
E/AndroidRuntime(21314): 	at be.tramckrijte.workmanager.BackgroundWorker.stopEngine$lambda-2(BackgroundWorker.kt:137)
E/AndroidRuntime(21314): 	at be.tramckrijte.workmanager.BackgroundWorker.lambda$u5fs2CPxJ29Hdjbap5WYUt2tGrg(Unknown Source:0)
E/AndroidRuntime(21314): 	at be.tramckrijte.workmanager.-$$Lambda$BackgroundWorker$u5fs2CPxJ29Hdjbap5WYUt2tGrg.run(Unknown Source:2)
E/AndroidRuntime(21314): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(21314): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21314): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(21314): 	at android.app.ActivityThread.main(ActivityThread.java:7263)
E/AndroidRuntime(21314): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21314): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(21314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
`
```
Code snippet
case uploadVideo:
        await Firebase.initializeApp();
        print("executing work manager task");
        print("$uploadVideo was executed. inputData = $inputData");
        final String inputFilePath = inputData!['filePath']! as String;
        final String currentUserId = inputData['currentUserId'] as String;
        final String prompt = inputData['prompt'] as String;
        uploadVideoToRepo(currentUserId, inputFilePath, prompt);
// upload video to repo:
Future<void> uploadVideoToRepo(String currentUserid, String inputFilePath, String prompt) async {
  var inputFile = File(inputFilePath);
  Repository().uploadVideo(currentUserId: currentUserid, file: inputFile, videoPrompt: prompt)
      .then((url) async {
    if(url != null) {
      // Set work manager result here
      Future.value(url);
      final _sharedPreference = await SharedPreferences.getInstance();
      _sharedPreference.setBool("isVideoUploaded", true);
    } else {
      // Set work manager result here failed
      Future.error("Couldn't upload video");
    }
  });

Future<String?> uploadVideo(
    {
    required String currentUserId,
    required File file,
  }) async {
    String? url;
    final uri = Uri.file(file.path);

    final storageReference = // hidden

    await storageReference.putFile(file).then(
      (value) async {
        url = await value.ref.getDownloadURL();
        final HttpsCallable callable = FirebaseFunctions.instance.httpsCallable(
          'cloud-function',
          options: HttpsCallableOptions(),
        );
        await callable({
          video: url,
        }).catchError((Object error) {
          FirebaseCrashlytics.instance.recordError(
            FirebaseException(message: error.toString(), plugin: 'FD'),
            StackTrace.current,
            reason: '',
          );
        });
      },
    );
    return url;
  }
```
Optionally provide the least amount of code that shows this behaviour. Ideally in the `sample` app.

**Output of `flutter doctor -v`**

[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.2 on channel stable at /Users/laavaans/Desktop/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/laavaans/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/laavaans/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Users/laavaans/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/laavaans/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM N975U (mobile) • R38M702ZLMF • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by AdamBridges** [comment]
Perhaps this line is the issue:
```
final _sharedPreference = await SharedPreferences.getInstance();
      _sharedPreference.setBool("isVideoUploaded", true);
```

I think I've encountered a similar issue when trying to access preferences from an isolate (which is what workmanager uses) and to solve it I included this line at the beginning of it: `DartPluginRegistrant.ensureInitialized();`

**Comment by luvishq** [comment]
Thanks @AdamBridges , now i am getting this error after adding that : 


```
E/AndroidRuntime(29061): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(29061): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.lambda$startTaskWithMethodChannel$3$FlutterFirebaseStorageTask(FlutterFirebaseStorageTask.java:252)
E/AndroidRuntime(29061): 	at io.flutter.plugins.firebase.storage.-$$Lambda$FlutterFirebaseStorageTask$l30n8-6B533ZYzRJRvaSfu1BF1M.run(Unknown Source:6)
E/AndroidRuntime(29061): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(29061): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29061): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(29061): 	at android.app.ActivityThread.main(ActivityThread.java:7263)
E/AndroidRuntime(29061): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29061): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(29061): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by AdamBridges** [comment]
> Thanks @AdamBridges , now i am getting this error after adding that :
> 
> ```
> E/AndroidRuntime(29061): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
> E/AndroidRuntime(29061): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.lambda$startTaskWithMethodChannel$3$FlutterFirebaseStorageTask(FlutterFirebaseStorageTask.java:252)
> ...
> ```

Have you tried adding `await` when setting the boolean? I'm not certain how isolates handle pending async operations if they're the last operation called before it closes, so could be worth trying. If that doesn't work, the `url` in `callable` could be null? Try using a logger or `debugPrint()` in your code to trace where it breaks. @luvishq

**Comment by ened** [comment]
Should be a bug in `firebase_storage`.
