### ISSUE TITLE
🐞[Getting task already registered on iOS]

### ISSUE THREAD

**Issue by luvishq** [fluttercommunity/flutter_workmanager#427]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.5.0         |
| Xcode version        |      14         |
| Swift version        |               |
| iOS deployment target|         13      |

**Describe the error**
It seems while trying to setup workmanager on iOS, I am getting the :

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Launch handler for task with identifier VideoTask has already been registered'

`
This is my setup :  

```
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

/// Registers all pubspec-referenced Flutter plugins in the given registry.
    static func registerPlugins(with registry: FlutterPluginRegistry) {
            GeneratedPluginRegistrant.register(with: registry)

       }
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
  if #available(iOS 10.0, *) {
        UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
      }
     FirebaseApp.configure()
    AppDelegate.registerPlugins(with: self) // Register the app's plugins in the context of a normal run

            WorkmanagerPlugin.setPluginRegistrantCallback { registry in
                // The following code will be called upon WorkmanagerPlugin's registration.
                // Note : all of the app's plugins may not be required in this context ;
                // instead of using GeneratedPluginRegistrant.register(with: registry),
                // you may want to register only specific plugins.
                AppDelegate.registerPlugins(with: registry)
            }
            WorkmanagerPlugin.registerTask(withIdentifier: "videoTask")
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func applicationDidBecomeActive(_ application: UIApplication) {
          signal(SIGPIPE, SIG_IGN);
      }

      override func applicationWillEnterForeground(_ application: UIApplication) {
          signal(SIGPIPE, SIG_IGN);
      }
}


```
Can someone point what is wrong ?

**Output of `flutter doctor -v`**

**Comment by jamescardona11** [comment]
Same problem here, I have the same configuration that the Readme.md and example/ios.

**Comment by ened** [comment]
Is it possible you run a separate background process in your iOS App, e.g. location services or other system reasons the App would start in the background?

The error seems correct from iOS side. You will need to wrap this line:
```
            WorkmanagerPlugin.registerTask(withIdentifier: "videoTask")
```

in a `if` conditional on a static Boolean variable `appWasStarted` or similar, to ensure the line is only executed once per app lifecycle.

**Comment by KalervoHyyppa** [comment]
Have the same issue mentioned above. It looks like you are correct in the above [comment](https://github.com/fluttercommunity/flutter_workmanager/issues/427#issuecomment-1287411352) that a location service is starting a process in the background for my app.

For reference, I'm using [Flutter Background Geolocation](https://pub.dev/packages/flutter_background_geolocation) which depends on [Background Fectch](https://pub.dev/packages/background_fetch) and that requires you to add an identifier to `BGTaskSchedulerPermittedIdentifiers` in info.plist (FYI kResetScheduleWorkManagerTaskIdentifier is the uniqueId I'm using for workmanager). 

```
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>kResetScheduleWorkManagerTaskIdentifier</string>
		<string>com.transistorsoft.fetch</string>
	</array>
```

Been troubleshooting for a few days now and I've tried using `UIApplication.shared.applicationState` in AppleDelegate.swift to detect the current app state when registering and have had no luck. 

```
     if (UIApplication.shared.applicationState != .background ) {
        WorkmanagerPlugin.registerTask(withIdentifier: "kResetScheduleWorkManagerTaskIdentifier")
     }
```


Do you have any suggestions on using these 2 packages together?

**Comment by edwardnagy** [comment]
@KalervoHyyppa Have you managed to find a solution? I think I am struggling with the same problem.

**Comment by KalervoHyyppa** [comment]
@edwardnagy Nope, not yet. @ened Do you happen to have any suggestions for the above [comment](https://github.com/fluttercommunity/flutter_workmanager/issues/427#issuecomment-1418250276)?

**Comment by ened** [comment]
Use a static boolean variable :)
