### ISSUE TITLE
🐞[ANDROID] Can't make http post request in callback dispatcher

### ISSUE THREAD

**Issue by NickLou26** [fluttercommunity/flutter_workmanager#440]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [] I have ran the sample app and it does not work there

**Describe the error**
I am trying to make an app where it will scan for ble devices in the background. I wanted to start by testing my http post requests in callBack Dispatcher but it doesn't seem to work.

@pragma('vm:entry-point') // Mandatory if the App is obfuscated or using Flutter 3.1+
void callbackDispatcher() {
  test.Workmanager().executeTask((task, inputData) {
    Networking(isFindCurrentUser: false).post(
        route: '/jobSchedule',
        body: {'WorkManager': 'Testing background'},
        isForCompany: true);
    print(
        "Native called background task: $task"); //simpleTask will be emitted here.
    return Future.value(true);
  });
}

void main() async {
...
test.Workmanager().registerOneOffTask(
      "oneoff-task-identifier", "simpleTask",
      initialDelay: Duration(seconds: 10));
...
}

I can see the print but not the post. The post works elsewhere because if i put it in my main(), it works.

**Output of `flutter doctor -v`**
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en)
    • Flutter version 3.3.4 on channel stable at /Users/Nick/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (4 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/Nick/dev/android_sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 09171FDD4006R8 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by graybrandonh** [comment]
@NickLou26 I don't know what networking package you're using, but it might be an async request and the isolate is finishing before your request is completed. Add an await to your post request?

**Comment by ened** [comment]
Code seems to not await for the network call to finish. Thx @graybrandonh
