### ISSUE TITLE
🐞[Enter Bug Description] PlatformException (PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.

### ISSUE THREAD

**Issue by Mariluk** [fluttercommunity/flutter_workmanager#441]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       5.0.1        |
| Xcode version        |       14.0.1         |
| Swift version        |        5.7       |
| iOS deployment target|        11.0       |

**Describe the error**
Describe error
Tested both in my application and in the example project of the super plugin

**Output of `Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-x64, locale
    cs-CZ)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability`**

**Comment by xunreal75** [comment]
Hi 

Please check following

The user has disabled background refresh in settings.
The app is running on Simulator which doesn’t support background processing.
The extension either hasn’t set RequestsOpenAccess to YES in The Info.plist File, or the user hasn’t granted open access.

I will add implementation of check for background refresh rights 

Thanks for your Feedback

**Comment by Mariluk** [comment]
oh, I ran the app in the simulator. Thanks for letting me know that it's not possible on the simulator. I couldn't find it anywhere. It's working.

**Comment by ened** [comment]
PRs welcome to update the README, @Mariluk - thank you!

**Comment by harunme3** [comment]
WorkmanagerPlugin.setPluginRegistrantCallback { (registry) in
            GeneratedPluginRegistrant.register(with: registry)
        }
Add this to the AppDelegate.swift file
