### ISSUE TITLE
🐞Could not start one time task under iOS

### ISSUE THREAD

**Issue by bambinoua** [fluttercommunity/flutter_workmanager#445]
I implemented all installation steps under iOS but stil could not run any background task.

![изображение](https://user-images.githubusercontent.com/45417992/201084290-bdb6e87c-c0a0-4a80-9feb-1672299fcd65.png)

**Comment by xunreal75** [comment]
Are trying to run this on simulator - it won't work.

Please check this on real device.

Your failure description is not helpful.

Please visit https://developer.apple.com/documentation/backgroundtasks/bgtaskschedulererrorcode/bgtaskschedulererrorcodeunavailable?language=objc

**Comment by bambinoua** [comment]
Thanks. I also discovered this. It works on real device.
