### ISSUE TITLE
[question] background only execution

### ISSUE THREAD

**Issue by feduke-nukem** [fluttercommunity/flutter_workmanager#457]
Do we have any mechanism to execute tasks only if application is not in foreground?

**Comment by ened** [comment]
That is sort of what this plugin does. You schedule a piece of work, that may run at any time (ideally, when the phone is not busy, charging etc).

**Comment by feduke-nukem** [comment]
> That is sort of what this plugin does. You schedule a piece of work, that may run at any time (ideally, when the phone is not busy, charging etc).

I mean, the plugin runs job even if app is in foreground. How could I prevent that?
