### ISSUE TITLE
is it possible to run wifi_iot plugin in background process inside callbackdispatcher method? 

### ISSUE THREAD

**Issue by rainamaharjan** [fluttercommunity/flutter_workmanager#462]
I implemented wifi_iot version 0.3.5 plugin in background process, but it show error like
missingpluginexception : missingpluginexception(no implementation found for method getssid on channel wifi_iot) in callbackdispatcher flutter

is there any solution to it?

**Comment by ened** [comment]
probably a issue with wifi_iot
