### ISSUE TITLE
Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?)

### ISSUE THREAD

**Issue by wechulimaven** [fluttercommunity/flutter_workmanager#464]
Running my flutter app am hitting into this

e: /Users/astroboy/development/flutter/.pub-cache/hosted/pub.dartlang.org/workmanager-0.4.1/android/src/main/kotlin/be/tramckrijte/workmanager/BackgroundWorker.kt: (132, 21): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /Users/astroboy/development/flutter/.pub-cache/hosted/pub.dartlang.org/workmanager-0.4.1/android/src/main/kotlin/be/tramckrijte/workmanager/BackgroundWorker.kt: (137, 25): 'error' overrides nothing

**Comment by ened** [comment]
Please use the latest plugin version. 0.4.1 is too old.
