### ISSUE TITLE
🐞Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)

### ISSUE THREAD

**Issue by TetrixGauss** [fluttercommunity/flutter_workmanager#467]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |         0.5.1      |
| Xcode version        |      14.2 & 14.3         |
| Swift version        |      5         |
| iOS deployment target|      13+         |

**Describe the error**
I am using m1 and when i am running the app i am getting the following in the workmanager.initialize() method:

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)`

I have tried from windows laptops and it seems that it works.

Any suggestions?

**Output of `flutter doctor -v`**
`[!] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale en-GR)
    • Flutter version 3.7.11 on channel stable at /Users/pp/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/pp/flutter. Consider adding
      /Users/pp/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (2 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/pp/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Users/pp/Downloads/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • SM A326B (mobile)           • RFCR2016WXA   • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available
`

**Comment by MaximVod** [comment]
same problem

**Comment by Aruljebaraj** [comment]
No implementation found for method backgroundChannelInitialized  -- same here

**Comment by ened** [comment]
Send a full minimal sample. Also please refer to the example app in this repo.

**Comment by TetrixGauss** [comment]
I have done exactly what the example says! The weird thing is that the work manager is working when I run the app from a PC with windows but not when I do it from MacBook (m1).

**Comment by ened** [comment]
Are you targeting a iOS or Mac app?
Can you share a minimal example of your app?

**Comment by TetrixGauss** [comment]
I am using a MacBook (m1) to create a flutter app that is tested on Android physical device at first and then on iOS! The problem is at the step of initialize.

**Comment by TetrixGauss** [comment]
any ideas anyone?

**Comment by ened** [comment]
I can not reproduce it., Please share a screen recording of your environment (full screen from click to run in your simulator) - maybe that provides a clue. Reopen the ticket when you have it.

**Comment by wonderkidshihab** [comment]
Having the same issue on android, any update?
