### ISSUE TITLE
Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.  This may be due to too many tasks being scheduled but not run.

### ISSUE THREAD

**Issue by luohao123** [fluttercommunity/flutter_workmanager#473]
Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.

This may be due to too many tasks being scheduled but not run.

**Comment by OE-Ahmed** [comment]
Please give me an alternative solution, If you have any.
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (7 months ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0

Above is my flutter version.

**Comment by OE-Ahmed** [comment]
The periodic register task of 15 minutes is completely working on Android but not working on iOS. I have to perform every 15 minutes task in iOS with the work manager how can I do it? Every time I get this error while registering periodic time with 15 mites in iOS. Anyone, please reply or suggest any other alternative solution to me.

Error: PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null, null)

Workmanager plugin full setup in ios done

**Comment by ened** [comment]
Run a one-off gas, then within that task execution, schedule the next.
Unfortunately iOS may decide to reschedule to a arbitrary time in the future.

Perform such work server-side if you can.
