### ISSUE TITLE
 Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.

### ISSUE THREAD

**Issue by luohao123** [fluttercommunity/flutter_workmanager#474]
Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.

**Comment by dab246** [comment]
I have a similar problem when running `example` on ios

**Comment by ened** [comment]
https://stackoverflow.com/a/58683962/375209 - please  check here. iOS simulator does not support background tasks.
