### ISSUE TITLE
🐞BGTaskSchedulerErrorDomain Code=3

### ISSUE THREAD

**Issue by robertjones1** [fluttercommunity/flutter_workmanager#479]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=3 "(null)") error, Scheduling the task using BGTaskScheduler has failed.

This may be due to too many tasks being scheduled but not run.

**Comment by jsshizhan** [comment]
same issue

**Comment by ened** [comment]
https://stackoverflow.com/a/58224050/375209 - you are probably missing on permissions.
