### ISSUE TITLE
🐞Android: terminating leads to stop background task

### ISSUE THREAD

**Issue by themw123** [fluttercommunity/flutter_workmanager#480]
**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.5.1         |
| Flutter version  |      3.10.2         |
| S10e  |      12       |
| A52  |      13         |
| s23 Ultra  |      13         |

On some devices(galaxy s10e and A52) it is fine terminating the app with a swipe. The background task will continue.
On other devices(s23 ultra) it wont continue background task if terminating the app with a swipe.
On all devices i am requesting and accepting Permission.ignoreBatteryOptimizations. If i dont request for this permission it wont work even on galaxy s10e and A52, i think because of the fact that power saving mode is enabled.

I am using the example code from readme

**Comment by themw123** [comment]
> **Version**
> 
> | Technology           | Version       |
> | -------------------  | ------------- |
> | Workmanager version  |      0.5.1         |
> | Flutter version  |      3.7.10         |
> | S10e  |      12       |
> | A52  |      13         |
> | s23 Ultra  |      13         |
> 
> On some devices(galaxy s10e and A52) it is fine terminating the app with a swipe. The background task will continue.
> On other devices(s23 ultra) it wont continue background task if terminating the app with a swipe.
> On all devices i am requesting and accepting Permission.ignoreBatteryOptimizations. If i dont request for this permission it wont work even on galaxy s10e and A52, i think because of the fact that power saving mode is enabled.
> 
> I am using the example code from readme
>

**Comment by ened** [comment]
This is unfortunately expected. Different versions of Android behave differently.
