### ISSUE TITLE
[question]  how to make background process long lived?

### ISSUE THREAD

**Issue by agufagit** [fluttercommunity/flutter_workmanager#485]
I'm making a background notification process using workmanager with a websocket connection.  It looks to me that workmanager background process just stops after `return Future.value(true);` and closes websocket connection.  Is there anyway to make it long lived?

Thank you

**Comment by xunreal75** [comment]
No because isolated , it’s not possible to let websocket living. Furthermore it would decrease the  battery level which is only allowed on special apps like music or navigation.
