### ISSUE TITLE
🐞Periodic Task are not working on iOS.

### ISSUE THREAD

**Issue by anmolgupta321** [fluttercommunity/flutter_workmanager#487]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  | 0.5.1 |
| Xcode version        |       14.3        |
| Swift version        |       5.0        |
| iOS deployment target|        15.2       |

**Describe the error**
When running the flutter app on iOS with workmanager configs, I am getting Platform exception error.
Exact Error:
```
[log] PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null, null)
      PlatformException(unhandledMethod("registerPeriodicTask") error, Unhandled method registerPeriodicTask, null, null)
      #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
      #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
      <asynchronous suspension>
      #2      Workmanager.registerPeriodicTask (package:workmanager/src/workmanager.dart:228:7)
      <asynchronous suspension>
```

**Output of `flutter doctor -v`**

**Comment by anmolgupta321** [comment]
@ened 
Does work manager package supports periodic task after every 15 mins on iOS?

**Comment by emiliodallatorre** [comment]
The plugin documentation **clearly** states that this is not supported.
In addition, even with native code, iOS does not support the execution of a **periodic** background task.

**Comment by ened** [comment]
Maybe the plugin should print warnings in the console, or throw an exception if a developer attempts to use these APIs on iOS.
