### ISSUE TITLE
* What went wrong: Execution failed for task ':app:checkDebugDuplicateClasses'. > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable   > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.7.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20)    Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains

### ISSUE THREAD

**Issue by shakibhoseen** [fluttercommunity/flutter_workmanager#526]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |               |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
Describe error
Optionally provide the least amount of code that shows this behaviour. Ideally in the `sample` app.

**Output of `flutter doctor -v`**

**Comment by BingCoke** [comment]
I fight with it for a day, and fix it!
add next code in android/build.gradle
```
  configurations.all {
    resolutionStrategy {
        eachDependency {
            if ((requested.group == "org.jetbrains.kotlin") && (requested.name.startsWith("kotlin-stdlib"))) {
                useVersion("1.8.22")
            }
        }
    }
  }
```
put it in 'allprojects'

**Comment by hgari** [comment]
thanks @BingCoke !

**Comment by shakibhoseen** [comment]
thank you so much @BingCoke

**Comment by md-rifatkhan** [comment]
After 3 hour of coding i just got this 😂😂, how pain that was,

Thank you so much @BingCoke

**Comment by maz341** [comment]
I changed my Kotlin version to 1.8.22.

android -> settings.gradle

`    id "org.jetbrains.kotlin.android" version "1.8.22" apply false`

**Comment by Navindu-Ashen** [comment]
thankyou @BingCoke

**Comment by followthemoney1** [comment]
> id "org.jetbrains.kotlin.android" version "1.8.22" apply false

works for me, thanks
