### ISSUE TITLE
pub.dev 0.5.2 is not the latest version

### ISSUE THREAD

**Issue by albertogjunior** [fluttercommunity/flutter_workmanager#549]
I am using the latest version of the plugin from pub.dev but that version is no compatible with the READM.ME from the package. The new Swift classes is not available on 0.5.2, but when I looked at the MAIN branch here at GitHub I can see the new classes.

Am I missing something or is there supposed to be a new version of the plugin that is not available at pub.dev yet?

Thanks Team.

**Comment by ened** [comment]
@albertogjunior that is correct, the plugin is undergoing major refactor work at the moment. Please refer to the readme within the pub.dev package.

**Comment by albertogjunior** [comment]
> @albertogjunior that is correct, the plugin is undergoing major refactor work at the moment. Please refer to the readme within the pub.dev package.

Thanks Sebastian. Unfortunately the iOS and Android setup docs in the 0.5.2 release in pub.dev are already pointing to the new features setup that you are working on not for the current version.
